-- ============================================================================
-- Puzzle pool expansion — batch 7: ALL CASUAL, 5+ letters only. +25 per category
-- (×12 = 300, 100% casual). Every phrase ≥5 letters. Fresh angles per category
-- (picture books, snack/candy brands, athletes, desserts, animated films, recent
-- pop hits, US cities, animals, sports events, devices/hardware). Deduped
-- case-insensitively against all prior batches. Data-only (prod), survives reset.
-- ============================================================================
BEGIN;

INSERT INTO public.daily_puzzles (phrase, category, clue, pool)
SELECT v.phrase, v.category, v.clue, v.pool
FROM (VALUES
-- ── Books & Characters 📚 (picture-book classics) ──────────────────────────
('Where the Wild Things Are', 'Books & Characters 📚', $$Max sails to where the monsters roar.$$, 'casual'),
('The Very Hungry Caterpillar', 'Books & Characters 📚', $$It eats through the week and becomes a butterfly.$$, 'casual'),
('Goodnight Moon', 'Books & Characters 📚', $$Saying goodnight to everything in the room.$$, 'casual'),
('The Cat in the Hat', 'Books & Characters 📚', $$A troublemaker in a red-striped hat.$$, 'casual'),
('Green Eggs and Ham', 'Books & Characters 📚', $$Sam I Am wont take no for an answer.$$, 'casual'),
('Oh the Places Youll Go', 'Books & Characters 📚', $$Seuss graduation favorite.$$, 'casual'),
('The Lorax', 'Books & Characters 📚', $$He speaks for the trees.$$, 'casual'),
('Horton Hears a Who', 'Books & Characters 📚', $$An elephant protects a tiny world.$$, 'casual'),
('If You Give a Mouse a Cookie', 'Books & Characters 📚', $$One request leads to another.$$, 'casual'),
('The Rainbow Fish', 'Books & Characters 📚', $$Sharing his shimmering scales.$$, 'casual'),
('Corduroy', 'Books & Characters 📚', $$A teddy bear missing a button.$$, 'casual'),
('The Snowy Day', 'Books & Characters 📚', $$Peter explores after a snowfall.$$, 'casual'),
('Brown Bear Brown Bear', 'Books & Characters 📚', $$What do you see?$$, 'casual'),
('Guess How Much I Love You', 'Books & Characters 📚', $$Nutbrown hares love contest.$$, 'casual'),
('Love You Forever', 'Books & Characters 📚', $$Ill like you for always.$$, 'casual'),
('The Kissing Hand', 'Books & Characters 📚', $$A raccoon nervous for school.$$, 'casual'),
('Chicka Chicka Boom Boom', 'Books & Characters 📚', $$Letters climb a coconut tree.$$, 'casual'),
('The Polar Express', 'Books & Characters 📚', $$A train to the North Pole.$$, 'casual'),
('Cloudy with a Chance of Meatballs', 'Books & Characters 📚', $$Food falls from the sky.$$, 'casual'),
('Where the Sidewalk Ends', 'Books & Characters 📚', $$Shel Silverstein poems.$$, 'casual'),
('The Napping House', 'Books & Characters 📚', $$Everyone piles onto one bed.$$, 'casual'),
('Stellaluna', 'Books & Characters 📚', $$A fruit bat raised by birds.$$, 'casual'),
('The Giving Tree', 'Books & Characters 📚', $$A tree that keeps on giving.$$, 'casual'),
('Make Way for Ducklings', 'Books & Characters 📚', $$A duck family crosses Boston.$$, 'casual'),
('The Little Engine That Could', 'Books & Characters 📚', $$I think I can, I think I can.$$, 'casual'),
-- ── Brands & Logos 🏷️ (snacks, candy, coffee) ──────────────────────────────
('Gatorade', 'Brands & Logos 🏷️', $$Sideline sports drink.$$, 'casual'),
('Powerade', 'Brands & Logos 🏷️', $$Cokes sports-drink rival.$$, 'casual'),
('Nespresso', 'Brands & Logos 🏷️', $$Pod espresso, Clooney ads.$$, 'casual'),
('Keurig', 'Brands & Logos 🏷️', $$K-Cup coffee maker.$$, 'casual'),
('Folgers', 'Brands & Logos 🏷️', $$The best part of waking up.$$, 'casual'),
('Tim Hortons', 'Brands & Logos 🏷️', $$Canadian coffee and donuts.$$, 'casual'),
('Nestle', 'Brands & Logos 🏷️', $$Swiss food and chocolate giant.$$, 'casual'),
('Ghirardelli', 'Brands & Logos 🏷️', $$San Francisco chocolate squares.$$, 'casual'),
('Toblerone', 'Brands & Logos 🏷️', $$Triangular Swiss chocolate bar.$$, 'casual'),
('Godiva', 'Brands & Logos 🏷️', $$Gold-box premium chocolates.$$, 'casual'),
('Cadbury', 'Brands & Logos 🏷️', $$British chocolate, purple wrapper.$$, 'casual'),
('Nutella', 'Brands & Logos 🏷️', $$Hazelnut chocolate spread.$$, 'casual'),
('Pringles', 'Brands & Logos 🏷️', $$Chips in a tube, mustachioed mascot.$$, 'casual'),
('Tostitos', 'Brands & Logos 🏷️', $$Tortilla chips for the dip.$$, 'casual'),
('Cheetos', 'Brands & Logos 🏷️', $$Crunchy orange cheese snack.$$, 'casual'),
('Ruffles', 'Brands & Logos 🏷️', $$Ridged potato chips.$$, 'casual'),
('Fritos', 'Brands & Logos 🏷️', $$Corn chips for chili.$$, 'casual'),
('Triscuit', 'Brands & Logos 🏷️', $$Woven whole-wheat crackers.$$, 'casual'),
('Goldfish', 'Brands & Logos 🏷️', $$The snack that smiles back.$$, 'casual'),
('Wheaties', 'Brands & Logos 🏷️', $$Breakfast of champions.$$, 'casual'),
('Pedialyte', 'Brands & Logos 🏷️', $$Rehydration drink.$$, 'casual'),
('Caribou Coffee', 'Brands & Logos 🏷️', $$Minnesota coffee chain.$$, 'casual'),
('Sun Chips', 'Brands & Logos 🏷️', $$Multigrain wavy chips.$$, 'casual'),
('Lindt', 'Brands & Logos 🏷️', $$Swiss chocolate truffle balls.$$, 'casual'),
('Peets Coffee', 'Brands & Logos 🏷️', $$Bay Area dark-roast chain.$$, 'casual'),
-- ── Famous People 🌟 (athletes) ─────────────────────────────────────────────
('Michael Jordan', 'Famous People 🌟', $$Bulls legend, the GOAT of hoops.$$, 'casual'),
('LeBron James', 'Famous People 🌟', $$King James, all-time scoring leader.$$, 'casual'),
('Kobe Bryant', 'Famous People 🌟', $$Black Mamba, Lakers icon.$$, 'casual'),
('Serena Williams', 'Famous People 🌟', $$23 Grand Slam singles titles.$$, 'casual'),
('Tiger Woods', 'Famous People 🌟', $$Golf superstar in a red Sunday shirt.$$, 'casual'),
('Muhammad Ali', 'Famous People 🌟', $$Float like a butterfly.$$, 'casual'),
('Usain Bolt', 'Famous People 🌟', $$Worlds fastest man.$$, 'casual'),
('Tom Brady', 'Famous People 🌟', $$Seven-time Super Bowl QB.$$, 'casual'),
('Lionel Messi', 'Famous People 🌟', $$Argentine soccer maestro.$$, 'casual'),
('Cristiano Ronaldo', 'Famous People 🌟', $$Portuguese goal machine, siuu.$$, 'casual'),
('Wayne Gretzky', 'Famous People 🌟', $$The Great One of hockey.$$, 'casual'),
('Babe Ruth', 'Famous People 🌟', $$The Sultan of Swat.$$, 'casual'),
('Jackie Robinson', 'Famous People 🌟', $$Broke baseballs color barrier.$$, 'casual'),
('Simone Biles', 'Famous People 🌟', $$Most decorated gymnast ever.$$, 'casual'),
('Michael Phelps', 'Famous People 🌟', $$23 Olympic gold medals.$$, 'casual'),
('Roger Federer', 'Famous People 🌟', $$Swiss tennis elegance.$$, 'casual'),
('Rafael Nadal', 'Famous People 🌟', $$King of Clay.$$, 'casual'),
('Shaquille Oneal', 'Famous People 🌟', $$Dominant Lakers center, Shaq.$$, 'casual'),
('Magic Johnson', 'Famous People 🌟', $$Showtime Lakers point guard.$$, 'casual'),
('Larry Bird', 'Famous People 🌟', $$Celtics sharpshooter.$$, 'casual'),
('Peyton Manning', 'Famous People 🌟', $$Omaha-calling QB legend.$$, 'casual'),
('Derek Jeter', 'Famous People 🌟', $$Yankees captain, Mr November.$$, 'casual'),
('Venus Williams', 'Famous People 🌟', $$Serenas champion sister.$$, 'casual'),
('Floyd Mayweather', 'Famous People 🌟', $$Undefeated boxing showman.$$, 'casual'),
-- ── Food & Drink 🍔 (desserts and drinks) ──────────────────────────────────
('Tiramisu', 'Food & Drink 🍔', $$Coffee-soaked Italian dessert.$$, 'casual'),
('Cannoli', 'Food & Drink 🍔', $$Crispy shell with sweet ricotta.$$, 'casual'),
('Panna Cotta', 'Food & Drink 🍔', $$Silky Italian cream dessert.$$, 'casual'),
('Creme Brulee', 'Food & Drink 🍔', $$Custard with a torched sugar crust.$$, 'casual'),
('Profiterole', 'Food & Drink 🍔', $$Cream puff with chocolate.$$, 'casual'),
('Eclair', 'Food & Drink 🍔', $$Long cream-filled pastry.$$, 'casual'),
('Macaron', 'Food & Drink 🍔', $$Colorful French sandwich cookie.$$, 'casual'),
('Baklava', 'Food & Drink 🍔', $$Honey, nuts, and phyllo layers.$$, 'casual'),
('Churros', 'Food & Drink 🍔', $$Fried dough in cinnamon sugar.$$, 'casual'),
('Beignet', 'Food & Drink 🍔', $$New Orleans powdered fried dough.$$, 'casual'),
('Cobbler', 'Food & Drink 🍔', $$Baked fruit under a biscuit top.$$, 'casual'),
('Bread Pudding', 'Food & Drink 🍔', $$Custardy baked stale bread.$$, 'casual'),
('Banana Split', 'Food & Drink 🍔', $$Three scoops in a long dish.$$, 'casual'),
('Root Beer Float', 'Food & Drink 🍔', $$Soda with a scoop of vanilla.$$, 'casual'),
('Milkshake', 'Food & Drink 🍔', $$Blended ice cream drink.$$, 'casual'),
('Smoothie', 'Food & Drink 🍔', $$Blended fruit drink.$$, 'casual'),
('Lemonade', 'Food & Drink 🍔', $$Sweet-tart summer refresher.$$, 'casual'),
('Cappuccino', 'Food & Drink 🍔', $$Espresso topped with foam.$$, 'casual'),
('Macchiato', 'Food & Drink 🍔', $$Espresso marked with milk.$$, 'casual'),
('Frappuccino', 'Food & Drink 🍔', $$Starbucks blended iced drink.$$, 'casual'),
('Espresso', 'Food & Drink 🍔', $$Concentrated coffee shot.$$, 'casual'),
('Affogato', 'Food & Drink 🍔', $$Gelato drowned in espresso.$$, 'casual'),
('Horchata', 'Food & Drink 🍔', $$Sweet cinnamon rice drink.$$, 'casual'),
('Hot Chocolate', 'Food & Drink 🍔', $$Warm cocoa with marshmallows.$$, 'casual'),
-- ── Movies & TV 🎬 (animated films) ─────────────────────────────────────────
('Monsters Inc', 'Movies & TV 🎬', $$Sully and Mike scare for energy.$$, 'casual'),
('Finding Dory', 'Movies & TV 🎬', $$The forgetful fish gets her own film.$$, 'casual'),
('The Incredibles', 'Movies & TV 🎬', $$A family of supers.$$, 'casual'),
('Ratatouille', 'Movies & TV 🎬', $$A rat who wants to be a chef.$$, 'casual'),
('Wall E', 'Movies & TV 🎬', $$A lonely trash-compacting robot.$$, 'casual'),
('Brave', 'Movies & TV 🎬', $$Scottish princess Merida and her bow.$$, 'casual'),
('Onward', 'Movies & TV 🎬', $$Elf brothers on a magical quest.$$, 'casual'),
('Turning Red', 'Movies & TV 🎬', $$Teen turns into a giant red panda.$$, 'casual'),
('Encanto', 'Movies & TV 🎬', $$We dont talk about Bruno.$$, 'casual'),
('Zootopia', 'Movies & TV 🎬', $$A bunny cop and a fox con artist.$$, 'casual'),
('Tangled', 'Movies & TV 🎬', $$Rapunzel lets down her hair.$$, 'casual'),
('Big Hero 6', 'Movies & TV 🎬', $$Hiro and the inflatable robot Baymax.$$, 'casual'),
('Wreck It Ralph', 'Movies & TV 🎬', $$A video-game villain wants to be good.$$, 'casual'),
('Kung Fu Panda', 'Movies & TV 🎬', $$Po the panda becomes a warrior.$$, 'casual'),
('How to Train Your Dragon', 'Movies & TV 🎬', $$Hiccup befriends Toothless.$$, 'casual'),
('Despicable Me', 'Movies & TV 🎬', $$Gru and his minions.$$, 'casual'),
('The Croods', 'Movies & TV 🎬', $$A prehistoric family road trip.$$, 'casual'),
('Trolls', 'Movies & TV 🎬', $$Colorful singing troll dolls.$$, 'casual'),
('Happy Feet', 'Movies & TV 🎬', $$A penguin who tap dances.$$, 'casual'),
('Ice Age', 'Movies & TV 🎬', $$Manny, Sid, and Diego.$$, 'casual'),
('Shrek', 'Movies & TV 🎬', $$An ogre and a talking donkey.$$, 'casual'),
('Megamind', 'Movies & TV 🎬', $$A supervillain with no hero to fight.$$, 'casual'),
('Paranorman', 'Movies & TV 🎬', $$A boy who talks to the dead.$$, 'casual'),
('The Boxtrolls', 'Movies & TV 🎬', $$Creatures who live in cardboard boxes.$$, 'casual'),
-- ── Music 🎵 (recent pop hits) ──────────────────────────────────────────────
('Levitating', 'Music 🎵', $$Dua Lipa disco-pop hit.$$, 'casual'),
('Blinding Lights', 'Music 🎵', $$The Weeknd 80s-style smash.$$, 'casual'),
('Watermelon Sugar', 'Music 🎵', $$Harry Styles summer single.$$, 'casual'),
('Dont Start Now', 'Music 🎵', $$Dua Lipa dancefloor anthem.$$, 'casual'),
('Good For U', 'Music 🎵', $$Olivia Rodrigo pop-punk breakup.$$, 'casual'),
('Drivers License', 'Music 🎵', $$Olivia Rodrigo debut ballad.$$, 'casual'),
('As It Was', 'Music 🎵', $$Harry Styles chart-topper.$$, 'casual'),
('Anti Hero', 'Music 🎵', $$Taylor Swift, its me, hi.$$, 'casual'),
('Flowers', 'Music 🎵', $$Miley Cyrus, I can buy myself flowers.$$, 'casual'),
('Unholy', 'Music 🎵', $$Sam Smith and Kim Petras duet.$$, 'casual'),
('Butter', 'Music 🎵', $$BTS smooth like this.$$, 'casual'),
('Heat Waves', 'Music 🎵', $$Glass Animals sleeper hit.$$, 'casual'),
('Industry Baby', 'Music 🎵', $$Lil Nas X and Jack Harlow.$$, 'casual'),
('Peaches', 'Music 🎵', $$Justin Bieber, I got my peaches.$$, 'casual'),
('Save Your Tears', 'Music 🎵', $$The Weeknd synth hit.$$, 'casual'),
('Montero', 'Music 🎵', $$Lil Nas X, call me by your name.$$, 'casual'),
('Circles', 'Music 🎵', $$Post Malone, run away.$$, 'casual'),
('Someone You Loved', 'Music 🎵', $$Lewis Capaldi heartbreak ballad.$$, 'casual'),
('Bad Guy', 'Music 🎵', $$Billie Eilish, duh.$$, 'casual'),
('Senorita', 'Music 🎵', $$Shawn Mendes and Camila duet.$$, 'casual'),
('Sucker', 'Music 🎵', $$Jonas Brothers comeback single.$$, 'casual'),
('Sicko Mode', 'Music 🎵', $$Travis Scott multi-part hit.$$, 'casual'),
('Rockstar', 'Music 🎵', $$Post Malone featuring 21 Savage.$$, 'casual'),
('Ghost', 'Music 🎵', $$Justin Bieber, missing someone.$$, 'casual'),
-- ── Phrases & Sayings 🗣️ ───────────────────────────────────────────────────
('Steal the Show', 'Phrases & Sayings 🗣️', $$Get all the attention.$$, 'casual'),
('Take a Rain Check', 'Phrases & Sayings 🗣️', $$Postpone to another time.$$, 'casual'),
('The Ball Is in Your Court', 'Phrases & Sayings 🗣️', $$Its your move now.$$, 'casual'),
('Through Thick and Thin', 'Phrases & Sayings 🗣️', $$In good times and bad.$$, 'casual'),
('Twist Someones Arm', 'Phrases & Sayings 🗣️', $$Persuade reluctantly.$$, 'casual'),
('Under the Table', 'Phrases & Sayings 🗣️', $$Done secretly.$$, 'casual'),
('Up in the Air', 'Phrases & Sayings 🗣️', $$Still uncertain.$$, 'casual'),
('Wear Your Heart on Your Sleeve', 'Phrases & Sayings 🗣️', $$Show emotions openly.$$, 'casual'),
('When Pigs Fly', 'Phrases & Sayings 🗣️', $$Never going to happen.$$, 'casual'),
('Wrap Your Head Around', 'Phrases & Sayings 🗣️', $$Finally understand.$$, 'casual'),
('You Can Say That Again', 'Phrases & Sayings 🗣️', $$I totally agree.$$, 'casual'),
('A Leopard Cant Change Its Spots', 'Phrases & Sayings 🗣️', $$People dont really change.$$, 'casual'),
('Bite Off More Than You Can Chew', 'Phrases & Sayings 🗣️', $$Take on too much.$$, 'casual'),
('Burn Bridges', 'Phrases & Sayings 🗣️', $$Destroy relationships for good.$$, 'casual'),
('Cut Corners', 'Phrases & Sayings 🗣️', $$Do it cheaply or carelessly.$$, 'casual'),
('Devils Advocate', 'Phrases & Sayings 🗣️', $$Argue the opposite for debate.$$, 'casual'),
('Face the Music', 'Phrases & Sayings 🗣️', $$Accept the consequences.$$, 'casual'),
('Fish Out of Water', 'Phrases & Sayings 🗣️', $$Out of your element.$$, 'casual'),
('Get Your Act Together', 'Phrases & Sayings 🗣️', $$Sort yourself out.$$, 'casual'),
('Go the Extra Mile', 'Phrases & Sayings 🗣️', $$Do more than required.$$, 'casual'),
('Hit the Nail on the Head', 'Phrases & Sayings 🗣️', $$Get it exactly right.$$, 'casual'),
('Jump on the Bandwagon', 'Phrases & Sayings 🗣️', $$Follow the trend.$$, 'casual'),
('Keep Your Chin Up', 'Phrases & Sayings 🗣️', $$Stay positive.$$, 'casual'),
('Let Sleeping Dogs Lie', 'Phrases & Sayings 🗣️', $$Dont stir up trouble.$$, 'casual'),
-- ── Places & Travel ✈️ (US cities) ──────────────────────────────────────────
('Nashville', 'Places & Travel ✈️', $$Music City, home of country.$$, 'casual'),
('Memphis', 'Places & Travel ✈️', $$Graceland and BBQ, Tennessee.$$, 'casual'),
('Austin', 'Places & Travel ✈️', $$Keep it weird, Texas capital.$$, 'casual'),
('Portland', 'Places & Travel ✈️', $$Roses and food carts, Oregon.$$, 'casual'),
('Denver', 'Places & Travel ✈️', $$Mile-high Colorado city.$$, 'casual'),
('Phoenix', 'Places & Travel ✈️', $$Desert Arizona capital.$$, 'casual'),
('San Diego', 'Places & Travel ✈️', $$Sunny SoCal beaches and zoo.$$, 'casual'),
('Sacramento', 'Places & Travel ✈️', $$Californias capital city.$$, 'casual'),
('Minneapolis', 'Places & Travel ✈️', $$Twin city on the Mississippi.$$, 'casual'),
('Milwaukee', 'Places & Travel ✈️', $$Wisconsin beer and brats.$$, 'casual'),
('Cleveland', 'Places & Travel ✈️', $$Rock Hall on Lake Erie.$$, 'casual'),
('Cincinnati', 'Places & Travel ✈️', $$Ohio chili and the Reds.$$, 'casual'),
('Pittsburgh', 'Places & Travel ✈️', $$City of bridges and steel.$$, 'casual'),
('Baltimore', 'Places & Travel ✈️', $$Maryland crab cakes and harbor.$$, 'casual'),
('Louisville', 'Places & Travel ✈️', $$Kentucky Derby city.$$, 'casual'),
('Raleigh', 'Places & Travel ✈️', $$North Carolina research triangle.$$, 'casual'),
('Kansas City', 'Places & Travel ✈️', $$Barbecue and jazz crossroads.$$, 'casual'),
('Oklahoma City', 'Places & Travel ✈️', $$Sooner State capital.$$, 'casual'),
('Albuquerque', 'Places & Travel ✈️', $$New Mexico balloon fiesta.$$, 'casual'),
('Tucson', 'Places & Travel ✈️', $$Saguaro-lined Arizona city.$$, 'casual'),
('El Paso', 'Places & Travel ✈️', $$Texas border city.$$, 'casual'),
('Boise', 'Places & Travel ✈️', $$Idahos capital.$$, 'casual'),
('Anchorage', 'Places & Travel ✈️', $$Largest city in Alaska.$$, 'casual'),
('Honolulu', 'Places & Travel ✈️', $$Hawaiis capital on Oahu.$$, 'casual'),
-- ── Science & Nature 🔬 (animals) ───────────────────────────────────────────
('Cheetah', 'Science & Nature 🔬', $$Fastest land animal.$$, 'casual'),
('Gazelle', 'Science & Nature 🔬', $$Graceful leaping antelope.$$, 'casual'),
('Cougar', 'Science & Nature 🔬', $$Mountain lion of the Americas.$$, 'casual'),
('Panther', 'Science & Nature 🔬', $$A black big cat.$$, 'casual'),
('Antelope', 'Science & Nature 🔬', $$Swift horned grazer.$$, 'casual'),
('Buffalo', 'Science & Nature 🔬', $$Shaggy plains bovine.$$, 'casual'),
('Rhinoceros', 'Science & Nature 🔬', $$Horned thick-skinned giant.$$, 'casual'),
('Hippopotamus', 'Science & Nature 🔬', $$River giant with a huge mouth.$$, 'casual'),
('Crocodile', 'Science & Nature 🔬', $$Toothy river reptile.$$, 'casual'),
('Alligator', 'Science & Nature 🔬', $$Broad-snouted swamp reptile.$$, 'casual'),
('Chameleon', 'Science & Nature 🔬', $$Color-changing lizard.$$, 'casual'),
('Iguana', 'Science & Nature 🔬', $$Spiny tropical lizard.$$, 'casual'),
('Salamander', 'Science & Nature 🔬', $$Slippery amphibian.$$, 'casual'),
('Porcupine', 'Science & Nature 🔬', $$Rodent covered in quills.$$, 'casual'),
('Armadillo', 'Science & Nature 🔬', $$Armored rolling mammal.$$, 'casual'),
('Hedgehog', 'Science & Nature 🔬', $$Small spiny insect-eater.$$, 'casual'),
('Meerkat', 'Science & Nature 🔬', $$Upright desert sentry.$$, 'casual'),
('Platypus', 'Science & Nature 🔬', $$Egg-laying duck-billed mammal.$$, 'casual'),
('Wombat', 'Science & Nature 🔬', $$Burrowing Australian marsupial.$$, 'casual'),
('Koala', 'Science & Nature 🔬', $$Eucalyptus-eating marsupial.$$, 'casual'),
('Lemur', 'Science & Nature 🔬', $$Ring-tailed Madagascar primate.$$, 'casual'),
('Sloth', 'Science & Nature 🔬', $$Slowest mammal in the trees.$$, 'casual'),
('Otter', 'Science & Nature 🔬', $$Playful river swimmer.$$, 'casual'),
('Raccoon', 'Science & Nature 🔬', $$Masked nighttime forager.$$, 'casual'),
-- ── Sports 🏆 (sports and events) ───────────────────────────────────────────
('Backhand', 'Sports 🏆', $$Tennis stroke across the body.$$, 'casual'),
('Forehand', 'Sports 🏆', $$Tennis stroke with the palm forward.$$, 'casual'),
('Volleyball', 'Sports 🏆', $$Bump, set, spike over a net.$$, 'casual'),
('Racquetball', 'Sports 🏆', $$Walled-court racket game.$$, 'casual'),
('Badminton', 'Sports 🏆', $$Net game with a shuttlecock.$$, 'casual'),
('Lacrosse', 'Sports 🏆', $$Netted-stick field game.$$, 'casual'),
('Water Polo', 'Sports 🏆', $$Handball in a pool.$$, 'casual'),
('Gymnastics', 'Sports 🏆', $$Beam, bars, and floor routines.$$, 'casual'),
('Wrestling', 'Sports 🏆', $$Grappling for the pin.$$, 'casual'),
('Kickboxing', 'Sports 🏆', $$Punches and kicks combined.$$, 'casual'),
('Archery', 'Sports 🏆', $$Bow and arrow at a target.$$, 'casual'),
('Fencing', 'Sports 🏆', $$Sword duel for points.$$, 'casual'),
('Cycling', 'Sports 🏆', $$Racing on two wheels.$$, 'casual'),
('Snowboarding', 'Sports 🏆', $$Sideways down the slope.$$, 'casual'),
('Bobsled', 'Sports 🏆', $$Team sled down an icy track.$$, 'casual'),
('Curling', 'Sports 🏆', $$Sweeping stones on ice.$$, 'casual'),
('Biathlon', 'Sports 🏆', $$Skiing plus rifle shooting.$$, 'casual'),
('Decathlon', 'Sports 🏆', $$Ten track-and-field events.$$, 'casual'),
('Marathon', 'Sports 🏆', $$26.2-mile race.$$, 'casual'),
('Triathlon', 'Sports 🏆', $$Swim, bike, and run.$$, 'casual'),
('Javelin', 'Sports 🏆', $$Spear-throwing event.$$, 'casual'),
('Discus', 'Sports 🏆', $$Hurling a heavy disc.$$, 'casual'),
('Shot Put', 'Sports 🏆', $$Heaving a heavy metal ball.$$, 'casual'),
('Skiing', 'Sports 🏆', $$Downhill on two long boards.$$, 'casual'),
-- ── Tech & Internet 💻 (devices and hardware) ──────────────────────────────
('Airpods', 'Tech & Internet 💻', $$Apples wireless earbuds.$$, 'casual'),
('Smartwatch', 'Tech & Internet 💻', $$Wrist computer that counts steps.$$, 'casual'),
('Touchscreen', 'Tech & Internet 💻', $$Tap-and-swipe display.$$, 'casual'),
('Fingerprint', 'Tech & Internet 💻', $$Biometric unlock by touch.$$, 'casual'),
('Face Unlock', 'Tech & Internet 💻', $$Open your phone by looking at it.$$, 'casual'),
('Wireless Charging', 'Tech & Internet 💻', $$Power up just by setting it down.$$, 'casual'),
('Power Bank', 'Tech & Internet 💻', $$Portable battery for a top-up.$$, 'casual'),
('Charging Cable', 'Tech & Internet 💻', $$Cord that juices your device.$$, 'casual'),
('USB Port', 'Tech & Internet 💻', $$Where you plug the cable in.$$, 'casual'),
('Headphones', 'Tech & Internet 💻', $$Over-the-ear audio.$$, 'casual'),
('Earbuds', 'Tech & Internet 💻', $$Tiny in-ear speakers.$$, 'casual'),
('Speaker', 'Tech & Internet 💻', $$Plays your audio out loud.$$, 'casual'),
('Webcam', 'Tech & Internet 💻', $$Camera for video calls.$$, 'casual'),
('Microphone', 'Tech & Internet 💻', $$Picks up your voice.$$, 'casual'),
('Selfie Stick', 'Tech & Internet 💻', $$Extends your reach for a photo.$$, 'casual'),
('Tripod', 'Tech & Internet 💻', $$Three-legged camera stand.$$, 'casual'),
('Smart Home', 'Tech & Internet 💻', $$Voice-controlled lights and locks.$$, 'casual'),
('Thermostat', 'Tech & Internet 💻', $$Smart dial for the heat.$$, 'casual'),
('Doorbell Camera', 'Tech & Internet 💻', $$See who is at the door.$$, 'casual'),
('Game Console', 'Tech & Internet 💻', $$PlayStation or Xbox box.$$, 'casual'),
('Graphics Card', 'Tech & Internet 💻', $$Powers the visuals in a PC.$$, 'casual'),
('Hard Drive', 'Tech & Internet 💻', $$Where your files are stored.$$, 'casual'),
('Memory Card', 'Tech & Internet 💻', $$Little chip for extra storage.$$, 'casual'),
('Streaming Stick', 'Tech & Internet 💻', $$Plugs into your TV for apps.$$, 'casual'),
-- ── Video Games 🎮 ─────────────────────────────────────────────────────────
('Splatoon', 'Video Games 🎮', $$Ink-shooting squid kids.$$, 'casual'),
('Titanfall', 'Video Games 🎮', $$Pilots and giant mechs.$$, 'casual'),
('Battlefield', 'Video Games 🎮', $$Large-scale military shooter.$$, 'casual'),
('Rainbow Six', 'Video Games 🎮', $$Tactical counter-terrorism.$$, 'casual'),
('Watch Dogs', 'Video Games 🎮', $$Hack the city.$$, 'casual'),
('Far Cry', 'Video Games 🎮', $$Open-world shooter with wild villains.$$, 'casual'),
('Just Cause', 'Video Games 🎮', $$Grappling-hook chaos sandbox.$$, 'casual'),
('Sleeping Dogs', 'Video Games 🎮', $$Undercover cop in Hong Kong.$$, 'casual'),
('Saints Row', 'Video Games 🎮', $$Over-the-top gang sandbox.$$, 'casual'),
('Dead Space', 'Video Games 🎮', $$Sci-fi horror on a mining ship.$$, 'casual'),
('Mass Effect', 'Video Games 🎮', $$Commander Shepard saves the galaxy.$$, 'casual'),
('Dragon Age', 'Video Games 🎮', $$Dark fantasy RPG series.$$, 'casual'),
('Fable', 'Video Games 🎮', $$British good-or-evil fantasy RPG.$$, 'casual'),
('Sea of Thieves', 'Video Games 🎮', $$Multiplayer pirate adventures.$$, 'casual'),
('Forza Horizon', 'Video Games 🎮', $$Open-world racing festival.$$, 'casual'),
('Gran Turismo', 'Video Games 🎮', $$The real driving simulator.$$, 'casual'),
('Burnout Paradise', 'Video Games 🎮', $$Crash-happy arcade racing.$$, 'casual'),
('Need for Speed', 'Video Games 🎮', $$Street-racing series.$$, 'casual'),
('Rocket League', 'Video Games 🎮', $$Soccer played with cars.$$, 'casual'),
('Fall Guys', 'Video Games 🎮', $$Jellybean obstacle-course battle.$$, 'casual'),
('Among Us', 'Video Games 🎮', $$Find the impostor on the ship.$$, 'casual'),
('Phasmophobia', 'Video Games 🎮', $$Co-op ghost hunting.$$, 'casual'),
('Valheim', 'Video Games 🎮', $$Viking survival sandbox.$$, 'casual'),
('State of Decay', 'Video Games 🎮', $$Zombie-survival base building.$$, 'casual')
) AS v(phrase, category, clue, pool)
WHERE NOT EXISTS (
  SELECT 1 FROM public.daily_puzzles d WHERE upper(d.phrase) = upper(v.phrase)
);

COMMIT;
