-- ╔══════════════════════════════════════════════════════════════════════════╗
-- ║  Phase 6b: Challenge Builder — lobby (migration: challenge_builder_6b)      ║
-- ╚══════════════════════════════════════════════════════════════════════════╝
-- Configurable N-player matches over a shared puzzle PACK. Replaces the 1v1
-- challenge system (kept live until the 6d cutover). Play engine + settle = 6c.
--
-- challenge_matches(id, host_id, group_id, mode 'standard'|'blitz', categories[],
--   pack_size, wager (0=friendly), payout 'winner'|'top3'|'even', status, settles_at).
-- challenge_pack(match_id, position, puzzle_id)            -- the shared seeded pack.
-- challenge_participants(match_id, user_id, paid, position, bankroll, guesses,
--   revealed/incorrect, p_vowels/p_reveals/p_wrong_guesses, total_score,
--   state invited|active|done).  Self-read RLS.
--
-- create_match(opponent|group_id, categories[], pack_size, mode, wager, payout,
--   window_seconds)  -- escrows the host; builds the pack from the categories;
--   invites the opponent OR every group member (notified). 1–10 puzzles, min wager
--   $100, window 1h–1week.
-- accept_match(id)   -- escrow my wager, go active.
-- get_match(id)      -- lobby/results, SPOILER-LOCKED: others' scores hidden until
--   I'm 'done' or the match is 'settled'.
-- get_my_matches()   -- inbox.
--
-- Verified 6b (SQL sim): Chef creates a 2-puzzle $200 winner match vs Warpocket →
-- escrow $1000→$800, pack=2, 2 players; War sees the invite, accepts (escrow
-- $800), spoiler-lock hides Chef's score (null) while War is mid-match. Cleaned up.
--
-- ── Phase 6c: play engine + settle (migration challenge_builder_6c_play) ───────
-- Each participant plays the pack one puzzle at a time on a fake $1,000 budget
-- (mirrors the Daily efficiency engine). Per-puzzle score = round(leftover × eff),
-- summed into total_score; advance through the pack, then state='done'.
--   match_start / match_buy_letter / match_reveal / match_submit_guess(id,…)
--   _match_board (current puzzle + {match:{position,pack_size,total_score,last_score}})
--   _match_resolve_and_advance (score + advance or finish → _match_maybe_settle)
-- _match_settle(id): rank PAID participants by total_score; pay the pot
--   (wager × paid) by payout rule — winner (tie → split), top3 (50/30/20 when ≥3,
--   else winner), even (split among finishers; no-shows forfeit); <2 paid → refund.
--   Notifies everyone with their standing. get_my_matches lazily settles expired
--   matches (past settles_at).
--
-- Verified 6c (SQL sim): solve puzzle 1 → score 1,900 (= $1,000 × 1.9 eff), advance
-- to #2; settle Chef 1500 vs War 900 → Chef wins $400 pot (1000→1200, War 1000→800),
-- status settled, notified. Cleaned up. Builder UI + results card = 6d.

-- ── Phase 7: Blitz (migration challenge_builder_blitz) ────────────────────────
-- mode='blitz' on a match: one clock for the whole pack (30s × pack_size), combo
-- scoring instead of efficiency. challenge_participants += started_at, combo_x100.
-- match_start stamps the clock; _match_tick locks the score (done) once expired
-- (guards every play action); match_check(id) is the client's countdown-expiry call.
-- _match_resolve_and_advance: blitz solve = round(300 × combo); combo +0.25 (cap
-- ×3.0), resets on a failed puzzle. _match_board carries started_at/clock_seconds/
-- combo for the countdown. Verified (SQL sim): start clock 60s, solve → 300 +
-- combo ×1.25, clock expiry → done @ 300.
