-- ============================================================================
-- Puzzle pool expansion — batch 3: +25 per category (×12 = 300), deduped.
-- Split ~17 daily / 8 casual per category to hold the existing ~66/34 ratio.
-- id/seq auto-generate; subcategory defaults to ''. Clues use $$..$$ quoting so
-- apostrophes are safe. The WHERE NOT EXISTS guard skips any phrase already present
-- (case-insensitive), so re-running is safe and no dupes slip in.
-- Data-only: does NOT touch the app binary → zero impact on App Store review, and
-- survives the launch reset (daily_puzzles is preserved). Applied to prod.
-- ============================================================================
BEGIN;

INSERT INTO public.daily_puzzles (phrase, category, clue, pool)
SELECT v.phrase, v.category, v.clue, v.pool
FROM (VALUES
-- ── Books & Characters 📚 ──────────────────────────────────────────────────
('The Book Thief', 'Books & Characters 📚', $$Death narrates, Nazi Germany.$$, 'daily'),
('Life of Pi', 'Books & Characters 📚', $$Boy, tiger, one lifeboat.$$, 'daily'),
('The Kite Runner', 'Books & Characters 📚', $$Afghan boys, for you a thousand times.$$, 'daily'),
('A Game of Thrones', 'Books & Characters 📚', $$Winter is coming.$$, 'daily'),
('The Handmaids Tale', 'Books & Characters 📚', $$Offred, Gilead, red robes.$$, 'daily'),
('The Road', 'Books & Characters 📚', $$Father and son, ashen apocalypse.$$, 'daily'),
('The Alchemist', 'Books & Characters 📚', $$Shepherd chases his Personal Legend.$$, 'daily'),
('Where the Crawdads Sing', 'Books & Characters 📚', $$Marsh girl on trial.$$, 'daily'),
('Enders Game', 'Books & Characters 📚', $$Child soldier, alien war.$$, 'daily'),
('The Stand', 'Books & Characters 📚', $$Stephen King plague epic.$$, 'daily'),
('Carrie', 'Books & Characters 📚', $$Prom, telekinesis, bucket of blood.$$, 'daily'),
('The Martian', 'Books & Characters 📚', $$Stranded astronaut grows potatoes.$$, 'daily'),
('Ready Player One', 'Books & Characters 📚', $$Virtual Easter-egg hunt in the OASIS.$$, 'daily'),
('Gone Girl', 'Books & Characters 📚', $$Amazing Amy vanishes.$$, 'daily'),
('The Girl on the Train', 'Books & Characters 📚', $$Unreliable commuter witness.$$, 'daily'),
('Little Fires Everywhere', 'Books & Characters 📚', $$Secrets in Shaker Heights.$$, 'daily'),
('The Secret History', 'Books & Characters 📚', $$Elite classics students, a murder.$$, 'daily'),
('The Nightingale', 'Books & Characters 📚', $$Sisters in Nazi-occupied France.$$, 'casual'),
('Circe', 'Books & Characters 📚', $$Witch of Aiaia.$$, 'casual'),
('The Song of Achilles', 'Books & Characters 📚', $$Patroclus and the Trojan War.$$, 'casual'),
('Normal People', 'Books & Characters 📚', $$Connell and Marianne.$$, 'casual'),
('A Little Life', 'Books & Characters 📚', $$Four friends, and Jude.$$, 'casual'),
('The Goldfinch', 'Books & Characters 📚', $$A bombing and a stolen painting.$$, 'casual'),
('Educated', 'Books & Characters 📚', $$Tara Westover leaves the mountain.$$, 'casual'),
('Beloved', 'Books & Characters 📚', $$Toni Morrison, haunted by Sethe.$$, 'casual'),
-- ── Brands & Logos 🏷️ ──────────────────────────────────────────────────────
('Costco', 'Brands & Logos 🏷️', $$Bulk buys, membership warehouse.$$, 'daily'),
('Target', 'Brands & Logos 🏷️', $$Red bullseye, expect more.$$, 'daily'),
('Best Buy', 'Brands & Logos 🏷️', $$Blue-shirt electronics store.$$, 'daily'),
('Home Depot', 'Brands & Logos 🏷️', $$Orange DIY warehouse.$$, 'daily'),
('Ford', 'Brands & Logos 🏷️', $$Blue oval, Model T maker.$$, 'daily'),
('Chevrolet', 'Brands & Logos 🏷️', $$Bowtie badge, American cars.$$, 'daily'),
('Mazda', 'Brands & Logos 🏷️', $$Zoom-Zoom, Japanese cars.$$, 'daily'),
('Subaru', 'Brands & Logos 🏷️', $$Boxer engines, six stars.$$, 'daily'),
('Panasonic', 'Brands & Logos 🏷️', $$Japanese electronics giant.$$, 'daily'),
('LG', 'Brands & Logos 🏷️', $$Lifes Good electronics.$$, 'daily'),
('Whirlpool', 'Brands & Logos 🏷️', $$Home appliance maker.$$, 'daily'),
('Reddit', 'Brands & Logos 🏷️', $$Front page of the internet.$$, 'daily'),
('Twitch', 'Brands & Logos 🏷️', $$Purple live game streaming.$$, 'daily'),
('Zoom', 'Brands & Logos 🏷️', $$Pandemic video meetings.$$, 'daily'),
('Slack', 'Brands & Logos 🏷️', $$Workplace chat channels.$$, 'daily'),
('Airbus', 'Brands & Logos 🏷️', $$European planemaker, the A320.$$, 'daily'),
('Boeing', 'Brands & Logos 🏷️', $$Maker of the 747.$$, 'daily'),
('Sephora', 'Brands & Logos 🏷️', $$Makeup superstore, black stripes.$$, 'casual'),
('Ulta', 'Brands & Logos 🏷️', $$Beauty store with a salon.$$, 'casual'),
('Chipotle', 'Brands & Logos 🏷️', $$Build-your-own burrito.$$, 'casual'),
('Popeyes', 'Brands & Logos 🏷️', $$Louisiana fried chicken.$$, 'casual'),
('Gatorade', 'Brands & Logos 🏷️', $$Sideline sports drink.$$, 'casual'),
('Monster Energy', 'Brands & Logos 🏷️', $$Green claw energy drink.$$, 'casual'),
('Crocs', 'Brands & Logos 🏷️', $$Foam clogs full of holes.$$, 'casual'),
('Vans', 'Brands & Logos 🏷️', $$Off the Wall skate shoes.$$, 'casual'),
-- ── Famous People 🌟 ───────────────────────────────────────────────────────
('George Washington', 'Famous People 🌟', $$First president, cherry tree myth.$$, 'daily'),
('Benjamin Franklin', 'Famous People 🌟', $$Kite, lightning, hundred-dollar bill.$$, 'daily'),
('Thomas Jefferson', 'Famous People 🌟', $$Declaration author, Monticello.$$, 'daily'),
('Theodore Roosevelt', 'Famous People 🌟', $$Rough Rider, the teddy bear.$$, 'daily'),
('John F Kennedy', 'Famous People 🌟', $$Camelot president, Dallas 1963.$$, 'daily'),
('Ronald Reagan', 'Famous People 🌟', $$Actor turned president.$$, 'daily'),
('Anne Frank', 'Famous People 🌟', $$Diary from a hidden annex.$$, 'daily'),
('Malala Yousafzai', 'Famous People 🌟', $$Youngest Nobel laureate, education.$$, 'daily'),
('Helen Keller', 'Famous People 🌟', $$Deaf and blind, taught by Anne Sullivan.$$, 'daily'),
('Harriet Tubman', 'Famous People 🌟', $$Underground Railroad conductor.$$, 'daily'),
('Frederick Douglass', 'Famous People 🌟', $$Escaped slave, abolitionist orator.$$, 'daily'),
('Alexander Hamilton', 'Famous People 🌟', $$Founding father, a Broadway smash.$$, 'daily'),
('Salvador Dali', 'Famous People 🌟', $$Melting clocks, curled mustache.$$, 'daily'),
('Claude Monet', 'Famous People 🌟', $$Water lilies, impressionism.$$, 'daily'),
('Marco Polo', 'Famous People 🌟', $$Venetian explorer of the Silk Road.$$, 'daily'),
('Jackie Robinson', 'Famous People 🌟', $$Broke baseballs color barrier, 42.$$, 'daily'),
('Babe Ruth', 'Famous People 🌟', $$Yankees slugger, the Bambino.$$, 'daily'),
('Wayne Gretzky', 'Famous People 🌟', $$Hockeys Great One.$$, 'casual'),
('Kobe Bryant', 'Famous People 🌟', $$Lakers legend, the Mamba.$$, 'casual'),
('Tom Brady', 'Famous People 🌟', $$Seven Super Bowl rings.$$, 'casual'),
('Simone Biles', 'Famous People 🌟', $$Dominant gymnast, the GOAT.$$, 'casual'),
('Michael Phelps', 'Famous People 🌟', $$Most decorated Olympian, swimmer.$$, 'casual'),
('Roger Federer', 'Famous People 🌟', $$Swiss tennis maestro.$$, 'casual'),
('Che Guevara', 'Famous People 🌟', $$Revolutionary on a million t-shirts.$$, 'casual'),
('Johann Sebastian Bach', 'Famous People 🌟', $$Baroque composer of fugues.$$, 'casual'),
-- ── Food & Drink 🍔 ────────────────────────────────────────────────────────
('Beef Wellington', 'Food & Drink 🍔', $$Pastry-wrapped tenderloin.$$, 'daily'),
('Chicken Alfredo', 'Food & Drink 🍔', $$Creamy Parmesan pasta.$$, 'daily'),
('Shepherds Pie', 'Food & Drink 🍔', $$Mince topped with mashed potato.$$, 'daily'),
('Pot Roast', 'Food & Drink 🍔', $$Slow-cooked Sunday beef.$$, 'daily'),
('Grilled Cheese', 'Food & Drink 🍔', $$Griddled melty sandwich.$$, 'daily'),
('French Toast', 'Food & Drink 🍔', $$Egg-dipped fried bread.$$, 'daily'),
('Eggs Benedict', 'Food & Drink 🍔', $$Poached eggs and hollandaise.$$, 'daily'),
('Chicken Noodle Soup', 'Food & Drink 🍔', $$Sick-day comfort bowl.$$, 'daily'),
('Tomato Soup', 'Food & Drink 🍔', $$Pairs with grilled cheese.$$, 'daily'),
('Garlic Bread', 'Food & Drink 🍔', $$Buttery toasted side.$$, 'daily'),
('Beef Stew', 'Food & Drink 🍔', $$Hearty simmered chunks.$$, 'daily'),
('Pulled Pork', 'Food & Drink 🍔', $$Smoky shredded barbecue.$$, 'daily'),
('Fish Tacos', 'Food & Drink 🍔', $$Baja-style with slaw.$$, 'daily'),
('Cinnamon Roll', 'Food & Drink 🍔', $$Frosted spiral pastry.$$, 'daily'),
('Banana Split', 'Food & Drink 🍔', $$Three-scoop sundae boat.$$, 'daily'),
('Peanut Butter', 'Food & Drink 🍔', $$Jellys sandwich partner.$$, 'daily'),
('Beef Jerky', 'Food & Drink 🍔', $$Chewy dried snack.$$, 'daily'),
('Mango Lassi', 'Food & Drink 🍔', $$Sweet Indian yogurt drink.$$, 'casual'),
('Chai Latte', 'Food & Drink 🍔', $$Spiced tea with steamed milk.$$, 'casual'),
('Cold Brew', 'Food & Drink 🍔', $$Slow-steeped iced coffee.$$, 'casual'),
('Pina Colada', 'Food & Drink 🍔', $$Coconut-pineapple rum drink.$$, 'casual'),
('Bloody Mary', 'Food & Drink 🍔', $$Brunch tomato cocktail.$$, 'casual'),
('Old Fashioned', 'Food & Drink 🍔', $$Whiskey, bitters, sugar.$$, 'casual'),
('Mojito', 'Food & Drink 🍔', $$Rum, lime, muddled mint.$$, 'casual'),
('Green Tea', 'Food & Drink 🍔', $$Antioxidant Japanese brew.$$, 'casual'),
-- ── Movies & TV 🎬 ─────────────────────────────────────────────────────────
('The Sixth Sense', 'Movies & TV 🎬', $$I see dead people.$$, 'daily'),
('No Country for Old Men', 'Movies & TV 🎬', $$Coin-flipping killer, Chigurh.$$, 'daily'),
('There Will Be Blood', 'Movies & TV 🎬', $$I drink your milkshake.$$, 'daily'),
('The Big Lebowski', 'Movies & TV 🎬', $$The Dude abides.$$, 'daily'),
('Reservoir Dogs', 'Movies & TV 🎬', $$Color-coded heist crew.$$, 'daily'),
('Kill Bill', 'Movies & TV 🎬', $$The Bride in a yellow suit.$$, 'daily'),
('Inglourious Basterds', 'Movies & TV 🎬', $$Nazi-hunting WWII revenge.$$, 'daily'),
('The Grand Budapest Hotel', 'Movies & TV 🎬', $$Wes Anderson concierge caper.$$, 'daily'),
('Get Out', 'Movies & TV 🎬', $$The sunken place.$$, 'daily'),
('A Quiet Place', 'Movies & TV 🎬', $$Monsters that hunt by sound.$$, 'daily'),
('John Wick', 'Movies & TV 🎬', $$They killed his dog.$$, 'daily'),
('Deadpool', 'Movies & TV 🎬', $$The merc with a mouth.$$, 'daily'),
('Guardians of the Galaxy', 'Movies & TV 🎬', $$Star-Lords misfit team.$$, 'daily'),
('The Batman', 'Movies & TV 🎬', $$Riddler, rainy Gotham.$$, 'daily'),
('Wonder Woman', 'Movies & TV 🎬', $$Amazon of Themyscira.$$, 'daily'),
('Zootopia', 'Movies & TV 🎬', $$Bunny cop and a sly fox.$$, 'daily'),
('Moana', 'Movies & TV 🎬', $$Islander, the ocean, and Maui.$$, 'daily'),
('Modern Family', 'Movies & TV 🎬', $$Mockumentary Dunphy clan.$$, 'casual'),
('Greys Anatomy', 'Movies & TV 🎬', $$Seattle hospital drama.$$, 'casual'),
('The Big Bang Theory', 'Movies & TV 🎬', $$Physicists and Penny.$$, 'casual'),
('How I Met Your Mother', 'Movies & TV 🎬', $$Teds tale and a yellow umbrella.$$, 'casual'),
('Brooklyn Nine Nine', 'Movies & TV 🎬', $$Precinct comedy, cool cool cool.$$, 'casual'),
('Rick and Morty', 'Movies & TV 🎬', $$Mad scientist and his grandson.$$, 'casual'),
('Bojack Horseman', 'Movies & TV 🎬', $$Depressed horse actor.$$, 'casual'),
('Fleabag', 'Movies & TV 🎬', $$Breaking the fourth wall.$$, 'casual'),
-- ── Music 🎵 ───────────────────────────────────────────────────────────────
('Highway to Hell', 'Music 🎵', $$AC/DC anthem.$$, 'daily'),
('Back in Black', 'Music 🎵', $$AC/DC after Bon Scott.$$, 'daily'),
('Enter Sandman', 'Music 🎵', $$Metallica lullaby of dread.$$, 'daily'),
('Master of Puppets', 'Music 🎵', $$Metallica thrash classic.$$, 'daily'),
('Nothing Else Matters', 'Music 🎵', $$Metallica ballad.$$, 'daily'),
('Under Pressure', 'Music 🎵', $$Queen and Bowie duet.$$, 'daily'),
('Killer Queen', 'Music 🎵', $$Guaranteed to blow your mind.$$, 'daily'),
('Life on Mars', 'Music 🎵', $$Bowies soaring ballad.$$, 'daily'),
('Space Oddity', 'Music 🎵', $$Bowies Major Tom.$$, 'daily'),
('Let It Go', 'Music 🎵', $$Frozens icy anthem.$$, 'daily'),
('A Thousand Miles', 'Music 🎵', $$Vanessa Carlton piano hit.$$, 'daily'),
('Call Me Maybe', 'Music 🎵', $$Carly Rae Jepsen earworm.$$, 'daily'),
('Uptown Girl', 'Music 🎵', $$Billy Joel doo-wop.$$, 'daily'),
('Piano Man', 'Music 🎵', $$Billy Joel bar singalong.$$, 'daily'),
('Rocket Man', 'Music 🎵', $$Elton John, burning out his fuse.$$, 'daily'),
('Tiny Dancer', 'Music 🎵', $$Elton John, hold me closer.$$, 'daily'),
('Your Song', 'Music 🎵', $$Early Elton John ballad.$$, 'daily'),
('Watermelon Sugar', 'Music 🎵', $$Harry Styles summer hit.$$, 'casual'),
('Sunflower', 'Music 🎵', $$Post Malone, Spider-Verse.$$, 'casual'),
('Circles', 'Music 🎵', $$Post Malone earworm.$$, 'casual'),
('Montero', 'Music 🎵', $$Lil Nas X, call me by your name.$$, 'casual'),
('Industry Baby', 'Music 🎵', $$Lil Nas X and Jack Harlow.$$, 'casual'),
('Flowers', 'Music 🎵', $$Miley Cyrus self-love anthem.$$, 'casual'),
('Anti Hero', 'Music 🎵', $$Taylor Swift, its me, hi.$$, 'casual'),
('Peaches', 'Music 🎵', $$Justin Bieber, down in Georgia.$$, 'casual'),
-- ── Phrases & Sayings 🗣️ ───────────────────────────────────────────────────
('Cat Got Your Tongue', 'Phrases & Sayings 🗣️', $$Why so silent?$$, 'daily'),
('Cut the Mustard', 'Phrases & Sayings 🗣️', $$Meet the standard.$$, 'daily'),
('Dead as a Doornail', 'Phrases & Sayings 🗣️', $$Utterly lifeless.$$, 'daily'),
('Down the Rabbit Hole', 'Phrases & Sayings 🗣️', $$Lost in a deep tangent.$$, 'daily'),
('Elephant in the Room', 'Phrases & Sayings 🗣️', $$The obvious unspoken problem.$$, 'daily'),
('Feather in Your Cap', 'Phrases & Sayings 🗣️', $$A proud achievement.$$, 'daily'),
('Fit as a Fiddle', 'Phrases & Sayings 🗣️', $$In great health.$$, 'daily'),
('Go Cold Turkey', 'Phrases & Sayings 🗣️', $$Quit all at once.$$, 'daily'),
('Green with Envy', 'Phrases & Sayings 🗣️', $$Consumed by jealousy.$$, 'daily'),
('Head in the Clouds', 'Phrases & Sayings 🗣️', $$Daydreaming, unfocused.$$, 'daily'),
('In the Nick of Time', 'Phrases & Sayings 🗣️', $$Just barely in time.$$, 'daily'),
('Larger Than Life', 'Phrases & Sayings 🗣️', $$Bigger than reality.$$, 'daily'),
('Method to the Madness', 'Phrases & Sayings 🗣️', $$Hidden logic in the chaos.$$, 'daily'),
('Nip It in the Bud', 'Phrases & Sayings 🗣️', $$Stop it before it grows.$$, 'daily'),
('Off the Hook', 'Phrases & Sayings 🗣️', $$Free from blame.$$, 'daily'),
('Chase Your Tail', 'Phrases & Sayings 🗣️', $$Busy but getting nowhere.$$, 'daily'),
('Jump for Joy', 'Phrases & Sayings 🗣️', $$Overwhelmed with happiness.$$, 'daily'),
('Paint the Town Red', 'Phrases & Sayings 🗣️', $$Go out and celebrate.$$, 'casual'),
('Pull the Plug', 'Phrases & Sayings 🗣️', $$End it abruptly.$$, 'casual'),
('Save Your Breath', 'Phrases & Sayings 🗣️', $$Dont bother arguing.$$, 'casual'),
('Sit on the Fence', 'Phrases & Sayings 🗣️', $$Refuse to pick a side.$$, 'casual'),
('Steal Your Thunder', 'Phrases & Sayings 🗣️', $$Take credit that was yours.$$, 'casual'),
('The Best Thing Since Sliced Bread', 'Phrases & Sayings 🗣️', $$A great new invention.$$, 'casual'),
('Walking on Eggshells', 'Phrases & Sayings 🗣️', $$Being extremely careful.$$, 'casual'),
('Cost You an Arm', 'Phrases & Sayings 🗣️', $$Painfully expensive.$$, 'casual'),
-- ── Places & Travel ✈️ ─────────────────────────────────────────────────────
('Chicago', 'Places & Travel ✈️', $$Windy City, deep-dish pizza.$$, 'daily'),
('Miami', 'Places & Travel ✈️', $$Art Deco and South Beach.$$, 'daily'),
('Boston', 'Places & Travel ✈️', $$Tea Party and the Freedom Trail.$$, 'daily'),
('Seattle', 'Places & Travel ✈️', $$Space Needle, coffee, rain.$$, 'daily'),
('San Francisco', 'Places & Travel ✈️', $$Golden Gate and cable cars.$$, 'daily'),
('New Orleans', 'Places & Travel ✈️', $$Jazz, Mardi Gras, beignets.$$, 'daily'),
('Nashville', 'Places & Travel ✈️', $$Country music, the Grand Ole Opry.$$, 'daily'),
('Toronto', 'Places & Travel ✈️', $$CN Tower, Canadas biggest city.$$, 'daily'),
('Vancouver', 'Places & Travel ✈️', $$Pacific coast, mountains and sea.$$, 'daily'),
('Montreal', 'Places & Travel ✈️', $$French Canada, old-town cobblestones.$$, 'daily'),
('Beijing', 'Places & Travel ✈️', $$Forbidden City, Chinas capital.$$, 'daily'),
('Shanghai', 'Places & Travel ✈️', $$Skyline along the Bund.$$, 'daily'),
('Delhi', 'Places & Travel ✈️', $$Indias sprawling capital.$$, 'daily'),
('Johannesburg', 'Places & Travel ✈️', $$South Africas City of Gold.$$, 'daily'),
('The Berlin Wall', 'Places & Travel ✈️', $$Cold War divider, fell in 1989.$$, 'daily'),
('The Brooklyn Bridge', 'Places & Travel ✈️', $$East River span from 1883.$$, 'daily'),
('The Panama Canal', 'Places & Travel ✈️', $$Shortcut between two oceans.$$, 'daily'),
('Osaka', 'Places & Travel ✈️', $$Japans street-food capital.$$, 'casual'),
('Lagos', 'Places & Travel ✈️', $$Nigerias megacity.$$, 'casual'),
('The Grand Bazaar', 'Places & Travel ✈️', $$Istanbuls covered market.$$, 'casual'),
('The Blue Lagoon', 'Places & Travel ✈️', $$Icelands geothermal spa.$$, 'casual'),
('The Hoover Dam', 'Places & Travel ✈️', $$Colorado River concrete giant.$$, 'casual'),
('The Space Needle', 'Places & Travel ✈️', $$Seattles 1962 spire.$$, 'casual'),
('The Sydney Harbour', 'Places & Travel ✈️', $$Bridge nicknamed the Coathanger.$$, 'casual'),
('Mount Sinai', 'Places & Travel ✈️', $$Where Moses got the tablets.$$, 'casual'),
-- ── Science & Nature 🔬 ────────────────────────────────────────────────────
('Absolute Zero', 'Science & Nature 🔬', $$The coldest possible temperature.$$, 'daily'),
('Acid Rain', 'Science & Nature 🔬', $$Pollution-tainted precipitation.$$, 'daily'),
('Amino Acids', 'Science & Nature 🔬', $$Protein building blocks.$$, 'daily'),
('Antimatter', 'Science & Nature 🔬', $$Matters mirror opposite.$$, 'daily'),
('Bacteria', 'Science & Nature 🔬', $$Single-celled microbes.$$, 'daily'),
('Biosphere', 'Science & Nature 🔬', $$All of Earths living zones.$$, 'daily'),
('Cell Membrane', 'Science & Nature 🔬', $$The cells outer boundary.$$, 'daily'),
('Chromosomes', 'Science & Nature 🔬', $$DNA-packaging structures.$$, 'daily'),
('Dark Matter', 'Science & Nature 🔬', $$Invisible mass holding galaxies together.$$, 'daily'),
('Enzymes', 'Science & Nature 🔬', $$Reaction-speeding proteins.$$, 'daily'),
('Fault Line', 'Science & Nature 🔬', $$Crack where earthquakes strike.$$, 'daily'),
('Food Web', 'Science & Nature 🔬', $$Interlocking who-eats-whom.$$, 'daily'),
('Glacier', 'Science & Nature 🔬', $$Slow-moving river of ice.$$, 'daily'),
('Gene Therapy', 'Science & Nature 🔬', $$Fixing disease at the DNA level.$$, 'daily'),
('Habitat', 'Science & Nature 🔬', $$An organisms natural home.$$, 'daily'),
('Herbivore', 'Science & Nature 🔬', $$Plant-only eater.$$, 'daily'),
('Cloud Formation', 'Science & Nature 🔬', $$Water vapor gathering aloft.$$, 'daily'),
('Igneous Rock', 'Science & Nature 🔬', $$Cooled from lava or magma.$$, 'casual'),
('Immune System', 'Science & Nature 🔬', $$The bodys defense force.$$, 'casual'),
('Lunar Eclipse', 'Science & Nature 🔬', $$Earths shadow on the moon.$$, 'casual'),
('Neurons', 'Science & Nature 🔬', $$Signal-firing nerve cells.$$, 'casual'),
('Nitrogen Cycle', 'Science & Nature 🔬', $$How the airs main gas moves through life.$$, 'casual'),
('Solar Flare', 'Science & Nature 🔬', $$Sudden burst from the sun.$$, 'casual'),
('Wind Turbine', 'Science & Nature 🔬', $$Blades that harvest the breeze.$$, 'casual'),
('Carbon Cycle', 'Science & Nature 🔬', $$Elements loop through air, life, and rock.$$, 'casual'),
-- ── Sports 🏆 ──────────────────────────────────────────────────────────────
('Air Ball', 'Sports 🏆', $$Shot that hits nothing.$$, 'daily'),
('Backhand', 'Sports 🏆', $$Racket swing across the body.$$, 'daily'),
('Ball Boy', 'Sports 🏆', $$Fetches strays courtside.$$, 'daily'),
('Base Runner', 'Sports 🏆', $$Player circling the diamond.$$, 'daily'),
('Blindside', 'Sports 🏆', $$Hit from where you cant see.$$, 'daily'),
('Caddie', 'Sports 🏆', $$Carries the golfers bag.$$, 'daily'),
('Center Court', 'Sports 🏆', $$The showcase tennis stage.$$, 'daily'),
('Clean Sheet', 'Sports 🏆', $$A shutout in soccer.$$, 'daily'),
('Deuce', 'Sports 🏆', $$Tied at 40 in tennis.$$, 'daily'),
('Dugout', 'Sports 🏆', $$Where the bench team sits.$$, 'daily'),
('End Zone', 'Sports 🏆', $$Where touchdowns are scored.$$, 'daily'),
('Extra Innings', 'Sports 🏆', $$Baseball past the ninth.$$, 'daily'),
('Fair Catch', 'Sports 🏆', $$Waving off the tackle on a punt.$$, 'daily'),
('False Start', 'Sports 🏆', $$Jumping before the gun.$$, 'daily'),
('Fastball', 'Sports 🏆', $$A pitchers heater.$$, 'daily'),
('Come From Behind', 'Sports 🏆', $$Rally from a deficit.$$, 'daily'),
('End to End', 'Sports 🏆', $$Play racing from one goal to the other.$$, 'daily'),
('Forehand', 'Sports 🏆', $$The natural tennis stroke.$$, 'casual'),
('Free Agent', 'Sports 🏆', $$Player without a team.$$, 'casual'),
('Goal Line', 'Sports 🏆', $$The scoring boundary.$$, 'casual'),
('Home Court', 'Sports 🏆', $$Where the crowd favors you.$$, 'casual'),
('Instant Replay', 'Sports 🏆', $$Review the disputed call.$$, 'casual'),
('Match Point', 'Sports 🏆', $$One point from winning.$$, 'casual'),
('Neutral Zone', 'Sports 🏆', $$No-mans-land between the lines.$$, 'casual'),
('Overtime', 'Sports 🏆', $$Bonus period to break a tie.$$, 'casual'),
-- ── Tech & Internet 💻 ─────────────────────────────────────────────────────
('Autopilot', 'Tech & Internet 💻', $$Self-steering mode.$$, 'daily'),
('Bug Report', 'Tech & Internet 💻', $$Flagging a software glitch.$$, 'daily'),
('Cache', 'Tech & Internet 💻', $$Stored data for quick reuse.$$, 'daily'),
('Chatbot', 'Tech & Internet 💻', $$Automated conversation partner.$$, 'daily'),
('Command Line', 'Tech & Internet 💻', $$Text-based computer control.$$, 'daily'),
('Data Center', 'Tech & Internet 💻', $$Warehouse full of servers.$$, 'daily'),
('Deep Learning', 'Tech & Internet 💻', $$Layered neural-net AI.$$, 'daily'),
('Digital Wallet', 'Tech & Internet 💻', $$Phone-based payment app.$$, 'daily'),
('Face ID', 'Tech & Internet 💻', $$Unlock with your face.$$, 'daily'),
('Gigabyte', 'Tech & Internet 💻', $$A thousand megabytes.$$, 'daily'),
('Group Chat', 'Tech & Internet 💻', $$Multi-person message thread.$$, 'daily'),
('Hard Reset', 'Tech & Internet 💻', $$Wipe it back to factory.$$, 'daily'),
('Home Screen', 'Tech & Internet 💻', $$Where your app icons live.$$, 'daily'),
('Hotspot', 'Tech & Internet 💻', $$Sharing your phones internet.$$, 'daily'),
('Kilobyte', 'Tech & Internet 💻', $$A thousand bytes.$$, 'daily'),
('Byte', 'Tech & Internet 💻', $$Eight bits.$$, 'daily'),
('Inbox Zero', 'Tech & Internet 💻', $$No unread emails left.$$, 'daily'),
('Landing Page', 'Tech & Internet 💻', $$First page a visitor sees.$$, 'casual'),
('Login Screen', 'Tech & Internet 💻', $$Where you enter credentials.$$, 'casual'),
('Loading Bar', 'Tech & Internet 💻', $$Progress indicator.$$, 'casual'),
('Mobile App', 'Tech & Internet 💻', $$Phone software you download.$$, 'casual'),
('Motion Sensor', 'Tech & Internet 💻', $$Detects movement.$$, 'casual'),
('Neural Network', 'Tech & Internet 💻', $$Brain-inspired AI model.$$, 'casual'),
('Photo Filter', 'Tech & Internet 💻', $$Instagram-style image tweak.$$, 'casual'),
('Voice Command', 'Tech & Internet 💻', $$Talking to your device.$$, 'casual'),
-- ── Video Games 🎮 ─────────────────────────────────────────────────────────
('Age of Empires', 'Video Games 🎮', $$Classic historical RTS.$$, 'daily'),
('Batman Arkham', 'Video Games 🎮', $$Caped Crusader beat-em-up series.$$, 'daily'),
('Battlefield', 'Video Games 🎮', $$Large-scale military shooter.$$, 'daily'),
('Beat Saber', 'Video Games 🎮', $$VR lightsaber rhythm game.$$, 'daily'),
('Cities Skylines', 'Video Games 🎮', $$City-building sim.$$, 'daily'),
('Civilization', 'Video Games 🎮', $$One more turn empire builder.$$, 'daily'),
('Contra', 'Video Games 🎮', $$Run-and-gun with the Konami code.$$, 'daily'),
('Dead Cells', 'Video Games 🎮', $$Roguelike metroidvania.$$, 'daily'),
('Deus Ex', 'Video Games 🎮', $$Cyberpunk stealth RPG.$$, 'daily'),
('Dishonored', 'Video Games 🎮', $$Stealth assassin with powers.$$, 'daily'),
('Doom', 'Video Games 🎮', $$Demon-blasting FPS pioneer.$$, 'daily'),
('Duke Nukem', 'Video Games 🎮', $$Wisecracking 90s shooter.$$, 'daily'),
('Fable', 'Video Games 🎮', $$Choices-shape-your-hero RPG.$$, 'daily'),
('Fifa', 'Video Games 🎮', $$Annual soccer sim.$$, 'daily'),
('Far Cry Series', 'Video Games 🎮', $$Open-world first-person mayhem.$$, 'daily'),
('Crusader Kings', 'Video Games 🎮', $$Medieval dynasty grand strategy.$$, 'daily'),
('Ape Escape', 'Video Games 🎮', $$PlayStation monkey-catching.$$, 'daily'),
('Frogger', 'Video Games 🎮', $$Cross the road and the river.$$, 'casual'),
('Galaga', 'Video Games 🎮', $$Arcade space shooter.$$, 'casual'),
('Gran Turismo', 'Video Games 🎮', $$The Real Driving Simulator.$$, 'casual'),
('Katamari', 'Video Games 🎮', $$Roll a sticky ball of stuff.$$, 'casual'),
('Left 4 Dead', 'Video Games 🎮', $$Co-op zombie survival.$$, 'casual'),
('Mega Man', 'Video Games 🎮', $$Blue robot who steals boss weapons.$$, 'casual'),
('Ms Pac Man', 'Video Games 🎮', $$Bow-wearing maze muncher.$$, 'casual'),
('Prince of Persia', 'Video Games 🎮', $$Time-rewinding platformer.$$, 'casual')
) AS v(phrase, category, clue, pool)
WHERE NOT EXISTS (
  SELECT 1 FROM public.daily_puzzles d WHERE upper(d.phrase) = upper(v.phrase)
);

COMMIT;
