-- 30 Daily Puzzles (rotation pool)
-- Run in Supabase SQL Editor after daily_puzzles table exists

INSERT INTO public.daily_puzzles (phrase, category, subcategory) VALUES
  ('THE GODFATHER', 'Movies & TV 🎬', 'Classic Film'),
  ('BREAKING BAD', 'Movies & TV 🎬', 'TV Series'),
  ('PIZZA NIGHT', 'Food & Drink 🍔', ''),
  ('ICE CREAM SUNDAE', 'Food & Drink 🍔', 'Dessert'),
  ('HAPPY HOUR', 'Slang & Sayings 🗣️', ''),
  ('PIECE OF CAKE', 'Slang & Sayings 🗣️', ''),
  ('THE EMPIRE STRIKES BACK', 'Movies & TV 🎬', 'Star Wars'),
  ('ELVIS PRESLEY', 'Pop Culture & Celebrities 🌟', ''),
  ('BUFFALO WINGS', 'Food & Drink 🍔', 'Appetizers'),
  ('BEND IT LIKE BECKHAM', 'Sports & Games 🏆', 'Movie'),
  ('MARTIN LUTHER KING', 'History & Culture 🏛️', 'Civil Rights'),
  ('RAIN CHECK', 'Slang & Sayings 🗣️', ''),
  ('THE CROWN', 'Movies & TV 🎬', 'TV Series'),
  ('STRANGER THINGS', 'Movies & TV 🎬', 'TV'),
  ('FISH AND CHIPS', 'Food & Drink 🍔', 'British'),
  ('BEYONCE', 'Pop Culture & Celebrities 🌟', ''),
  ('DOWN THE HATCH', 'Slang & Sayings 🗣️', ''),
  ('MOUNT RUSHMORE', 'History & Culture 🏛️', 'USA'),
  ('WORLD CUP', 'Sports & Games 🏆', 'Soccer'),
  ('TACO TUESDAY', 'Food & Drink 🍔', ''),
  ('THE OFFICE', 'Movies & TV 🎬', 'TV Comedy'),
  ('ONCE IN A BLUE MOON', 'Slang & Sayings 🗣️', ''),
  ('TAYLOR SWIFT', 'Pop Culture & Celebrities 🌟', ''),
  ('FRENCH FRIES', 'Food & Drink 🍔', ''),
  ('OLYMPIC GAMES', 'Sports & Games 🏆', ''),
  ('CLEOPATRA', 'History & Culture 🏛️', 'Ancient Egypt'),
  ('SPILL THE TEA', 'Slang & Sayings 🗣️', ''),
  ('THE WIZARD OF OZ', 'Movies & TV 🎬', 'Classic'),
  ('AVOCADO TOAST', 'Food & Drink 🍔', 'Brunch'),
  ('NO PAIN NO GAIN', 'Slang & Sayings 🗣️', '');
