-- ============================================================================
-- Puzzle pool expansion — batch 6: ALL CASUAL, 5+ letters only. +25 per category
-- (×12 = 300, 100% casual). Every phrase is ≥5 letters (matches the new floor).
-- Deduped against all prior batches (case-insensitive). Data-only (prod), survives reset.
-- ============================================================================
BEGIN;

INSERT INTO public.daily_puzzles (phrase, category, clue, pool)
SELECT v.phrase, v.category, v.clue, v.pool
FROM (VALUES
-- ── Books & Characters 📚 ──────────────────────────────────────────────────
('Eat Pray Love', 'Books & Characters 📚', $$Woman finds herself across Italy, India, Bali.$$, 'casual'),
('Me Before You', 'Books & Characters 📚', $$Caregiver and a paralyzed man.$$, 'casual'),
('The Lovely Bones', 'Books & Characters 📚', $$Murdered girl narrates from beyond.$$, 'casual'),
('Hatchet', 'Books & Characters 📚', $$Boy survives alone after a plane crash.$$, 'casual'),
('The Perks of Being a Wallflower', 'Books & Characters 📚', $$Shy freshman, mixtapes, Charlie.$$, 'casual'),
('Looking for Alaska', 'Books & Characters 📚', $$John Green boarding-school tragedy.$$, 'casual'),
('Paper Towns', 'Books & Characters 📚', $$Chasing a girl named Margo.$$, 'casual'),
('Eleanor and Park', 'Books & Characters 📚', $$Two misfits fall in love over comics.$$, 'casual'),
('Six of Crows', 'Books & Characters 📚', $$Six outcasts pull an impossible heist.$$, 'casual'),
('Shadow and Bone', 'Books & Characters 📚', $$The Sun Summoner and the Darkling.$$, 'casual'),
('Throne of Glass', 'Books & Characters 📚', $$Teen assassin Celaena.$$, 'casual'),
('A Court of Thorns and Roses', 'Books & Characters 📚', $$Faerie romance, Feyre.$$, 'casual'),
('Red Queen', 'Books & Characters 📚', $$Silver blood rules over red.$$, 'casual'),
('Cinder', 'Books & Characters 📚', $$Cyborg Cinderella retelling.$$, 'casual'),
('Legend', 'Books & Characters 📚', $$Dystopian teens Day and June.$$, 'casual'),
('Miss Peregrines Home for Peculiar Children', 'Books & Characters 📚', $$Time-loop kids with strange powers.$$, 'casual'),
('Big Little Lies', 'Books & Characters 📚', $$Monterey moms and a death.$$, 'casual'),
('The Silent Patient', 'Books & Characters 📚', $$She shot her husband, then stopped speaking.$$, 'casual'),
('Verity', 'Books & Characters 📚', $$Ghostwriter finds a chilling manuscript.$$, 'casual'),
('It Ends with Us', 'Books & Characters 📚', $$Colleen Hoover, love and abuse.$$, 'casual'),
('Turtles All the Way Down', 'Books & Characters 📚', $$John Green, anxious spirals.$$, 'casual'),
('The Sun Is Also a Star', 'Books & Characters 📚', $$One day of love before a deportation.$$, 'casual'),
('The Selection', 'Books & Characters 📚', $$Thirty-five girls compete for a prince.$$, 'casual'),
('Water for Elephants', 'Books & Characters 📚', $$Depression-era circus vet.$$, 'casual'),
('The Darkest Minds', 'Books & Characters 📚', $$Kids with powers, on the run.$$, 'casual'),
-- ── Brands & Logos 🏷️ ──────────────────────────────────────────────────────
('Publix', 'Brands & Logos 🏷️', $$Southern grocery, where shopping is a pleasure.$$, 'casual'),
('Safeway', 'Brands & Logos 🏷️', $$Western US grocery chain.$$, 'casual'),
('Wegmans', 'Brands & Logos 🏷️', $$Cult-favorite East Coast grocer.$$, 'casual'),
('Sprouts', 'Brands & Logos 🏷️', $$Farmers-market-style grocer.$$, 'casual'),
('Arbys', 'Brands & Logos 🏷️', $$We have the meats.$$, 'casual'),
('Culvers', 'Brands & Logos 🏷️', $$Butter burgers and frozen custard.$$, 'casual'),
('Five Guys', 'Brands & Logos 🏷️', $$Burgers and free peanuts.$$, 'casual'),
('Shake Shack', 'Brands & Logos 🏷️', $$Trendy burgers and concretes.$$, 'casual'),
('Cracker Barrel', 'Brands & Logos 🏷️', $$Country store and rocking chairs.$$, 'casual'),
('Olive Garden', 'Brands & Logos 🏷️', $$Endless breadsticks.$$, 'casual'),
('Applebees', 'Brands & Logos 🏷️', $$Neighborhood grill and bar.$$, 'casual'),
('Chilis', 'Brands & Logos 🏷️', $$Baby back ribs jingle.$$, 'casual'),
('Outback', 'Brands & Logos 🏷️', $$Aussie-themed steakhouse.$$, 'casual'),
('Cheesecake Factory', 'Brands & Logos 🏷️', $$Huge menu, huge slices.$$, 'casual'),
('Waffle House', 'Brands & Logos 🏷️', $$24-hour yellow-sign diner.$$, 'casual'),
('Panda Express', 'Brands & Logos 🏷️', $$Mall orange chicken.$$, 'casual'),
('Jimmy Johns', 'Brands & Logos 🏷️', $$Freaky fast subs.$$, 'casual'),
('Jersey Mikes', 'Brands & Logos 🏷️', $$Subs Mikes Way.$$, 'casual'),
('Firehouse Subs', 'Brands & Logos 🏷️', $$Firefighter-themed sandwiches.$$, 'casual'),
('Auntie Annes', 'Brands & Logos 🏷️', $$Mall soft pretzels.$$, 'casual'),
('Cinnabon', 'Brands & Logos 🏷️', $$Airport cinnamon rolls.$$, 'casual'),
('Baskin Robbins', 'Brands & Logos 🏷️', $$Thirty-one ice cream flavors.$$, 'casual'),
('Sonic', 'Brands & Logos 🏷️', $$Drive-in with carhops.$$, 'casual'),
('Dennys', 'Brands & Logos 🏷️', $$Always-open Grand Slam diner.$$, 'casual'),
-- ── Famous People 🌟 ───────────────────────────────────────────────────────
('Bruno Mars', 'Famous People 🌟', $$Uptown Funk, retro showman.$$, 'casual'),
('Justin Timberlake', 'Famous People 🌟', $$NSYNC to solo, SexyBack.$$, 'casual'),
('Katy Perry', 'Famous People 🌟', $$Firework, whipped-cream cannons.$$, 'casual'),
('Ariana Grande', 'Famous People 🌟', $$Ponytail, whistle notes.$$, 'casual'),
('Selena Gomez', 'Famous People 🌟', $$Disney star turned pop mogul.$$, 'casual'),
('Ed Sheeran', 'Famous People 🌟', $$Ginger with a loop pedal.$$, 'casual'),
('Bruce Springsteen', 'Famous People 🌟', $$The Boss.$$, 'casual'),
('Stevie Wonder', 'Famous People 🌟', $$Blind Motown genius.$$, 'casual'),
('Dolly Parton', 'Famous People 🌟', $$Jolene, Dollywood, big heart.$$, 'casual'),
('Johnny Cash', 'Famous People 🌟', $$The Man in Black.$$, 'casual'),
('Willie Nelson', 'Famous People 🌟', $$Braided outlaw of country.$$, 'casual'),
('Snoop Dogg', 'Famous People 🌟', $$Laid-back West Coast rapper.$$, 'casual'),
('Eminem', 'Famous People 🌟', $$Slim Shady, Detroit rapper.$$, 'casual'),
('Kendrick Lamar', 'Famous People 🌟', $$Pulitzer-winning rapper.$$, 'casual'),
('Bad Bunny', 'Famous People 🌟', $$Puerto Rican reggaeton superstar.$$, 'casual'),
('Shakira', 'Famous People 🌟', $$Hips dont lie.$$, 'casual'),
('Celine Dion', 'Famous People 🌟', $$My Heart Will Go On.$$, 'casual'),
('Whitney Houston', 'Famous People 🌟', $$Powerhouse voice, I Will Always Love You.$$, 'casual'),
('Mariah Carey', 'Famous People 🌟', $$Five-octave range, Christmas anthem.$$, 'casual'),
('Janet Jackson', 'Famous People 🌟', $$Rhythm Nation, Michaels sister.$$, 'casual'),
('Diana Ross', 'Famous People 🌟', $$Supremes frontwoman.$$, 'casual'),
('Gloria Estefan', 'Famous People 🌟', $$Conga, Miami Sound Machine.$$, 'casual'),
('Ricky Martin', 'Famous People 🌟', $$Livin la Vida Loca.$$, 'casual'),
('Enrique Iglesias', 'Famous People 🌟', $$Hero, Latin pop heartthrob.$$, 'casual'),
-- ── Food & Drink 🍔 ────────────────────────────────────────────────────────
('Antipasto', 'Food & Drink 🍔', $$Cured meats and cheese starter.$$, 'casual'),
('Bibimbap', 'Food & Drink 🍔', $$Korean rice bowl with egg.$$, 'casual'),
('Bulgogi', 'Food & Drink 🍔', $$Korean marinated grilled beef.$$, 'casual'),
('Kimchi', 'Food & Drink 🍔', $$Fermented spicy cabbage.$$, 'casual'),
('Miso Soup', 'Food & Drink 🍔', $$Japanese soybean broth.$$, 'casual'),
('Wonton Soup', 'Food & Drink 🍔', $$Dumplings in clear broth.$$, 'casual'),
('Dim Sum', 'Food & Drink 🍔', $$Cart-served small plates.$$, 'casual'),
('Peking Duck', 'Food & Drink 🍔', $$Crispy-skinned roast duck.$$, 'casual'),
('Sesame Chicken', 'Food & Drink 🍔', $$Sweet takeout classic.$$, 'casual'),
('Orange Chicken', 'Food & Drink 🍔', $$Tangy battered chicken.$$, 'casual'),
('Kung Pao', 'Food & Drink 🍔', $$Spicy chicken with peanuts.$$, 'casual'),
('Mongolian Beef', 'Food & Drink 🍔', $$Sweet soy stir-fried beef.$$, 'casual'),
('Beef and Broccoli', 'Food & Drink 🍔', $$Takeout stir-fry staple.$$, 'casual'),
('Lo Mein', 'Food & Drink 🍔', $$Soft stir-fried noodles.$$, 'casual'),
('Sweet and Sour Pork', 'Food & Drink 🍔', $$Battered pork, bright red sauce.$$, 'casual'),
('Hot Pot', 'Food & Drink 🍔', $$Cook it yourself in simmering broth.$$, 'casual'),
('Banh Mi', 'Food & Drink 🍔', $$Vietnamese baguette sandwich.$$, 'casual'),
('Summer Roll', 'Food & Drink 🍔', $$Fresh rice-paper wrap.$$, 'casual'),
('Rice Bowl', 'Food & Drink 🍔', $$Toppings over a base of rice.$$, 'casual'),
('Acai Bowl', 'Food & Drink 🍔', $$Purple berry breakfast bowl.$$, 'casual'),
('Buddha Bowl', 'Food & Drink 🍔', $$Loaded veggie grain bowl.$$, 'casual'),
('Chow Fun', 'Food & Drink 🍔', $$Wide stir-fried rice noodles.$$, 'casual'),
('Katsu', 'Food & Drink 🍔', $$Panko-breaded fried cutlet.$$, 'casual'),
('Chili Crisp', 'Food & Drink 🍔', $$Crunchy spicy oil condiment.$$, 'casual'),
-- ── Movies & TV 🎬 ─────────────────────────────────────────────────────────
('Prisoners', 'Movies & TV 🎬', $$Father hunts for his abducted daughter.$$, 'casual'),
('Mystic River', 'Movies & TV 🎬', $$Boston childhood trauma and murder.$$, 'casual'),
('Zodiac', 'Movies & TV 🎬', $$Hunting a real serial killer.$$, 'casual'),
('Nightcrawler', 'Movies & TV 🎬', $$Freelance crime cameraman.$$, 'casual'),
('Sicario', 'Movies & TV 🎬', $$Cartel war on the border.$$, 'casual'),
('Wind River', 'Movies & TV 🎬', $$Murder on a snowy reservation.$$, 'casual'),
('Hell or High Water', 'Movies & TV 🎬', $$Brothers rob banks to save the ranch.$$, 'casual'),
('Manchester by the Sea', 'Movies & TV 🎬', $$Grieving uncle becomes guardian.$$, 'casual'),
('Lady Bird', 'Movies & TV 🎬', $$Sacramento teen and her mom.$$, 'casual'),
('Marriage Story', 'Movies & TV 🎬', $$A painful coast-to-coast divorce.$$, 'casual'),
('Uncut Gems', 'Movies & TV 🎬', $$Sandler jeweler spiraling on bets.$$, 'casual'),
('Doctor Strange', 'Movies & TV 🎬', $$Surgeon becomes sorcerer supreme.$$, 'casual'),
('Black Widow', 'Movies & TV 🎬', $$Natasha Romanoffs solo film.$$, 'casual'),
('Captain America', 'Movies & TV 🎬', $$Star-spangled super-soldier.$$, 'casual'),
('Thor Ragnarok', 'Movies & TV 🎬', $$Asgard falls, gladiator Hulk.$$, 'casual'),
('Avengers Endgame', 'Movies & TV 🎬', $$Whatever it takes.$$, 'casual'),
('Infinity War', 'Movies & TV 🎬', $$Thanos and the snap.$$, 'casual'),
('Ant Man', 'Movies & TV 🎬', $$Shrinking heist hero.$$, 'casual'),
('Doctor Who', 'Movies & TV 🎬', $$Time Lord in a blue box.$$, 'casual'),
('Severance', 'Movies & TV 🎬', $$Work memories split from home.$$, 'casual'),
('The Bear', 'Movies & TV 🎬', $$Chef takes over a chaotic kitchen.$$, 'casual'),
('Mindhunter', 'Movies & TV 🎬', $$FBI agents interview serial killers.$$, 'casual'),
('The Leftovers', 'Movies & TV 🎬', $$Two percent of people vanish.$$, 'casual'),
('This Is Us', 'Movies & TV 🎬', $$Big Three across the decades.$$, 'casual'),
-- ── Music 🎵 ───────────────────────────────────────────────────────────────
('American Idiot', 'Music 🎵', $$Green Day title track.$$, 'casual'),
('Basket Case', 'Music 🎵', $$Green Day, do you have the time.$$, 'casual'),
('Wake Me Up When September Ends', 'Music 🎵', $$Green Day autumn ballad.$$, 'casual'),
('Come As You Are', 'Music 🎵', $$Nirvana, memoria.$$, 'casual'),
('Heart Shaped Box', 'Music 🎵', $$Nirvana, meat-eating orchid.$$, 'casual'),
('Even Flow', 'Music 🎵', $$Pearl Jam grunge staple.$$, 'casual'),
('Interstate Love Song', 'Music 🎵', $$Stone Temple Pilots hit.$$, 'casual'),
('Bullet with Butterfly Wings', 'Music 🎵', $$Smashing Pumpkins, rat in a cage.$$, 'casual'),
('Bitter Sweet Symphony', 'Music 🎵', $$The Verve string-loop anthem.$$, 'casual'),
('Karma Police', 'Music 🎵', $$Radiohead, this is what youll get.$$, 'casual'),
('No Rain', 'Music 🎵', $$Blind Melon, bee-suit video.$$, 'casual'),
('Cannonball', 'Music 🎵', $$The Breeders alt hit.$$, 'casual'),
('Where Is My Mind', 'Music 🎵', $$Pixies, Fight Club ending.$$, 'casual'),
('Everlong', 'Music 🎵', $$Foo Fighters anthem.$$, 'casual'),
('My Own Worst Enemy', 'Music 🎵', $$Lit, woke up on the floor.$$, 'casual'),
('All Star', 'Music 🎵', $$Smash Mouth, somebody once told me.$$, 'casual'),
('Semi Charmed Life', 'Music 🎵', $$Third Eye Blind, doo doo doo.$$, 'casual'),
('Closing Time', 'Music 🎵', $$Semisonic, every new beginning.$$, 'casual'),
('Save Tonight', 'Music 🎵', $$Eagle Eye Cherry singalong.$$, 'casual'),
('Kiss Me', 'Music 🎵', $$Sixpence None the Richer.$$, 'casual'),
('One Week', 'Music 🎵', $$Barenaked Ladies rapid-fire hit.$$, 'casual'),
('Steal My Sunshine', 'Music 🎵', $$Len, sunny 1999 hit.$$, 'casual'),
('Building a Mystery', 'Music 🎵', $$Sarah McLachlan hit.$$, 'casual'),
('Meet Virginia', 'Music 🎵', $$Train, doesnt wear high heels.$$, 'casual'),
-- ── Phrases & Sayings 🗣️ ───────────────────────────────────────────────────
('Icing on the Cake', 'Phrases & Sayings 🗣️', $$A welcome bonus.$$, 'casual'),
('In the Bag', 'Phrases & Sayings 🗣️', $$Practically guaranteed.$$, 'casual'),
('Jump Ship', 'Phrases & Sayings 🗣️', $$Abandon a failing effort.$$, 'casual'),
('Keep an Eye On', 'Phrases & Sayings 🗣️', $$Watch closely.$$, 'casual'),
('Kick the Habit', 'Phrases & Sayings 🗣️', $$Quit something addictive.$$, 'casual'),
('Know the Ropes', 'Phrases & Sayings 🗣️', $$Understand how it all works.$$, 'casual'),
('Lend a Hand', 'Phrases & Sayings 🗣️', $$Offer help.$$, 'casual'),
('Lose Your Marbles', 'Phrases & Sayings 🗣️', $$Go a little crazy.$$, 'casual'),
('Make Ends Meet', 'Phrases & Sayings 🗣️', $$Get by financially.$$, 'casual'),
('Miss the Mark', 'Phrases & Sayings 🗣️', $$Fall short of the goal.$$, 'casual'),
('On the Ball', 'Phrases & Sayings 🗣️', $$Alert and competent.$$, 'casual'),
('Out of the Woods', 'Phrases & Sayings 🗣️', $$Past the danger.$$, 'casual'),
('Over the Moon', 'Phrases & Sayings 🗣️', $$Absolutely thrilled.$$, 'casual'),
('Play It by Ear', 'Phrases & Sayings 🗣️', $$Improvise as you go.$$, 'casual'),
('Pull Out All the Stops', 'Phrases & Sayings 🗣️', $$Do everything possible.$$, 'casual'),
('Put Your Foot Down', 'Phrases & Sayings 🗣️', $$Firmly refuse.$$, 'casual'),
('Rack Your Brain', 'Phrases & Sayings 🗣️', $$Think really hard.$$, 'casual'),
('Ring a Bell', 'Phrases & Sayings 🗣️', $$Sounds vaguely familiar.$$, 'casual'),
('Roll Up Your Sleeves', 'Phrases & Sayings 🗣️', $$Get ready for hard work.$$, 'casual'),
('Rub the Wrong Way', 'Phrases & Sayings 🗣️', $$Annoy or irritate.$$, 'casual'),
('Sell Like Hotcakes', 'Phrases & Sayings 🗣️', $$Fly off the shelves.$$, 'casual'),
('Sitting Duck', 'Phrases & Sayings 🗣️', $$An easy target.$$, 'casual'),
('Take the Plunge', 'Phrases & Sayings 🗣️', $$Finally commit.$$, 'casual'),
('Under Your Nose', 'Phrases & Sayings 🗣️', $$Right in plain sight.$$, 'casual'),
-- ── Places & Travel ✈️ ─────────────────────────────────────────────────────
('Belize', 'Places & Travel ✈️', $$Central American reef and jungle.$$, 'casual'),
('Guatemala', 'Places & Travel ✈️', $$Mayan ruins and volcanoes.$$, 'casual'),
('Nicaragua', 'Places & Travel ✈️', $$Lakes and volcanoes, Central America.$$, 'casual'),
('Ecuador', 'Places & Travel ✈️', $$Equator country, the Galapagos.$$, 'casual'),
('Bolivia', 'Places & Travel ✈️', $$Salt flats and high Andes.$$, 'casual'),
('Uruguay', 'Places & Travel ✈️', $$Small South American coast nation.$$, 'casual'),
('Colombia', 'Places & Travel ✈️', $$Coffee, Cartagena, cumbia.$$, 'casual'),
('Venezuela', 'Places & Travel ✈️', $$Angel Falls and oil.$$, 'casual'),
('Panama City', 'Places & Travel ✈️', $$Skyline beside the canal.$$, 'casual'),
('San Juan', 'Places & Travel ✈️', $$Puerto Ricos colorful capital.$$, 'casual'),
('Montego Bay', 'Places & Travel ✈️', $$Jamaican resort town.$$, 'casual'),
('Aruba', 'Places & Travel ✈️', $$Dry Caribbean island getaway.$$, 'casual'),
('Curacao', 'Places & Travel ✈️', $$Dutch Caribbean, pastel waterfront.$$, 'casual'),
('Barbados', 'Places & Travel ✈️', $$Eastern Caribbean island nation.$$, 'casual'),
('Cartagena', 'Places & Travel ✈️', $$Walled colonial Colombian port.$$, 'casual'),
('Medellin', 'Places & Travel ✈️', $$Colombias city of eternal spring.$$, 'casual'),
('Ushuaia', 'Places & Travel ✈️', $$The worlds southernmost city.$$, 'casual'),
('Saint Lucia', 'Places & Travel ✈️', $$Twin volcanic peaks, the Pitons.$$, 'casual'),
('Antigua', 'Places & Travel ✈️', $$Caribbean island, 365 beaches.$$, 'casual'),
('Trinidad', 'Places & Travel ✈️', $$Carnival and steel drums.$$, 'casual'),
('Grenada', 'Places & Travel ✈️', $$The Spice Isle.$$, 'casual'),
('Cordoba', 'Places & Travel ✈️', $$Andalusian city, the Mezquita.$$, 'casual'),
('Cusco', 'Places & Travel ✈️', $$Andean gateway to Machu Picchu.$$, 'casual'),
('Quito', 'Places & Travel ✈️', $$High-altitude Ecuadorian capital.$$, 'casual'),
-- ── Science & Nature 🔬 ────────────────────────────────────────────────────
('Acoustics', 'Science & Nature 🔬', $$The science of sound.$$, 'casual'),
('Adrenaline', 'Science & Nature 🔬', $$Fight-or-flight hormone.$$, 'casual'),
('Ammonia', 'Science & Nature 🔬', $$Sharp-smelling nitrogen compound.$$, 'casual'),
('Antenna', 'Science & Nature 🔬', $$An insects feeler.$$, 'casual'),
('Barometer', 'Science & Nature 🔬', $$Measures air pressure.$$, 'casual'),
('Beaker', 'Science & Nature 🔬', $$Lipped lab glass.$$, 'casual'),
('Bedrock', 'Science & Nature 🔬', $$Solid rock beneath the soil.$$, 'casual'),
('Calorie', 'Science & Nature 🔬', $$A unit of energy in food.$$, 'casual'),
('Calcium', 'Science & Nature 🔬', $$Bone-building element.$$, 'casual'),
('Cellulose', 'Science & Nature 🔬', $$Fiber in plant cell walls.$$, 'casual'),
('Cerebellum', 'Science & Nature 🔬', $$Brain region for balance.$$, 'casual'),
('Chlorine', 'Science & Nature 🔬', $$Pool-cleaning element.$$, 'casual'),
('Compound', 'Science & Nature 🔬', $$Two or more elements bonded.$$, 'casual'),
('Corrosion', 'Science & Nature 🔬', $$Metal wearing away, like rust.$$, 'casual'),
('Diffusion', 'Science & Nature 🔬', $$Particles spreading out.$$, 'casual'),
('Dinosaur', 'Science & Nature 🔬', $$Extinct prehistoric reptile.$$, 'casual'),
('Equator', 'Science & Nature 🔬', $$Zero degrees latitude.$$, 'casual'),
('Estuary', 'Science & Nature 🔬', $$Where a river meets the sea.$$, 'casual'),
('Filament', 'Science & Nature 🔬', $$Glowing thread in a bulb.$$, 'casual'),
('Follicle', 'Science & Nature 🔬', $$Where a hair grows.$$, 'casual'),
('Fructose', 'Science & Nature 🔬', $$Sugar found in fruit.$$, 'casual'),
('Glucose', 'Science & Nature 🔬', $$Bloods main sugar fuel.$$, 'casual'),
('Isotope', 'Science & Nature 🔬', $$Same element, different neutrons.$$, 'casual'),
('Latitude', 'Science & Nature 🔬', $$Distance north or south of the equator.$$, 'casual'),
-- ── Sports 🏆 ──────────────────────────────────────────────────────────────
('Audible', 'Sports 🏆', $$QB changes the play at the line.$$, 'casual'),
('Backboard', 'Sports 🏆', $$Where the rim is mounted.$$, 'casual'),
('Backcourt', 'Sports 🏆', $$The defensive half in basketball.$$, 'casual'),
('Ballpark', 'Sports 🏆', $$Where baseball is played.$$, 'casual'),
('Bleachers', 'Sports 🏆', $$Cheap backless seats.$$, 'casual'),
('Bullpen', 'Sports 🏆', $$Where relief pitchers warm up.$$, 'casual'),
('Cornerback', 'Sports 🏆', $$Covers the wide receiver.$$, 'casual'),
('Deadlift', 'Sports 🏆', $$Lifting a loaded bar off the floor.$$, 'casual'),
('Dribbling', 'Sports 🏆', $$Bouncing the ball while moving.$$, 'casual'),
('Face Mask', 'Sports 🏆', $$Grabbing the helmet cage, a penalty.$$, 'casual'),
('Fairway', 'Sports 🏆', $$Mown grass between tee and green.$$, 'casual'),
('Fielders Choice', 'Sports 🏆', $$Out recorded instead of the batter.$$, 'casual'),
('Forward Pass', 'Sports 🏆', $$Throwing it downfield.$$, 'casual'),
('Freestyle', 'Sports 🏆', $$Any-stroke swimming race.$$, 'casual'),
('Front Nine', 'Sports 🏆', $$First half of a golf round.$$, 'casual'),
('Goalpost', 'Sports 🏆', $$Uprights to kick between.$$, 'casual'),
('Grandstand', 'Sports 🏆', $$The main covered seating.$$, 'casual'),
('Halfback', 'Sports 🏆', $$Ball-carrying running back.$$, 'casual'),
('Handoff', 'Sports 🏆', $$Giving the ball to the runner.$$, 'casual'),
('Hurdle', 'Sports 🏆', $$Barrier to leap over on the track.$$, 'casual'),
('Bicycle', 'Sports 🏆', $$What you race in the Tour de France.$$, 'casual'),
('Scrimmage', 'Sports 🏆', $$A practice game.$$, 'casual'),
('Shortstop', 'Sports 🏆', $$Fields between second and third.$$, 'casual'),
('Sidearm', 'Sports 🏆', $$Throwing from the side, not overhand.$$, 'casual'),
-- ── Tech & Internet 💻 ─────────────────────────────────────────────────────
('Airplane Mode', 'Tech & Internet 💻', $$Cuts all wireless signals.$$, 'casual'),
('Analytics', 'Tech & Internet 💻', $$Data on how people use your app.$$, 'casual'),
('Automation', 'Tech & Internet 💻', $$Letting machines do the repetition.$$, 'casual'),
('Battery Life', 'Tech & Internet 💻', $$How long before a recharge.$$, 'casual'),
('Browser Tab', 'Tech & Internet 💻', $$One of many pages open at once.$$, 'casual'),
('Cellular', 'Tech & Internet 💻', $$Phone-network data.$$, 'casual'),
('Cloud Server', 'Tech & Internet 💻', $$A remote machine that hosts your data.$$, 'casual'),
('Direct Message', 'Tech & Internet 💻', $$A private DM.$$, 'casual'),
('Emulator', 'Tech & Internet 💻', $$Software mimicking another device.$$, 'casual'),
('Interface', 'Tech & Internet 💻', $$Where user meets machine.$$, 'casual'),
('Joystick', 'Tech & Internet 💻', $$Tilt-to-move controller stick.$$, 'casual'),
('Megapixel', 'Tech & Internet 💻', $$A million pixels of camera detail.$$, 'casual'),
('Modem', 'Tech & Internet 💻', $$Box that brings internet in.$$, 'casual'),
('Network', 'Tech & Internet 💻', $$Connected devices sharing data.$$, 'casual'),
('Offline', 'Tech & Internet 💻', $$Not connected to the internet.$$, 'casual'),
('Passcode', 'Tech & Internet 💻', $$Digits to unlock your phone.$$, 'casual'),
('Screen Lock', 'Tech & Internet 💻', $$Keeps others out of your phone.$$, 'casual'),
('Software', 'Tech & Internet 💻', $$Programs, not hardware.$$, 'casual'),
('Spreadsheet', 'Tech & Internet 💻', $$Rows and columns of cells.$$, 'casual'),
('System Update', 'Tech & Internet 💻', $$New OS version to install.$$, 'casual'),
('Template', 'Tech & Internet 💻', $$A reusable starting layout.$$, 'casual'),
('Terminal', 'Tech & Internet 💻', $$Command-line window.$$, 'casual'),
('Username', 'Tech & Internet 💻', $$Your login handle.$$, 'casual'),
('Web Browser', 'Tech & Internet 💻', $$Chrome, Safari, and friends.$$, 'casual'),
-- ── Video Games 🎮 ─────────────────────────────────────────────────────────
('Golden Axe', 'Video Games 🎮', $$Arcade hack-and-slash fantasy.$$, 'casual'),
('Grim Fandango', 'Video Games 🎮', $$Noir adventure in the land of the dead.$$, 'casual'),
('Guacamelee', 'Video Games 🎮', $$Luchador metroidvania.$$, 'casual'),
('Heavy Rain', 'Video Games 🎮', $$Choice-driven crime drama.$$, 'casual'),
('Hotline Miami', 'Video Games 🎮', $$Neon top-down 80s brutality.$$, 'casual'),
('Injustice', 'Video Games 🎮', $$DC heroes fighting game.$$, 'casual'),
('Jet Set Radio', 'Video Games 🎮', $$Cel-shaded graffiti skaters.$$, 'casual'),
('Killer Instinct', 'Video Games 🎮', $$C-C-C-Combo breaker!$$, 'casual'),
('Lego Star Wars', 'Video Games 🎮', $$Brick-built galaxy far away.$$, 'casual'),
('LittleBigPlanet', 'Video Games 🎮', $$Sackboy build-and-play.$$, 'casual'),
('Mafia', 'Video Games 🎮', $$Open-world mobster saga.$$, 'casual'),
('Mario Party', 'Video Games 🎮', $$Board game with minigames.$$, 'casual'),
('Metro Exodus', 'Video Games 🎮', $$Post-apocalyptic Russian shooter.$$, 'casual'),
('Monster Hunter', 'Video Games 🎮', $$Slay giant beasts, craft gear.$$, 'casual'),
('Nier Automata', 'Video Games 🎮', $$Androids and existential combat.$$, 'casual'),
('Octopath Traveler', 'Video Games 🎮', $$Eight heroes, retro-modern RPG.$$, 'casual'),
('Outlast', 'Video Games 🎮', $$Camcorder asylum horror.$$, 'casual'),
('Parappa the Rapper', 'Video Games 🎮', $$Gotta believe, rhythm game.$$, 'casual'),
('Persona', 'Video Games 🎮', $$School life meets demon dungeons.$$, 'casual'),
('Pikmin', 'Video Games 🎮', $$Command tiny plant creatures.$$, 'casual'),
('Plague Tale', 'Video Games 🎮', $$Siblings flee rats in medieval France.$$, 'casual'),
('Psychonauts', 'Video Games 🎮', $$Platforming inside peoples minds.$$, 'casual'),
('Rayman', 'Video Games 🎮', $$Limbless platforming hero.$$, 'casual'),
('Golden Sun', 'Video Games 🎮', $$Game Boy Advance RPG classic.$$, 'casual')
) AS v(phrase, category, clue, pool)
WHERE NOT EXISTS (
  SELECT 1 FROM public.daily_puzzles d WHERE upper(d.phrase) = upper(v.phrase)
);

COMMIT;
