-- Notifications: instant delivery + targeted clearing (2026-06-24).
-- Challenges (create_match) and friend requests (add_friend) already _notify the
-- recipient; these changes make the top-right badge update live and let the
-- act-now banner clear the right notification when you act on it.
--
-- Applied to prod via MCP:
--   * ALTER PUBLICATION supabase_realtime ADD TABLE public.notifications;
--     (notifications now broadcasts INSERTs; RLS notifications_self =
--      user_id = auth.uid() scopes delivery to the recipient. The client subscribes
--      in notificationStore.startNotifications(uid) → poll() on insert.)
--   * mark_notifications_read migrations (by_match / by_match_or_from):
--       mark_notifications_read(p_match_id uuid default null, p_from_id uuid default null)
--       - no args  → mark ALL my unread read (unchanged behavior)
--       - p_match_id → clear one challenge's notifs (banner-accept a challenge)
--       - p_from_id  → clear one person's friend-request notif (banner-accept a friend)
--     Front: notificationStore.markChallengeNotifRead(matchId) /
--     markFriendNotifRead(fromId); +page respondToMatch + acceptFriend call them.
--     +page also refreshes getMyMatches when unreadCount rises, so a new challenge
--     shows in the banner live (not just the badge).
--
-- Verified live (2 accounts): A challenges B → B badge 0→1 within ~5s with no refresh;
-- B accepts via the banner → badge → 0.
--
-- Follow-up (migration notifications_drop_chat_and_clear_friend_requests):
--   * Chat lives in the in-game 💬 icon only — send_match_message NO LONGER posts a
--     'challenge_chat' notification, and get_notifications excludes type='challenge_chat'
--     from both items + unread_count. Existing challenge_chat rows deleted.
--   * Friend-request notifications now auto-clear: respond_friend_request (and the
--     add_friend auto-accept branch) DELETE the recipient's friend_request notification
--     for that requester. respond_friend_request returns ok:true even when the request
--     was already handled (status 'friends'/'gone'), so a stale Accept resolves the UI
--     instead of doing nothing. Existing already-handled friend_request notifs deleted.
--   Verified (rolled back): accept → friends + notif deleted; accept again → 'friends';
--   live: @Chefcharles inbox left with only the legit challenge (chat + stale request gone).
