-- supabase-puzzles-seed-expansion-2.sql
-- Batch 2: adds 20 more puzzles to each of the 12 categories (240 total).
-- Brings every category from 80 to 100. Deduped against all 960 prior phrases.
-- Schema: daily_puzzles(id uuid default, phrase text, category text, subcategory text default '', clue text)

INSERT INTO public.daily_puzzles (phrase, category, clue) VALUES
-- ===== Books & Characters 📚 =====
('Watership Down', 'Books & Characters 📚', 'Rabbits seek a new warren.'),
('The Pearl', 'Books & Characters 📚', 'Fisherman finds cursed gem.'),
('The Hound of the Baskervilles', 'Books & Characters 📚', 'Sherlock and a spectral hound.'),
('Twenty Thousand Leagues', 'Books & Characters 📚', 'Captain Nemo submarine.'),
('Around the World in Eighty Days', 'Books & Characters 📚', 'Phileas Foggs wager.'),
('The Time Machine', 'Books & Characters 📚', 'Traveler visits the future.'),
('The Invisible Man', 'Books & Characters 📚', 'Scientist vanishes from sight.'),
('The War of the Worlds', 'Books & Characters 📚', 'Martians invade Earth.'),
('Dr Jekyll and Mr Hyde', 'Books & Characters 📚', 'Potion splits the man.'),
('The Picture of Dorian Gray', 'Books & Characters 📚', 'Portrait ages, not him.'),
('The Bell Jar', 'Books & Characters 📚', 'A young womans unraveling.'),
('Slaughterhouse Five', 'Books & Characters 📚', 'Unstuck in time, war.'),
('The Hitchhikers Guide', 'Books & Characters 📚', 'Dont panic, answer 42.'),
('The Name of the Wind', 'Books & Characters 📚', 'Musician magician legend.'),
('Eragon', 'Books & Characters 📚', 'Boy and his dragon.'),
('The Golden Compass', 'Books & Characters 📚', 'Girl and her daemon.'),
('Holes', 'Books & Characters 📚', 'Boys dig in the desert.'),
('Bridge to Terabithia', 'Books & Characters 📚', 'Imaginary kingdom friendship.'),
('The Phantom Tollbooth', 'Books & Characters 📚', 'Boy drives to wordland.'),
('Goosebumps', 'Books & Characters 📚', 'Spooky kids book series.'),
-- ===== Brands & Logos 🏷️ =====
('T Mobile', 'Brands & Logos 🏷️', 'Magenta phone carrier.'),
('Vodafone', 'Brands & Logos 🏷️', 'Red speech mark telecom.'),
('Shell', 'Brands & Logos 🏷️', 'Yellow seashell gas station.'),
('BP', 'Brands & Logos 🏷️', 'British petroleum giant.'),
('Chevron', 'Brands & Logos 🏷️', 'Blue and red gas brand.'),
('Volkswagen', 'Brands & Logos 🏷️', 'The peoples car.'),
('Hyundai', 'Brands & Logos 🏷️', 'Korean car brand.'),
('Kia', 'Brands & Logos 🏷️', 'Korean car maker.'),
('Nissan', 'Brands & Logos 🏷️', 'Japanese car brand.'),
('Volvo', 'Brands & Logos 🏷️', 'Safe Swedish cars.'),
('Jeep', 'Brands & Logos 🏷️', 'Rugged offroad SUV.'),
('Harley Davidson', 'Brands & Logos 🏷️', 'Loud American motorcycle.'),
('Canon', 'Brands & Logos 🏷️', 'Camera and printer maker.'),
('Nikon', 'Brands & Logos 🏷️', 'Camera lens brand.'),
('GoPro', 'Brands & Logos 🏷️', 'Action adventure camera.'),
('Fitbit', 'Brands & Logos 🏷️', 'Wrist fitness tracker.'),
('Dyson', 'Brands & Logos 🏷️', 'Bagless vacuum innovator.'),
('Bose', 'Brands & Logos 🏷️', 'Premium audio speakers.'),
('JBL', 'Brands & Logos 🏷️', 'Portable bluetooth speakers.'),
('Beats', 'Brands & Logos 🏷️', 'Headphones by Dre.'),
-- ===== Famous People 🌟 =====
('Jeff Bezos', 'Famous People 🌟', 'Amazon founder billionaire.'),
('Warren Buffett', 'Famous People 🌟', 'Omaha investing oracle.'),
('Neil deGrasse Tyson', 'Famous People 🌟', 'Famous astrophysicist communicator.'),
('Jane Goodall', 'Famous People 🌟', 'Chimpanzee researcher.'),
('Amelia Earhart', 'Famous People 🌟', 'Pioneering lost aviator.'),
('Wright Brothers', 'Famous People 🌟', 'First powered flight.'),
('Thomas Edison', 'Famous People 🌟', 'Light bulb inventor.'),
('Alexander Graham Bell', 'Famous People 🌟', 'Telephone inventor.'),
('Galileo Galilei', 'Famous People 🌟', 'Father of observation.'),
('Aristotle', 'Famous People 🌟', 'Ancient Greek philosopher.'),
('Plato', 'Famous People 🌟', 'Athenian philosopher of forms.'),
('Socrates', 'Famous People 🌟', 'Question everything philosopher.'),
('Confucius', 'Famous People 🌟', 'Chinese wisdom teacher.'),
('Karl Marx', 'Famous People 🌟', 'Wrote the Communist Manifesto.'),
('Sigmund Freud', 'Famous People 🌟', 'Father of psychoanalysis.'),
('Charles Dickens', 'Famous People 🌟', 'Victorian novelist.'),
('Jane Austen', 'Famous People 🌟', 'Pride and Prejudice author.'),
('Mark Twain', 'Famous People 🌟', 'Huckleberry Finn author.'),
('Maya Angelou', 'Famous People 🌟', 'Caged bird poet.'),
('Ernest Hemingway', 'Famous People 🌟', 'Spare prose novelist.'),
-- ===== Food & Drink 🍔 =====
('Calamari', 'Food & Drink 🍔', 'Fried squid rings.'),
('Ceviche', 'Food & Drink 🍔', 'Citrus cured raw fish.'),
('Poke Bowl', 'Food & Drink 🍔', 'Hawaiian raw fish bowl.'),
('Enchilada', 'Food & Drink 🍔', 'Rolled sauced tortilla.'),
('Fajitas', 'Food & Drink 🍔', 'Sizzling skillet strips.'),
('Empanada', 'Food & Drink 🍔', 'Stuffed pastry pocket.'),
('Tamale', 'Food & Drink 🍔', 'Corn husk wrapped masa.'),
('Goulash', 'Food & Drink 🍔', 'Hungarian beef paprika stew.'),
('Ratatouille', 'Food & Drink 🍔', 'French vegetable medley.'),
('Quiche', 'Food & Drink 🍔', 'Savory egg tart.'),
('Baguette', 'Food & Drink 🍔', 'Long French bread.'),
('Scone', 'Food & Drink 🍔', 'British tea biscuit.'),
('Muffin', 'Food & Drink 🍔', 'Sweet breakfast cake.'),
('Cupcake', 'Food & Drink 🍔', 'Frosted single serving cake.'),
('Macaroon', 'Food & Drink 🍔', 'Chewy coconut cookie.'),
('Gelato', 'Food & Drink 🍔', 'Italian frozen treat.'),
('Sorbet', 'Food & Drink 🍔', 'Fruity frozen dessert.'),
('Frappuccino', 'Food & Drink 🍔', 'Blended iced coffee.'),
('Matcha Latte', 'Food & Drink 🍔', 'Green tea milk drink.'),
('Bubble Tea', 'Food & Drink 🍔', 'Tapioca pearl drink.'),
-- ===== Movies & TV 🎬 =====
('The Departed', 'Movies & TV 🎬', 'Boston cop mole drama.'),
('Goodfellas', 'Movies & TV 🎬', 'Mob rise and fall.'),
('Scarface', 'Movies & TV 🎬', 'Say hello to my little friend.'),
('The Silence of the Lambs', 'Movies & TV 🎬', 'Hannibal and the FBI.'),
('Schindlers List', 'Movies & TV 🎬', 'Holocaust factory savior.'),
('Saving Private Ryan', 'Movies & TV 🎬', 'WWII rescue mission.'),
('Braveheart', 'Movies & TV 🎬', 'Scottish freedom fighter.'),
('The Green Mile', 'Movies & TV 🎬', 'Death row gentle giant.'),
('Shawshank Redemption', 'Movies & TV 🎬', 'Prison escape friendship.'),
('Mad Max', 'Movies & TV 🎬', 'Desert post apocalypse chase.'),
('Blade Runner', 'Movies & TV 🎬', 'Replicant hunting future.'),
('Alien', 'Movies & TV 🎬', 'Space monster terror.'),
('Predator', 'Movies & TV 🎬', 'Jungle alien hunter.'),
('The Terminator', 'Movies & TV 🎬', 'Time traveling killer robot.'),
('Ghostbusters', 'Movies & TV 🎬', 'Who you gonna call.'),
('Indiana Jones', 'Movies & TV 🎬', 'Whip cracking archaeologist.'),
('The Goonies', 'Movies & TV 🎬', 'Kids hunt pirate treasure.'),
('ET the Extra Terrestrial', 'Movies & TV 🎬', 'Alien phones home.'),
('Coco', 'Movies & TV 🎬', 'Boy in the land of dead.'),
('Up', 'Movies & TV 🎬', 'Floating balloon house.'),
-- ===== Music 🎵 =====
('Sweet Emotion', 'Music 🎵', 'Aerosmith classic riff.'),
('Dont Stop Me Now', 'Music 🎵', 'Queen, having fun.'),
('We Will Rock You', 'Music 🎵', 'Stomp stomp clap.'),
('We Are the Champions', 'Music 🎵', 'Queen victory anthem.'),
('Another Brick in the Wall', 'Music 🎵', 'Pink Floyd, no education.'),
('Comfortably Numb', 'Music 🎵', 'Pink Floyd haze.'),
('Light My Fire', 'Music 🎵', 'The Doors hit.'),
('Riders on the Storm', 'Music 🎵', 'The Doors rainy tune.'),
('Paint It Black', 'Music 🎵', 'Rolling Stones dark.'),
('Satisfaction', 'Music 🎵', 'Stones cant get none.'),
('Good Vibrations', 'Music 🎵', 'Beach Boys harmony.'),
('Dancing in the Dark', 'Music 🎵', 'Springsteen restless anthem.'),
('Empire State of Mind', 'Music 🎵', 'Jay Z New York.'),
('In Da Club', 'Music 🎵', 'Fifty Cent birthday anthem.'),
('Gold Digger', 'Music 🎵', 'Kanye and Jamie Foxx.'),
('Sicko Mode', 'Music 🎵', 'Travis Scott banger.'),
('Gods Plan', 'Music 🎵', 'Drake generosity hit.'),
('Bad Habits', 'Music 🎵', 'Ed Sheeran night out.'),
('Drivers License', 'Music 🎵', 'Olivia Rodrigo heartbreak.'),
('As It Was', 'Music 🎵', 'Harry Styles solo hit.'),
-- ===== Phrases & Sayings 🗣️ =====
('Actions Speak Louder Than Words', 'Phrases & Sayings 🗣️', 'Do, dont just say.'),
('The Grass Is Greener', 'Phrases & Sayings 🗣️', 'Others side seems better.'),
('Dont Count Your Chickens', 'Phrases & Sayings 🗣️', 'Wait before celebrating.'),
('A Bird in the Hand', 'Phrases & Sayings 🗣️', 'Keep the sure thing.'),
('The Pot Calling the Kettle', 'Phrases & Sayings 🗣️', 'Hypocrite criticizing.'),
('Bury the Hatchet', 'Phrases & Sayings 🗣️', 'Make peace, end feud.'),
('Costs a Pretty Penny', 'Phrases & Sayings 🗣️', 'Very expensive.'),
('Add Insult to Injury', 'Phrases & Sayings 🗣️', 'Make a bad thing worse.'),
('Beggars Cant Be Choosers', 'Phrases & Sayings 🗣️', 'Take what you get.'),
('Better Late Than Never', 'Phrases & Sayings 🗣️', 'Late beats not at all.'),
('Fish Out of Water', 'Phrases & Sayings 🗣️', 'Feeling out of place.'),
('Get Out of Hand', 'Phrases & Sayings 🗣️', 'Lose control of things.'),
('Go Back to the Drawing Board', 'Phrases & Sayings 🗣️', 'Start over fresh.'),
('Hit Below the Belt', 'Phrases & Sayings 🗣️', 'An unfair blow.'),
('Ignorance Is Bliss', 'Phrases & Sayings 🗣️', 'Not knowing is happier.'),
('Kick the Bucket', 'Phrases & Sayings 🗣️', 'Pass away.'),
('Let Bygones Be Bygones', 'Phrases & Sayings 🗣️', 'Forget old grudges.'),
('Light at the End of the Tunnel', 'Phrases & Sayings 🗣️', 'Hope after hardship.'),
('Make Hay While the Sun Shines', 'Phrases & Sayings 🗣️', 'Seize the opportunity.'),
('Two Peas in a Pod', 'Phrases & Sayings 🗣️', 'Very alike pair.'),
-- ===== Places & Travel ✈️ =====
('Lisbon', 'Places & Travel ✈️', 'Portuguese coastal capital.'),
('Madrid', 'Places & Travel ✈️', 'Spanish royal capital.'),
('Florence', 'Places & Travel ✈️', 'Renaissance art city.'),
('Naples', 'Places & Travel ✈️', 'Italian pizza birthplace.'),
('Milan', 'Places & Travel ✈️', 'Italian fashion capital.'),
('Munich', 'Places & Travel ✈️', 'Bavarian beer city.'),
('Copenhagen', 'Places & Travel ✈️', 'Danish harbor capital.'),
('Stockholm', 'Places & Travel ✈️', 'Swedish island capital.'),
('Oslo', 'Places & Travel ✈️', 'Norwegian fjord capital.'),
('Helsinki', 'Places & Travel ✈️', 'Finnish design capital.'),
('Budapest', 'Places & Travel ✈️', 'Danube thermal baths.'),
('Warsaw', 'Places & Travel ✈️', 'Polish rebuilt capital.'),
('Zurich', 'Places & Travel ✈️', 'Swiss banking city.'),
('Geneva', 'Places & Travel ✈️', 'Lakeside Swiss city.'),
('Brussels', 'Places & Travel ✈️', 'Belgian waffle capital.'),
('Lima', 'Places & Travel ✈️', 'Peruvian coastal capital.'),
('Havana', 'Places & Travel ✈️', 'Cuban vintage cars.'),
('Casablanca', 'Places & Travel ✈️', 'Moroccan port city.'),
('Nairobi', 'Places & Travel ✈️', 'Kenyan safari gateway.'),
('Yosemite', 'Places & Travel ✈️', 'California granite valley.'),
-- ===== Science & Nature 🔬 =====
('Mitosis', 'Science & Nature 🔬', 'Cell splits in two.'),
('Meiosis', 'Science & Nature 🔬', 'Sex cell division.'),
('Fermentation', 'Science & Nature 🔬', 'Microbes make alcohol.'),
('Oxidation', 'Science & Nature 🔬', 'The rusting reaction.'),
('Sublimation', 'Science & Nature 🔬', 'Solid straight to gas.'),
('Catalyst', 'Science & Nature 🔬', 'Speeds up reactions.'),
('Entropy', 'Science & Nature 🔬', 'Measure of disorder.'),
('Kinetic Energy', 'Science & Nature 🔬', 'Energy of motion.'),
('Potential Energy', 'Science & Nature 🔬', 'Stored up energy.'),
('Static Electricity', 'Science & Nature 🔬', 'Shock from the carpet.'),
('Sound Waves', 'Science & Nature 🔬', 'Vibrations we hear.'),
('Ultraviolet', 'Science & Nature 🔬', 'Invisible sunburn rays.'),
('Infrared', 'Science & Nature 🔬', 'Heat sensing light.'),
('Atoms', 'Science & Nature 🔬', 'Tiny matter building blocks.'),
('Molecules', 'Science & Nature 🔬', 'Bonded atom groups.'),
('Electrons', 'Science & Nature 🔬', 'Negative orbiting particles.'),
('Photons', 'Science & Nature 🔬', 'Particles of light.'),
('Nebula', 'Science & Nature 🔬', 'Cloud of space gas.'),
('Galaxy', 'Science & Nature 🔬', 'Vast star system.'),
('Constellation', 'Science & Nature 🔬', 'Star pattern picture.'),
-- ===== Sports 🏆 =====
('Layup', 'Sports 🏆', 'Easy basketball shot.'),
('Jump Shot', 'Sports 🏆', 'Mid range basketball shot.'),
('Crossover', 'Sports 🏆', 'Ankle breaking dribble.'),
('Rebound', 'Sports 🏆', 'Grab the missed shot.'),
('Assist', 'Sports 🏆', 'Pass leading to a score.'),
('Header', 'Sports 🏆', 'Score with your head.'),
('Volley', 'Sports 🏆', 'Strike the ball mid air.'),
('Slide Tackle', 'Sports 🏆', 'Sliding ball steal.'),
('Yellow Card', 'Sports 🏆', 'Soccer caution.'),
('Pinch Hitter', 'Sports 🏆', 'Substitute batter.'),
('Sacrifice Fly', 'Sports 🏆', 'Out that scores a run.'),
('No Hitter', 'Sports 🏆', 'Pitcher allows no hits.'),
('Quarterback Sneak', 'Sports 🏆', 'Short yardage push.'),
('Blitz', 'Sports 🏆', 'Defensive rush play.'),
('Interception', 'Sports 🏆', 'Defense catches the pass.'),
('Fumble', 'Sports 🏆', 'A dropped football.'),
('Tiebreak', 'Sports 🏆', 'Tennis deciding game.'),
('Slice', 'Sports 🏆', 'Spinning tennis shot.'),
('Bogey', 'Sports 🏆', 'One over par golf.'),
('Face Off', 'Sports 🏆', 'Hockey puck drop.'),
-- ===== Tech & Internet 💻 =====
('Webcam', 'Tech & Internet 💻', 'Video chat camera.'),
('Keyboard Shortcut', 'Tech & Internet 💻', 'Quick key combo.'),
('Copy and Paste', 'Tech & Internet 💻', 'Duplicate and place text.'),
('Screenshot', 'Tech & Internet 💻', 'Capture your screen.'),
('Refresh Rate', 'Tech & Internet 💻', 'Screen update speed.'),
('Dark Mode', 'Tech & Internet 💻', 'Easy on the eyes theme.'),
('Notification', 'Tech & Internet 💻', 'An app alert ping.'),
('Biometrics', 'Tech & Internet 💻', 'Fingerprint or face login.'),
('Geolocation', 'Tech & Internet 💻', 'Pinpointing your position.'),
('Latency', 'Tech & Internet 💻', 'Network delay lag.'),
('Buffering', 'Tech & Internet 💻', 'Loading spinner wait.'),
('Hyperlink', 'Tech & Internet 💻', 'Clickable web link.'),
('URL', 'Tech & Internet 💻', 'A web address line.'),
('Database', 'Tech & Internet 💻', 'Organized data store.'),
('Debugging', 'Tech & Internet 💻', 'Fixing code errors.'),
('Pixelation', 'Tech & Internet 💻', 'Blocky low res image.'),
('Emoticon', 'Tech & Internet 💻', 'Smiley from punctuation.'),
('Trolling', 'Tech & Internet 💻', 'Provoking online users.'),
('Catfishing', 'Tech & Internet 💻', 'Fake online identity.'),
('Unboxing', 'Tech & Internet 💻', 'Opening new product video.'),
-- ===== Video Games 🎮 =====
('Tekken', 'Video Games 🎮', '3D fighting game.'),
('Guitar Hero', 'Video Games 🎮', 'Plastic guitar rhythm.'),
('Just Dance', 'Video Games 🎮', 'Motion dance game.'),
('Rock Band', 'Video Games 🎮', 'Full band rhythm game.'),
('Five Nights at Freddys', 'Video Games 🎮', 'Haunted animatronics.'),
('Undertale', 'Video Games 🎮', 'You dont have to fight.'),
('Terraria', 'Video Games 🎮', '2D dig and build.'),
('No Mans Sky', 'Video Games 🎮', 'Infinite space exploration.'),
('Starfield', 'Video Games 🎮', 'Bethesda space RPG.'),
('Baldurs Gate', 'Video Games 🎮', 'D and D party RPG.'),
('Hades', 'Video Games 🎮', 'Escape the underworld.'),
('Celeste', 'Video Games 🎮', 'Climb the mountain.'),
('Ori', 'Video Games 🎮', 'Glowing forest spirit.'),
('Limbo', 'Video Games 🎮', 'Dark puzzle platformer.'),
('Bejeweled', 'Video Games 🎮', 'Match three gems.'),
('Words with Friends', 'Video Games 🎮', 'Online word tiles.'),
('Clash of Clans', 'Video Games 🎮', 'Build and raid villages.'),
('Clash Royale', 'Video Games 🎮', 'Card tower battler.'),
('Brawl Stars', 'Video Games 🎮', 'Mobile arena brawler.'),
('PUBG', 'Video Games 🎮', 'Battle royale original.');

-- Verify after running:
-- SELECT category, count(*) FROM public.daily_puzzles GROUP BY category ORDER BY category;
