-- ╔══════════════════════════════════════════════════════════════════════════╗
-- ║  Daily reward = a fixed "puzzle worth" (par), not efficiency multipliers    ║
-- ║  (migration: v3_daily_fixed_reward — applied via MCP)                       ║
-- ╚══════════════════════════════════════════════════════════════════════════╝
-- Per design feedback: clearer model. The puzzle is WORTH a fixed reward based on
-- its length/difficulty; the player just spends as little as possible. Net profit =
-- reward − spent. Drops the clean/no-vowel/first-try multipliers (which were mostly
-- redundant with spend anyway). Same shape as the Climb bounty → Daily & Climb now
-- consistent ("a puzzle is worth a % of its full-reveal cost").
--
-- _daily_reward(pid) = GREATEST(100, $10-rounded 1.20 × Σ distinct letter_cost).
--   [v3.2; was 0.70] k=1.20 > 1.0 → Daily is the forgiving paycheck (a solve always
--   nets +); Climb stays steep at 0.85 (full reveal loses). KNOB. See
--   supabase-economy-v3-2-rebalance.sql.
-- _daily_live(spent, reward) → { spent, reward, net=reward−spent }.
-- daily_start / _daily_resolve_and_return feed the fixed reward into live.
-- _finalize_daily: credits the gross reward; game_results.score = NET PROFIT
--   (reward − spent) so the Daily leaderboard ranks by efficiency (not everyone tied).
-- daily_result payload → { reward, spent, net }.
--
-- Verified (rolled-back sim, Chef): reward $500 (length-based), spent $143,
--   net $357; full day cash flow = attendance 150 + reward 500 − spent 143 = +507.
--
-- Client: live line shows "Worth $X · spent $Y · profit +$Z" (red if negative) for
--   Daily + Climb; result modal shows Profit + worth/spent (dropped the eff chips);
--   come-back modal + share text say "Profit"; no more reward-flash (reward is fixed).
