-- ============================================================================
-- Puzzle pool expansion — batch 5: ALL CASUAL. +25 per category (×12 = 300), 100% casual.
-- Daily pool (1,200) is already ~3+ years deep at 1 puzzle/day, so no more daily is needed;
-- casual is the pool engaged players actually burn through (Cash Game / Free Play / Challenges).
-- Deduped against all prior batches (case-insensitive).
-- Data-only (applied to prod): no binary change, no App Store impact, survives reset.
-- ============================================================================
BEGIN;

INSERT INTO public.daily_puzzles (phrase, category, clue, pool)
SELECT v.phrase, v.category, v.clue, v.pool
FROM (VALUES
-- ── Books & Characters 📚 ──────────────────────────────────────────────────
('The Fellowship of the Ring', 'Books & Characters 📚', $$First leg of the quest to Mordor.$$, 'casual'),
('The Return of the King', 'Books & Characters 📚', $$Aragorn takes the throne.$$, 'casual'),
('Good Omens', 'Books & Characters 📚', $$An angel and a demon stop the apocalypse.$$, 'casual'),
('Project Hail Mary', 'Books & Characters 📚', $$Lone astronaut, an alien named Rocky.$$, 'casual'),
('The Help', 'Books & Characters 📚', $$Maids in 1960s Mississippi.$$, 'casual'),
('The Two Towers', 'Books & Characters 📚', $$Middle volume of the Ring saga.$$, 'casual'),
('A Feast for Crows', 'Books & Characters 📚', $$Fourth Westeros volume.$$, 'casual'),
('A Dance with Dragons', 'Books & Characters 📚', $$Fifth Westeros volume.$$, 'casual'),
('The Eye of the World', 'Books & Characters 📚', $$Book one of the Wheel of Time.$$, 'casual'),
('The Gunslinger', 'Books & Characters 📚', $$King, the man in black, the Dark Tower.$$, 'casual'),
('Coraline', 'Books & Characters 📚', $$Girl, other mother, button eyes.$$, 'casual'),
('The Graveyard Book', 'Books & Characters 📚', $$Boy raised by ghosts.$$, 'casual'),
('Stardust', 'Books & Characters 📚', $$A fallen star and a wall.$$, 'casual'),
('The Midnight Library', 'Books & Characters 📚', $$Every life you could have lived.$$, 'casual'),
('Klara and the Sun', 'Books & Characters 📚', $$Android friend powered by the sun.$$, 'casual'),
('Never Let Me Go', 'Books & Characters 📚', $$Boarding-school clones.$$, 'casual'),
('Remains of the Day', 'Books & Characters 📚', $$A butlers quiet regret.$$, 'casual'),
('Atonement', 'Books & Characters 📚', $$A childs lie ruins two lives.$$, 'casual'),
('Cloud Atlas', 'Books & Characters 📚', $$Six nested stories across time.$$, 'casual'),
('The Time Travelers Wife', 'Books & Characters 📚', $$Love with a man who jumps in time.$$, 'casual'),
('Water for Elephants', 'Books & Characters 📚', $$Depression-era circus romance.$$, 'casual'),
('The Ocean at the End of the Lane', 'Books & Characters 📚', $$Gaiman, a pond that is an ocean.$$, 'casual'),
('The Color of Magic', 'Books & Characters 📚', $$First Discworld novel.$$, 'casual'),
('Ready Player Two', 'Books & Characters 📚', $$Sequel back inside the OASIS.$$, 'casual'),
('The Immortal Life of Henrietta Lacks', 'Books & Characters 📚', $$Cells taken without consent.$$, 'casual'),
-- ── Brands & Logos 🏷️ ──────────────────────────────────────────────────────
('Gap', 'Brands & Logos 🏷️', $$Blue-box casual clothing.$$, 'casual'),
('H&M', 'Brands & Logos 🏷️', $$Swedish fast fashion.$$, 'casual'),
('Zara', 'Brands & Logos 🏷️', $$Spanish fast fashion.$$, 'casual'),
('The North Face', 'Brands & Logos 🏷️', $$Half-dome outdoor gear.$$, 'casual'),
('New Balance', 'Brands & Logos 🏷️', $$Dad-shoe sneaker brand.$$, 'casual'),
('Old Navy', 'Brands & Logos 🏷️', $$Budget family clothing.$$, 'casual'),
('Banana Republic', 'Brands & Logos 🏷️', $$Upscale sibling of Gap.$$, 'casual'),
('Uniqlo', 'Brands & Logos 🏷️', $$Japanese basics retailer.$$, 'casual'),
('Forever 21', 'Brands & Logos 🏷️', $$Teen fast-fashion chain.$$, 'casual'),
('Victorias Secret', 'Brands & Logos 🏷️', $$Lingerie with an angels runway.$$, 'casual'),
('Lululemon', 'Brands & Logos 🏷️', $$Premium yoga pants.$$, 'casual'),
('Patagonia', 'Brands & Logos 🏷️', $$Fleece and eco-activism.$$, 'casual'),
('Columbia', 'Brands & Logos 🏷️', $$Outdoor jackets and boots.$$, 'casual'),
('Converse', 'Brands & Logos 🏷️', $$Chuck Taylor high-tops.$$, 'casual'),
('Skechers', 'Brands & Logos 🏷️', $$Comfy casual shoes.$$, 'casual'),
('Timberland', 'Brands & Logos 🏷️', $$Wheat-colored work boots.$$, 'casual'),
('Oakley', 'Brands & Logos 🏷️', $$Sporty sunglasses.$$, 'casual'),
('Fossil', 'Brands & Logos 🏷️', $$Watches and leather goods.$$, 'casual'),
('Michael Kors', 'Brands & Logos 🏷️', $$Designer handbags, MK logo.$$, 'casual'),
('Coach', 'Brands & Logos 🏷️', $$Horse-and-carriage leather bags.$$, 'casual'),
('Kate Spade', 'Brands & Logos 🏷️', $$Playful designer handbags.$$, 'casual'),
('Tiffany', 'Brands & Logos 🏷️', $$Robin-egg blue jewelry boxes.$$, 'casual'),
('Casio', 'Brands & Logos 🏷️', $$Digital watches and calculators.$$, 'casual'),
('Timex', 'Brands & Logos 🏷️', $$Takes a licking, keeps ticking.$$, 'casual'),
-- ── Famous People 🌟 ───────────────────────────────────────────────────────
('Denzel Washington', 'Famous People 🌟', $$Two-time Oscar-winning actor.$$, 'casual'),
('Morgan Freeman', 'Famous People 🌟', $$That unmistakable narrator voice.$$, 'casual'),
('Julia Roberts', 'Famous People 🌟', $$Pretty Woman, megawatt smile.$$, 'casual'),
('Jennifer Lawrence', 'Famous People 🌟', $$Katniss, tripped at the Oscars.$$, 'casual'),
('Ryan Reynolds', 'Famous People 🌟', $$Deadpool, Aviation gin.$$, 'casual'),
('Robert De Niro', 'Famous People 🌟', $$You talkin to me?$$, 'casual'),
('Al Pacino', 'Famous People 🌟', $$Say hello to my little friend.$$, 'casual'),
('Jack Nicholson', 'Famous People 🌟', $$Heres Johnny, arched eyebrows.$$, 'casual'),
('Clint Eastwood', 'Famous People 🌟', $$Make my day, spaghetti westerns.$$, 'casual'),
('Harrison Ford', 'Famous People 🌟', $$Han Solo and Indiana Jones.$$, 'casual'),
('Samuel L Jackson', 'Famous People 🌟', $$Pulp Fiction, Nick Fury.$$, 'casual'),
('Scarlett Johansson', 'Famous People 🌟', $$Black Widow.$$, 'casual'),
('Emma Watson', 'Famous People 🌟', $$Hermione Granger.$$, 'casual'),
('Natalie Portman', 'Famous People 🌟', $$Black Swan, Padme.$$, 'casual'),
('Anne Hathaway', 'Famous People 🌟', $$The Devil Wears Prada.$$, 'casual'),
('Sandra Bullock', 'Famous People 🌟', $$Speed, Miss Congeniality.$$, 'casual'),
('Nicole Kidman', 'Famous People 🌟', $$Australian Oscar winner.$$, 'casual'),
('Cate Blanchett', 'Famous People 🌟', $$Played Galadriel and a queen.$$, 'casual'),
('Viola Davis', 'Famous People 🌟', $$Powerhouse of stage and screen.$$, 'casual'),
('Halle Berry', 'Famous People 🌟', $$First Black Best Actress winner.$$, 'casual'),
('Charlize Theron', 'Famous People 🌟', $$Monster, Mad Max Furiosa.$$, 'casual'),
('Chris Hemsworth', 'Famous People 🌟', $$Wields Thors hammer.$$, 'casual'),
('Ryan Gosling', 'Famous People 🌟', $$Drive, La La Land, Ken.$$, 'casual'),
('Timothee Chalamet', 'Famous People 🌟', $$Dune, Willy Wonka.$$, 'casual'),
-- ── Food & Drink 🍔 ────────────────────────────────────────────────────────
('Hash Browns', 'Food & Drink 🍔', $$Crispy shredded breakfast potatoes.$$, 'casual'),
('Omelette', 'Food & Drink 🍔', $$Folded eggs with fillings.$$, 'casual'),
('Gumbo', 'Food & Drink 🍔', $$Louisiana stew over rice.$$, 'casual'),
('Lobster Roll', 'Food & Drink 🍔', $$New England seafood in a bun.$$, 'casual'),
('Carbonara', 'Food & Drink 🍔', $$Pasta with egg, cheese, and bacon.$$, 'casual'),
('Chicken Fried Steak', 'Food & Drink 🍔', $$Breaded beef with white gravy.$$, 'casual'),
('Biscuits and Gravy', 'Food & Drink 🍔', $$Southern breakfast smother.$$, 'casual'),
('Frittata', 'Food & Drink 🍔', $$Open-faced Italian omelette.$$, 'casual'),
('Prosciutto', 'Food & Drink 🍔', $$Thin-sliced cured ham.$$, 'casual'),
('Bratwurst', 'Food & Drink 🍔', $$German grilling sausage.$$, 'casual'),
('Chorizo', 'Food & Drink 🍔', $$Spicy red sausage.$$, 'casual'),
('Jambalaya', 'Food & Drink 🍔', $$Creole rice, meat, and spice.$$, 'casual'),
('Etouffee', 'Food & Drink 🍔', $$Smothered crawfish over rice.$$, 'casual'),
('Po Boy', 'Food & Drink 🍔', $$Louisiana sub sandwich.$$, 'casual'),
('Crab Cakes', 'Food & Drink 🍔', $$Pan-fried Maryland patties.$$, 'casual'),
('Shrimp Scampi', 'Food & Drink 🍔', $$Garlic-butter shrimp over pasta.$$, 'casual'),
('Beef Stroganoff', 'Food & Drink 🍔', $$Sour-cream beef over noodles.$$, 'casual'),
('Chicken Cordon Bleu', 'Food & Drink 🍔', $$Chicken stuffed with ham and cheese.$$, 'casual'),
('Osso Buco', 'Food & Drink 🍔', $$Braised veal shanks.$$, 'casual'),
('Bolognese', 'Food & Drink 🍔', $$Rich meat sauce for pasta.$$, 'casual'),
('Kielbasa', 'Food & Drink 🍔', $$Polish smoked sausage.$$, 'casual'),
('Veal Parmesan', 'Food & Drink 🍔', $$Breaded veal, sauce, cheese.$$, 'casual'),
('Oysters Rockefeller', 'Food & Drink 🍔', $$Baked oysters with greens.$$, 'casual'),
('Crawfish Boil', 'Food & Drink 🍔', $$Spicy Cajun seafood feast.$$, 'casual'),
-- ── Movies & TV 🎬 ─────────────────────────────────────────────────────────
('Cast Away', 'Movies & TV 🎬', $$Tom Hanks, a volleyball named Wilson.$$, 'casual'),
('Apollo 13', 'Movies & TV 🎬', $$Houston, we have a problem.$$, 'casual'),
('Skyfall', 'Movies & TV 🎬', $$Bond returns to his Scottish home.$$, 'casual'),
('Mary Poppins', 'Movies & TV 🎬', $$Practically perfect flying nanny.$$, 'casual'),
('The Sound of Music', 'Movies & TV 🎬', $$Singing von Trapps flee the Nazis.$$, 'casual'),
('A Few Good Men', 'Movies & TV 🎬', $$You cant handle the truth!$$, 'casual'),
('Dead Poets Society', 'Movies & TV 🎬', $$O Captain, my Captain.$$, 'casual'),
('Green Book', 'Movies & TV 🎬', $$Pianist and driver road trip.$$, 'casual'),
('Rocketman', 'Movies & TV 🎬', $$Elton John musical biopic.$$, 'casual'),
('The Kings Speech', 'Movies & TV 🎬', $$A stammering king finds his voice.$$, 'casual'),
('Argo', 'Movies & TV 🎬', $$Fake movie rescues hostages in Iran.$$, 'casual'),
('Spotlight', 'Movies & TV 🎬', $$Boston reporters break a scandal.$$, 'casual'),
('Birdman', 'Movies & TV 🎬', $$Faded superhero actor, one long take.$$, 'casual'),
('Moonlight', 'Movies & TV 🎬', $$Coming of age in three chapters.$$, 'casual'),
('Nomadland', 'Movies & TV 🎬', $$Living out of a van on the road.$$, 'casual'),
('CODA', 'Movies & TV 🎬', $$Hearing girl in a deaf family.$$, 'casual'),
('Everything Everywhere All at Once', 'Movies & TV 🎬', $$Multiverse laundromat and hot dogs.$$, 'casual'),
('The Shape of Water', 'Movies & TV 🎬', $$Woman loves an amphibian man.$$, 'casual'),
('Twelve Years a Slave', 'Movies & TV 🎬', $$Free man sold into slavery.$$, 'casual'),
('No Time to Die', 'Movies & TV 🎬', $$Craigs final Bond.$$, 'casual'),
('Dr No', 'Movies & TV 🎬', $$The very first Bond film.$$, 'casual'),
('West Side Story', 'Movies & TV 🎬', $$Sharks and Jets, a musical Romeo.$$, 'casual'),
('Singin in the Rain', 'Movies & TV 🎬', $$Dancing with an umbrella.$$, 'casual'),
('Willy Wonka', 'Movies & TV 🎬', $$Golden tickets, chocolate river.$$, 'casual'),
-- ── Music 🎵 ───────────────────────────────────────────────────────────────
('American Pie', 'Music 🎵', $$Don McLean, the day the music died.$$, 'casual'),
('Here Comes the Sun', 'Music 🎵', $$Beatles, little darling.$$, 'casual'),
('Respect', 'Music 🎵', $$Aretha spells it out.$$, 'casual'),
('The Sound of Silence', 'Music 🎵', $$Simon and Garfunkel, hello darkness.$$, 'casual'),
('Landslide', 'Music 🎵', $$Fleetwood Mac, built my life around you.$$, 'casual'),
('Whats Going On', 'Music 🎵', $$Marvin Gaye plea for peace.$$, 'casual'),
('Aint No Mountain High Enough', 'Music 🎵', $$Motown duet, nothing can keep me.$$, 'casual'),
('My Girl', 'Music 🎵', $$The Temptations, sunshine.$$, 'casual'),
('I Heard It Through the Grapevine', 'Music 🎵', $$Marvin Gaye, bout to lose your mind.$$, 'casual'),
('Superstition', 'Music 🎵', $$Stevie Wonder clavinet groove.$$, 'casual'),
('Sir Duke', 'Music 🎵', $$Stevie Wonder horn tribute.$$, 'casual'),
('Isnt She Lovely', 'Music 🎵', $$Stevie Wonder celebrates his daughter.$$, 'casual'),
('September', 'Music 🎵', $$Earth Wind and Fire, ba-dee-ya.$$, 'casual'),
('Come Together', 'Music 🎵', $$Beatles, right now over me.$$, 'casual'),
('While My Guitar Gently Weeps', 'Music 🎵', $$Harrison Beatles ballad.$$, 'casual'),
('A Day in the Life', 'Music 🎵', $$Beatles, I read the news today.$$, 'casual'),
('Lucy in the Sky with Diamonds', 'Music 🎵', $$Beatles, tangerine trees.$$, 'casual'),
('Twist and Shout', 'Music 🎵', $$Beatles, shake it up baby.$$, 'casual'),
('Wouldnt It Be Nice', 'Music 🎵', $$Beach Boys daydream.$$, 'casual'),
('California Dreamin', 'Music 🎵', $$Mamas and the Papas, leaves are brown.$$, 'casual'),
('House of the Rising Sun', 'Music 🎵', $$The Animals, New Orleans lament.$$, 'casual'),
('Bridge Over Troubled Water', 'Music 🎵', $$Simon and Garfunkel, Ill lay me down.$$, 'casual'),
('Mrs Robinson', 'Music 🎵', $$Simon and Garfunkel, Jesus loves you.$$, 'casual'),
('Vienna', 'Music 🎵', $$Billy Joel, waits for you.$$, 'casual'),
-- ── Phrases & Sayings 🗣️ ───────────────────────────────────────────────────
('At the Drop of a Hat', 'Phrases & Sayings 🗣️', $$Without hesitation.$$, 'casual'),
('Bite Your Tongue', 'Phrases & Sayings 🗣️', $$Hold back what you want to say.$$, 'casual'),
('Cry Wolf', 'Phrases & Sayings 🗣️', $$Raise a false alarm.$$, 'casual'),
('Draw the Line', 'Phrases & Sayings 🗣️', $$Set a firm limit.$$, 'casual'),
('Hit the Ground Running', 'Phrases & Sayings 🗣️', $$Start with full momentum.$$, 'casual'),
('A Watched Pot Never Boils', 'Phrases & Sayings 🗣️', $$Waiting makes time crawl.$$, 'casual'),
('All Bark and No Bite', 'Phrases & Sayings 🗣️', $$Threatens but never acts.$$, 'casual'),
('Ants in Your Pants', 'Phrases & Sayings 🗣️', $$Too restless to sit still.$$, 'casual'),
('Beat the Clock', 'Phrases & Sayings 🗣️', $$Finish before time runs out.$$, 'casual'),
('Bend Over Backwards', 'Phrases & Sayings 🗣️', $$Try extremely hard to help.$$, 'casual'),
('Between a Rock and a Hard Place', 'Phrases & Sayings 🗣️', $$Two bad choices.$$, 'casual'),
('Blow Off Steam', 'Phrases & Sayings 🗣️', $$Release pent-up frustration.$$, 'casual'),
('Born with a Silver Spoon', 'Phrases & Sayings 🗣️', $$Born into wealth.$$, 'casual'),
('Burn the Candle at Both Ends', 'Phrases & Sayings 🗣️', $$Overwork yourself.$$, 'casual'),
('Chip Off the Old Block', 'Phrases & Sayings 🗣️', $$Just like a parent.$$, 'casual'),
('Cross That Bridge When You Come to It', 'Phrases & Sayings 🗣️', $$Deal with it later.$$, 'casual'),
('Cut Your Losses', 'Phrases & Sayings 🗣️', $$Quit before it gets worse.$$, 'casual'),
('Dig Your Heels In', 'Phrases & Sayings 🗣️', $$Stubbornly refuse to budge.$$, 'casual'),
('Down in the Dumps', 'Phrases & Sayings 🗣️', $$Feeling low.$$, 'casual'),
('Eat Your Words', 'Phrases & Sayings 🗣️', $$Admit you were wrong.$$, 'casual'),
('Get a Taste of Your Own Medicine', 'Phrases & Sayings 🗣️', $$Treated as you treat others.$$, 'casual'),
('Give the Benefit of the Doubt', 'Phrases & Sayings 🗣️', $$Trust despite uncertainty.$$, 'casual'),
('Go Down in Flames', 'Phrases & Sayings 🗣️', $$Fail spectacularly.$$, 'casual'),
('Grasp at Straws', 'Phrases & Sayings 🗣️', $$Try anything in desperation.$$, 'casual'),
-- ── Places & Travel ✈️ ─────────────────────────────────────────────────────
('Jamaica', 'Places & Travel ✈️', $$Reggae and jerk chicken island.$$, 'casual'),
('Fiji', 'Places & Travel ✈️', $$South Pacific island paradise.$$, 'casual'),
('Lake Tahoe', 'Places & Travel ✈️', $$Blue alpine lake, ski country.$$, 'casual'),
('Key West', 'Places & Travel ✈️', $$Southernmost point, Hemingways bar.$$, 'casual'),
('Sedona', 'Places & Travel ✈️', $$Arizona red rocks, vortexes.$$, 'casual'),
('Cancun', 'Places & Travel ✈️', $$Mexican spring-break beaches.$$, 'casual'),
('Punta Cana', 'Places & Travel ✈️', $$Dominican all-inclusive resorts.$$, 'casual'),
('Cabo San Lucas', 'Places & Travel ✈️', $$Baja arch and beaches.$$, 'casual'),
('The Bahamas', 'Places & Travel ✈️', $$Turquoise Caribbean islands.$$, 'casual'),
('Tahiti', 'Places & Travel ✈️', $$Overwater bungalows.$$, 'casual'),
('Seychelles', 'Places & Travel ✈️', $$Indian Ocean granite beaches.$$, 'casual'),
('Mauritius', 'Places & Travel ✈️', $$Once home of the dodo.$$, 'casual'),
('Zanzibar', 'Places & Travel ✈️', $$Spice island off Tanzania.$$, 'casual'),
('Madagascar', 'Places & Travel ✈️', $$Island of lemurs.$$, 'casual'),
('The Rocky Mountains', 'Places & Travel ✈️', $$North Americas spine.$$, 'casual'),
('The Grand Tetons', 'Places & Travel ✈️', $$Jagged Wyoming peaks.$$, 'casual'),
('Zion National Park', 'Places & Travel ✈️', $$Utah canyon of red cliffs.$$, 'casual'),
('Bryce Canyon', 'Places & Travel ✈️', $$Utah hoodoo spires.$$, 'casual'),
('The Everglades', 'Places & Travel ✈️', $$Florida gator wetlands.$$, 'casual'),
('The Outer Banks', 'Places & Travel ✈️', $$North Carolina barrier islands.$$, 'casual'),
('Marthas Vineyard', 'Places & Travel ✈️', $$New England summer island.$$, 'casual'),
('Nantucket', 'Places & Travel ✈️', $$Whaling-era Massachusetts island.$$, 'casual'),
('Savannah', 'Places & Travel ✈️', $$Georgia squares and Spanish moss.$$, 'casual'),
('Charleston', 'Places & Travel ✈️', $$South Carolina antebellum charm.$$, 'casual'),
-- ── Science & Nature 🔬 ────────────────────────────────────────────────────
('Chemistry', 'Science & Nature 🔬', $$The science of substances.$$, 'casual'),
('Camouflage', 'Science & Nature 🔬', $$Blending in to hide.$$, 'casual'),
('Hydrogen', 'Science & Nature 🔬', $$Element number one.$$, 'casual'),
('Magma', 'Science & Nature 🔬', $$Molten rock below the surface.$$, 'casual'),
('Antibiotics', 'Science & Nature 🔬', $$Drugs that kill bacteria.$$, 'casual'),
('Aerodynamics', 'Science & Nature 🔬', $$The study of airflow.$$, 'casual'),
('Amphibians', 'Science & Nature 🔬', $$Frogs, toads, and newts.$$, 'casual'),
('Meteor', 'Science & Nature 🔬', $$A shooting star.$$, 'casual'),
('Biome', 'Science & Nature 🔬', $$A major ecological community.$$, 'casual'),
('Botany', 'Science & Nature 🔬', $$The study of plants.$$, 'casual'),
('Carnivore', 'Science & Nature 🔬', $$Meat eater.$$, 'casual'),
('Cartilage', 'Science & Nature 🔬', $$Flexible tissue in ears and nose.$$, 'casual'),
('Cloning', 'Science & Nature 🔬', $$Making a genetic copy.$$, 'casual'),
('Decomposition', 'Science & Nature 🔬', $$Breaking down of dead matter.$$, 'casual'),
('Digestion', 'Science & Nature 🔬', $$Breaking down food for energy.$$, 'casual'),
('Element', 'Science & Nature 🔬', $$A pure substance on the table.$$, 'casual'),
('Endangered Species', 'Science & Nature 🔬', $$At risk of extinction.$$, 'casual'),
('Fluorescence', 'Science & Nature 🔬', $$Glowing under UV light.$$, 'casual'),
('Fungi', 'Science & Nature 🔬', $$Mushrooms, molds, yeasts.$$, 'casual'),
('Gene Pool', 'Science & Nature 🔬', $$A populations total genes.$$, 'casual'),
('Germination', 'Science & Nature 🔬', $$A seed beginning to grow.$$, 'casual'),
('Gills', 'Science & Nature 🔬', $$How fish breathe underwater.$$, 'casual'),
('Hemoglobin', 'Science & Nature 🔬', $$Oxygen-carrier in blood.$$, 'casual'),
('Larva', 'Science & Nature 🔬', $$A young insects wormy stage.$$, 'casual'),
-- ── Sports 🏆 ──────────────────────────────────────────────────────────────
('Baseline', 'Sports 🏆', $$Back line of the tennis court.$$, 'casual'),
('Hang Time', 'Sports 🏆', $$Seconds airborne on a jump.$$, 'casual'),
('Chip Shot', 'Sports 🏆', $$Short lofted golf approach.$$, 'casual'),
('Jump Ball', 'Sports 🏆', $$Ref tosses it up to start.$$, 'casual'),
('Personal Foul', 'Sports 🏆', $$Illegal contact penalty.$$, 'casual'),
('Backspin', 'Sports 🏆', $$Reverse spin on the ball.$$, 'casual'),
('Ball Screen', 'Sports 🏆', $$Setting a pick on defense.$$, 'casual'),
('Batting Average', 'Sports 🏆', $$Hits divided by at-bats.$$, 'casual'),
('Boxing Ring', 'Sports 🏆', $$Roped square for the bout.$$, 'casual'),
('Breakaway', 'Sports 🏆', $$Racing clear of the defense.$$, 'casual'),
('Bump and Run', 'Sports 🏆', $$Jam the receiver at the line.$$, 'casual'),
('Curl Route', 'Sports 🏆', $$Run upfield then hook back.$$, 'casual'),
('Delay of Game', 'Sports 🏆', $$Penalty for stalling.$$, 'casual'),
('Double Bogey', 'Sports 🏆', $$Two over par on a hole.$$, 'casual'),
('Encroachment', 'Sports 🏆', $$Defender jumps into the neutral zone.$$, 'casual'),
('Fadeaway', 'Sports 🏆', $$Jumper drifting backward.$$, 'casual'),
('Flea Flicker', 'Sports 🏆', $$Handoff then a pitch back to pass.$$, 'casual'),
('Give and Go', 'Sports 🏆', $$Pass then cut for the return.$$, 'casual'),
('Goaltending', 'Sports 🏆', $$Illegally blocking a descending shot.$$, 'casual'),
('Holding', 'Sports 🏆', $$Grabbing a player illegally.$$, 'casual'),
('Icing', 'Sports 🏆', $$Shooting the puck the length of the ice.$$, 'casual'),
('Man to Man', 'Sports 🏆', $$Each defender guards one player.$$, 'casual'),
('Endurance', 'Sports 🏆', $$Stamina to go the distance.$$, 'casual'),
('Down and Out', 'Sports 🏆', $$Sprint upfield then break sideline.$$, 'casual'),
-- ── Tech & Internet 💻 ─────────────────────────────────────────────────────
('Antivirus', 'Tech & Internet 💻', $$Software that catches malware.$$, 'casual'),
('Download', 'Tech & Internet 💻', $$Pull a file to your device.$$, 'casual'),
('Upload', 'Tech & Internet 💻', $$Send a file to the cloud.$$, 'casual'),
('Playlist', 'Tech & Internet 💻', $$A curated queue of songs.$$, 'casual'),
('Desktop', 'Tech & Internet 💻', $$Your computers main screen.$$, 'casual'),
('App Icon', 'Tech & Internet 💻', $$The tappable square on your phone.$$, 'casual'),
('Autofill', 'Tech & Internet 💻', $$Form fields filled for you.$$, 'casual'),
('Bookmark', 'Tech & Internet 💻', $$Saving a page for later.$$, 'casual'),
('Bug Fix', 'Tech & Internet 💻', $$A patch that squashes a glitch.$$, 'casual'),
('Character Limit', 'Tech & Internet 💻', $$Cap on how much you can type.$$, 'casual'),
('Cloud Sync', 'Tech & Internet 💻', $$Keeping devices in step.$$, 'casual'),
('Cursor', 'Tech & Internet 💻', $$The blinking on-screen marker.$$, 'casual'),
('Dashboard', 'Tech & Internet 💻', $$At-a-glance control panel.$$, 'casual'),
('Data Plan', 'Tech & Internet 💻', $$Your monthly cellular allowance.$$, 'casual'),
('Emoji Reaction', 'Tech & Internet 💻', $$Tapping a heart on a message.$$, 'casual'),
('File Format', 'Tech & Internet 💻', $$JPG, PDF, and their kin.$$, 'casual'),
('Firmware', 'Tech & Internet 💻', $$Software baked into a device.$$, 'casual'),
('Folder', 'Tech & Internet 💻', $$Where files are grouped.$$, 'casual'),
('Function Key', 'Tech & Internet 💻', $$The F1-through-F12 row.$$, 'casual'),
('Gif', 'Tech & Internet 💻', $$A looping silent animation.$$, 'casual'),
('Home Button', 'Tech & Internet 💻', $$The old round iPhone key.$$, 'casual'),
('Live Photo', 'Tech & Internet 💻', $$A photo that briefly moves.$$, 'casual'),
('Screensaver', 'Tech & Internet 💻', $$Idle-screen animation.$$, 'casual'),
('Battery Saver', 'Tech & Internet 💻', $$Low-power stretch mode.$$, 'casual'),
-- ── Video Games 🎮 ─────────────────────────────────────────────────────────
('Days Gone', 'Video Games 🎮', $$Biker in a zombie apocalypse.$$, 'casual'),
('Control', 'Video Games 🎮', $$Supernatural agency shooter.$$, 'casual'),
('Duck Hunt', 'Video Games 🎮', $$NES light-gun bird shooting.$$, 'casual'),
('Fruit Ninja', 'Video Games 🎮', $$Slice flying fruit.$$, 'casual'),
('Flappy Bird', 'Video Games 🎮', $$Tap to flap through pipes.$$, 'casual'),
('Ace Combat', 'Video Games 🎮', $$Arcade fighter-jet dogfights.$$, 'casual'),
('Alien Isolation', 'Video Games 🎮', $$Hide from one relentless xenomorph.$$, 'casual'),
('Bastion', 'Video Games 🎮', $$Narrated indie action RPG.$$, 'casual'),
('Bloodstained', 'Video Games 🎮', $$Spiritual heir to Castlevania.$$, 'casual'),
('Bully', 'Video Games 🎮', $$Rockstar boarding-school sandbox.$$, 'casual'),
('Carrion', 'Video Games 🎮', $$Play the escaping monster.$$, 'casual'),
('Catherine', 'Video Games 🎮', $$Block-climbing puzzle nightmares.$$, 'casual'),
('Darksiders', 'Video Games 🎮', $$Horsemen of the Apocalypse action.$$, 'casual'),
('Disco Elysium', 'Video Games 🎮', $$Detective RPG inside your own head.$$, 'casual'),
('Donkey Kong Country', 'Video Games 🎮', $$SNES ape platformer.$$, 'casual'),
('Dota', 'Video Games 🎮', $$Rival MOBA to League.$$, 'casual'),
('Dead by Daylight', 'Video Games 🎮', $$Four survivors flee one killer.$$, 'casual'),
('Enter the Gungeon', 'Video Games 🎮', $$Bullet-hell roguelike.$$, 'casual'),
('Fez', 'Video Games 🎮', $$Rotating 2D-to-3D puzzler.$$, 'casual'),
('Firewatch', 'Video Games 🎮', $$Lonely fire lookout mystery.$$, 'casual'),
('Gauntlet', 'Video Games 🎮', $$Classic four-player dungeon crawl.$$, 'casual'),
('Broforce', 'Video Games 🎮', $$Action-hero pixel run-and-gun.$$, 'casual'),
('Banjo Tooie', 'Video Games 🎮', $$Bear-and-bird N64 sequel.$$, 'casual'),
('Everquest', 'Video Games 🎮', $$Landmark early online RPG.$$, 'casual'),
-- top-up: replaces the 12 phrases that collided, evening every category to 75 casual
('Country Roads', 'Music 🎵', $$John Denver, take me home.$$, 'casual'),
('Brown Eyed Girl', 'Music 🎵', $$Van Morrison, sha la la la.$$, 'casual'),
('Wrangler', 'Brands & Logos 🏷️', $$Rugged American jeans.$$, 'casual'),
('Will Ferrell', 'Famous People 🌟', $$Anchorman, Buddy the Elf.$$, 'casual'),
('French Onion Soup', 'Food & Drink 🍔', $$Broth under melted cheese.$$, 'casual'),
('Groundhog Day', 'Movies & TV 🎬', $$Reliving the same day forever.$$, 'casual'),
('Once Bitten Twice Shy', 'Phrases & Sayings 🗣️', $$Wary after being hurt before.$$, 'casual'),
('Costa Rica', 'Places & Travel ✈️', $$Pura vida, rainforests, volcanoes.$$, 'casual'),
('Skeleton', 'Science & Nature 🔬', $$The bodys bony frame.$$, 'casual'),
('Time Out', 'Sports 🏆', $$Coach stops the clock.$$, 'casual'),
('Airdrop', 'Tech & Internet 💻', $$Apples device-to-device sharing.$$, 'casual'),
('Q Bert', 'Video Games 🎮', $$Arcade hopper on a pyramid.$$, 'casual')
) AS v(phrase, category, clue, pool)
WHERE NOT EXISTS (
  SELECT 1 FROM public.daily_puzzles d WHERE upper(d.phrase) = upper(v.phrase)
);

COMMIT;
