-- supabase-puzzles-seed-expansion.sql
-- Adds 20 new puzzles to each of the 12 categories (240 total).
-- All phrases checked against the existing 720 to avoid duplicates.
-- Schema: daily_puzzles(id uuid default, phrase text, category text, subcategory text default '', clue text)

INSERT INTO public.daily_puzzles (phrase, category, clue) VALUES
-- ===== Books & Characters 📚 =====
('To Kill a Mockingbird', 'Books & Characters 📚', 'Atticus defends the innocent.'),
('The Grapes of Wrath', 'Books & Characters 📚', 'Dust Bowl family migration.'),
('Fahrenheit 451', 'Books & Characters 📚', 'Firemen burn the books.'),
('The Old Man and the Sea', 'Books & Characters 📚', 'Fisherman battles a marlin.'),
('A Wrinkle in Time', 'Books & Characters 📚', 'Kids travel through space.'),
('Charlottes Web', 'Books & Characters 📚', 'Spider saves the pig.'),
('The Color Purple', 'Books & Characters 📚', 'Letters, survival, sisterhood.'),
('Catch Twenty Two', 'Books & Characters 📚', 'No-win military logic.'),
('The Outsiders', 'Books & Characters 📚', 'Greasers versus Socs.'),
('The Fault in Our Stars', 'Books & Characters 📚', 'Teen cancer love story.'),
('Diary of a Wimpy Kid', 'Books & Characters 📚', 'Middle school misadventures.'),
('The Maze Runner', 'Books & Characters 📚', 'Boys trapped in a maze.'),
('Divergent', 'Books & Characters 📚', 'Society split by faction.'),
('Gullivers Travels', 'Books & Characters 📚', 'Tiny people tie him down.'),
('Heidi', 'Books & Characters 📚', 'Orphan in the Alps.'),
('Black Beauty', 'Books & Characters 📚', 'Horse narrates its life.'),
('The Velveteen Rabbit', 'Books & Characters 📚', 'Toy made real by love.'),
('James and the Giant Peach', 'Books & Characters 📚', 'Boy sails inside fruit.'),
('Charlie and the Chocolate Factory', 'Books & Characters 📚', 'Golden ticket factory tour.'),
('The BFG', 'Books & Characters 📚', 'Big friendly dream blower.'),
-- ===== Brands & Logos 🏷️ =====
('Nintendo', 'Brands & Logos 🏷️', 'Marios game maker.'),
('Sony', 'Brands & Logos 🏷️', 'PlayStation parent electronics.'),
('Intel', 'Brands & Logos 🏷️', 'Inside your computer chip.'),
('Nvidia', 'Brands & Logos 🏷️', 'Graphics card giant.'),
('Cartier', 'Brands & Logos 🏷️', 'French luxury jeweler.'),
('Rayban', 'Brands & Logos 🏷️', 'Iconic sunglasses brand.'),
('Lacoste', 'Brands & Logos 🏷️', 'Crocodile polo shirts.'),
('Nestle', 'Brands & Logos 🏷️', 'Swiss food and chocolate.'),
('Kelloggs', 'Brands & Logos 🏷️', 'Breakfast cereal company.'),
('Colgate', 'Brands & Logos 🏷️', 'Toothpaste smile brand.'),
('Gillette', 'Brands & Logos 🏷️', 'The best a man can get.'),
('Duracell', 'Brands & Logos 🏷️', 'Long lasting battery bunny.'),
('FedEx', 'Brands & Logos 🏷️', 'Overnight package delivery.'),
('PayPal', 'Brands & Logos 🏷️', 'Online money transfers.'),
('Hershey', 'Brands & Logos 🏷️', 'American chocolate kisses.'),
('Cadbury', 'Brands & Logos 🏷️', 'Purple British chocolate.'),
('Pizza Hut', 'Brands & Logos 🏷️', 'Red roof pizza chain.'),
('Wendys', 'Brands & Logos 🏷️', 'Square burgers, red pigtails.'),
('Taco Bell', 'Brands & Logos 🏷️', 'Late night taco run.'),
('Chick fil A', 'Brands & Logos 🏷️', 'Chicken, closed Sundays.'),
-- ===== Famous People 🌟 =====
('Brad Pitt', 'Famous People 🌟', 'Fight Club heartthrob actor.'),
('Leonardo DiCaprio', 'Famous People 🌟', 'Sank with the Titanic.'),
('Will Smith', 'Famous People 🌟', 'Fresh Prince turned star.'),
('Robert Downey Jr', 'Famous People 🌟', 'Played Iron Man.'),
('Keanu Reeves', 'Famous People 🌟', 'The Matrix and John Wick.'),
('Dwayne Johnson', 'Famous People 🌟', 'The Rock turned actor.'),
('Adele', 'Famous People 🌟', 'Powerhouse British singer.'),
('Rihanna', 'Famous People 🌟', 'Singer turned beauty mogul.'),
('Drake', 'Famous People 🌟', 'Toronto rapper superstar.'),
('Kanye West', 'Famous People 🌟', 'Controversial rapper, Yeezy.'),
('Madonna', 'Famous People 🌟', 'Queen of Pop reinvention.'),
('David Bowie', 'Famous People 🌟', 'Ziggy Stardust chameleon.'),
('Freddie Mercury', 'Famous People 🌟', 'Queens flamboyant frontman.'),
('Stephen Curry', 'Famous People 🌟', 'Golden State three pointers.'),
('LeBron James', 'Famous People 🌟', 'King James basketball.'),
('Tom Cruise', 'Famous People 🌟', 'Mission Impossible stunts.'),
('Meryl Streep', 'Famous People 🌟', 'Most nominated actress.'),
('Angelina Jolie', 'Famous People 🌟', 'Actress and humanitarian.'),
('Johnny Depp', 'Famous People 🌟', 'Played Jack Sparrow.'),
('Aretha Franklin', 'Famous People 🌟', 'Queen of Soul, Respect.'),
-- ===== Food & Drink 🍔 =====
('Macaron', 'Food & Drink 🍔', 'Colorful French almond cookie.'),
('Croissant', 'Food & Drink 🍔', 'Flaky buttery crescent.'),
('Bruschetta', 'Food & Drink 🍔', 'Toasted bread, tomato topping.'),
('Risotto', 'Food & Drink 🍔', 'Creamy Italian rice.'),
('Paella', 'Food & Drink 🍔', 'Spanish saffron rice.'),
('Gyro', 'Food & Drink 🍔', 'Greek wrap, spit meat.'),
('Tempura', 'Food & Drink 🍔', 'Battered Japanese fry.'),
('Teriyaki', 'Food & Drink 🍔', 'Sweet glazed grilled meat.'),
('Kebab', 'Food & Drink 🍔', 'Skewered grilled meat.'),
('Samosa', 'Food & Drink 🍔', 'Fried spiced triangle.'),
('Pierogi', 'Food & Drink 🍔', 'Polish stuffed dumpling.'),
('Crepe', 'Food & Drink 🍔', 'Thin French pancake.'),
('Cobb Salad', 'Food & Drink 🍔', 'Eggs, bacon, blue cheese.'),
('Fried Rice', 'Food & Drink 🍔', 'Wok tossed leftover rice.'),
('Spring Rolls', 'Food & Drink 🍔', 'Crispy wrapped veggies.'),
('Banana Bread', 'Food & Drink 🍔', 'Sweet loaf, ripe fruit.'),
('Chili', 'Food & Drink 🍔', 'Spicy beef and bean stew.'),
('Meatloaf', 'Food & Drink 🍔', 'Baked ground beef loaf.'),
('Cornbread', 'Food & Drink 🍔', 'Southern golden side.'),
('Root Beer', 'Food & Drink 🍔', 'Sweet sassafras soda.'),
-- ===== Movies & TV 🎬 =====
('Pirates of the Caribbean', 'Movies & TV 🎬', 'Jack Sparrow on the seas.'),
('The Notebook', 'Movies & TV 🎬', 'Rain soaked romance.'),
('Interstellar', 'Movies & TV 🎬', 'Wormhole, space, time.'),
('Django Unchained', 'Movies & TV 🎬', 'Freed bounty hunter.'),
('Gravity', 'Movies & TV 🎬', 'Stranded astronaut survival.'),
('Whiplash', 'Movies & TV 🎬', 'Brutal jazz drumming mentor.'),
('The Revenant', 'Movies & TV 🎬', 'Bear attack frontier revenge.'),
('Joker', 'Movies & TV 🎬', 'A clowns descent.'),
('Dune', 'Movies & TV 🎬', 'Desert planet spice wars.'),
('Oppenheimer', 'Movies & TV 🎬', 'The atomic bomb maker.'),
('Barbie', 'Movies & TV 🎬', 'Pink doll, real world.'),
('Narcos', 'Movies & TV 🎬', 'Colombian cartel drama.'),
('Ozark', 'Movies & TV 🎬', 'Money laundering family.'),
('Succession', 'Movies & TV 🎬', 'Media empire family feud.'),
('Westworld', 'Movies & TV 🎬', 'Robot theme park revolt.'),
('Sherlock', 'Movies & TV 🎬', 'Modern London detective.'),
('Vikings', 'Movies & TV 🎬', 'Norse warrior raids.'),
('Dexter', 'Movies & TV 🎬', 'Serial killer with a code.'),
('Lost', 'Movies & TV 🎬', 'Plane crash mystery island.'),
('Suits', 'Movies & TV 🎬', 'Fake lawyer, big firm.'),
-- ===== Music 🎵 =====
('Sweet Child O Mine', 'Music 🎵', 'Guns N Roses anthem.'),
('Livin on a Prayer', 'Music 🎵', 'Bon Jovi, halfway there.'),
('Dont Stop Believin', 'Music 🎵', 'Journey small town anthem.'),
('I Will Always Love You', 'Music 🎵', 'Whitneys soaring ballad.'),
('My Heart Will Go On', 'Music 🎵', 'Titanic theme song.'),
('Let It Be', 'Music 🎵', 'Beatles words of wisdom.'),
('Hey There Delilah', 'Music 🎵', 'Acoustic long distance love.'),
('Someone Like You', 'Music 🎵', 'Adele piano heartbreak.'),
('Halo', 'Music 🎵', 'Beyonce radiant love.'),
('Poker Face', 'Music 🎵', 'Lady Gaga bluff.'),
('Bad Blood', 'Music 🎵', 'Taylor Swift feud anthem.'),
('Roar', 'Music 🎵', 'Katy Perry tiger.'),
('California Gurls', 'Music 🎵', 'Katy Perry summer hit.'),
('Sugar', 'Music 🎵', 'Maroon 5 wedding crash.'),
('Shallow', 'Music 🎵', 'A Star Is Born duet.'),
('Perfect', 'Music 🎵', 'Ed Sheeran wedding ballad.'),
('Believer', 'Music 🎵', 'Imagine Dragons, pain.'),
('Thunder', 'Music 🎵', 'Imagine Dragons storm.'),
('Lover', 'Music 🎵', 'Taylor Swift slow dance.'),
('Happier', 'Music 🎵', 'Marshmello bittersweet tune.'),
-- ===== Phrases & Sayings 🗣️ =====
('Bite Off More Than You Can Chew', 'Phrases & Sayings 🗣️', 'Take on too much.'),
('A Dime a Dozen', 'Phrases & Sayings 🗣️', 'Very common and cheap.'),
('Beat a Dead Horse', 'Phrases & Sayings 🗣️', 'Pointless repeated effort.'),
('Birds of a Feather', 'Phrases & Sayings 🗣️', 'Similar people flock together.'),
('By the Skin of Your Teeth', 'Phrases & Sayings 🗣️', 'Just barely made it.'),
('Curiosity Killed the Cat', 'Phrases & Sayings 🗣️', 'Nosiness brings trouble.'),
('Every Cloud Has a Silver Lining', 'Phrases & Sayings 🗣️', 'Good within the bad.'),
('Hit the Sack', 'Phrases & Sayings 🗣️', 'Go to bed.'),
('Let Sleeping Dogs Lie', 'Phrases & Sayings 🗣️', 'Dont stir up trouble.'),
('Miss the Boat', 'Phrases & Sayings 🗣️', 'Lose your chance.'),
('On Cloud Nine', 'Phrases & Sayings 🗣️', 'Extremely happy.'),
('Bite the Dust', 'Phrases & Sayings 🗣️', 'Fail or fall.'),
('Cut Corners', 'Phrases & Sayings 🗣️', 'Do it cheaply and poorly.'),
('Hit the Road', 'Phrases & Sayings 🗣️', 'Time to leave.'),
('Burn a Hole in Your Pocket', 'Phrases & Sayings 🗣️', 'Money begging to be spent.'),
('Throw Caution to the Wind', 'Phrases & Sayings 🗣️', 'Take a big risk.'),
('A Storm in a Teacup', 'Phrases & Sayings 🗣️', 'Big fuss, small matter.'),
('The Apple of My Eye', 'Phrases & Sayings 🗣️', 'Cherished favorite person.'),
('Wolf in Sheeps Clothing', 'Phrases & Sayings 🗣️', 'Hidden dangerous person.'),
('You Cant Judge a Book', 'Phrases & Sayings 🗣️', 'Looks can deceive.'),
-- ===== Places & Travel ✈️ =====
('Singapore', 'Places & Travel ✈️', 'Garden city, Marina Bay.'),
('Hong Kong', 'Places & Travel ✈️', 'Skyline harbor metropolis.'),
('Bangkok', 'Places & Travel ✈️', 'Thai temples and street food.'),
('Marrakech', 'Places & Travel ✈️', 'Moroccan market maze.'),
('Cape Town', 'Places & Travel ✈️', 'Table Mountain port city.'),
('Reykjavik', 'Places & Travel ✈️', 'Icelands northern capital.'),
('Prague', 'Places & Travel ✈️', 'Bohemian castle city.'),
('Vienna', 'Places & Travel ✈️', 'Austrian waltz capital.'),
('Dublin', 'Places & Travel ✈️', 'Irish pubs and Guinness.'),
('Edinburgh', 'Places & Travel ✈️', 'Scottish castle on a hill.'),
('Athens', 'Places & Travel ✈️', 'Ancient Greek capital.'),
('Jerusalem', 'Places & Travel ✈️', 'Ancient holy city.'),
('Kyoto', 'Places & Travel ✈️', 'Japans temple old capital.'),
('Seoul', 'Places & Travel ✈️', 'South Koreas K pop hub.'),
('Mumbai', 'Places & Travel ✈️', 'Indias bustling film city.'),
('Mexico City', 'Places & Travel ✈️', 'Aztec capital sprawl.'),
('Buenos Aires', 'Places & Travel ✈️', 'Tango and steak city.'),
('Banff', 'Places & Travel ✈️', 'Canadian Rockies lakes.'),
('The Galapagos', 'Places & Travel ✈️', 'Darwins island species.'),
('Victoria Falls', 'Places & Travel ✈️', 'Africas thundering waterfall.'),
-- ===== Science & Nature 🔬 =====
('DNA Replication', 'Science & Nature 🔬', 'Cells copy genetic code.'),
('Gravitational Waves', 'Science & Nature 🔬', 'Ripples in spacetime.'),
('Condensation', 'Science & Nature 🔬', 'Vapor turns to liquid.'),
('Evaporation', 'Science & Nature 🔬', 'Liquid turns to vapor.'),
('Precipitation', 'Science & Nature 🔬', 'Rain, snow, or hail.'),
('Combustion', 'Science & Nature 🔬', 'Burning chemical reaction.'),
('Electromagnetism', 'Science & Nature 🔬', 'Force of charge and magnet.'),
('Thermodynamics', 'Science & Nature 🔬', 'Study of heat energy.'),
('Buoyancy', 'Science & Nature 🔬', 'Why objects float.'),
('Acceleration', 'Science & Nature 🔬', 'Rate of speed change.'),
('Velocity', 'Science & Nature 🔬', 'Speed with direction.'),
('Momentum', 'Science & Nature 🔬', 'Mass times velocity.'),
('Capillary Action', 'Science & Nature 🔬', 'Water climbs narrow tubes.'),
('Refraction', 'Science & Nature 🔬', 'Light bends through water.'),
('Ecology', 'Science & Nature 🔬', 'Study of living systems.'),
('Biodiversity', 'Science & Nature 🔬', 'Variety of living things.'),
('Hibernation', 'Science & Nature 🔬', 'Animals sleep through winter.'),
('Migration', 'Science & Nature 🔬', 'Seasonal animal travel.'),
('Fossilization', 'Science & Nature 🔬', 'Bones turn to stone.'),
('Geothermal Energy', 'Science & Nature 🔬', 'Heat from the Earth.'),
-- ===== Sports 🏆 =====
('Three Pointer', 'Sports 🏆', 'Long range basketball shot.'),
('Fast Break', 'Sports 🏆', 'Quick basketball counter.'),
('Pick and Roll', 'Sports 🏆', 'Classic basketball play.'),
('Corner Kick', 'Sports 🏆', 'Soccer set piece.'),
('Throw In', 'Sports 🏆', 'Soccer sideline restart.'),
('Own Goal', 'Sports 🏆', 'Scoring on yourself.'),
('Bunt', 'Sports 🏆', 'Soft baseball tap.'),
('Stolen Base', 'Sports 🏆', 'Sprint to the next base.'),
('Curveball', 'Sports 🏆', 'Bending baseball pitch.'),
('Touchback', 'Sports 🏆', 'Football endzone reset.'),
('Two Point Conversion', 'Sports 🏆', 'Football after touchdown.'),
('Onside Kick', 'Sports 🏆', 'Surprise football recovery.'),
('Ace', 'Sports 🏆', 'Unreturnable tennis serve.'),
('Double Fault', 'Sports 🏆', 'Two missed serves.'),
('Love All', 'Sports 🏆', 'Tennis zero score.'),
('Tee Off', 'Sports 🏆', 'Start the golf hole.'),
('Mulligan', 'Sports 🏆', 'Golf do over shot.'),
('Backstroke', 'Sports 🏆', 'Swimming on your back.'),
('Butterfly Stroke', 'Sports 🏆', 'Demanding swim style.'),
('Penalty Box', 'Sports 🏆', 'Hockey timeout for fouls.'),
-- ===== Tech & Internet 💻 =====
('Pop Up Ad', 'Tech & Internet 💻', 'Annoying browser window.'),
('Spyware', 'Tech & Internet 💻', 'Software that snoops.'),
('Malware', 'Tech & Internet 💻', 'Malicious software.'),
('Trojan Horse', 'Tech & Internet 💻', 'Hidden harmful program.'),
('Ransomware', 'Tech & Internet 💻', 'Files held hostage.'),
('Cloud Backup', 'Tech & Internet 💻', 'Offsite data copy.'),
('USB Drive', 'Tech & Internet 💻', 'Pocket file storage.'),
('Hard Drive', 'Tech & Internet 💻', 'Computer storage disk.'),
('Random Access Memory', 'Tech & Internet 💻', 'Short term computer memory.'),
('Graphics Card', 'Tech & Internet 💻', 'Renders the visuals.'),
('Motherboard', 'Tech & Internet 💻', 'Computers main circuit.'),
('Ethernet Cable', 'Tech & Internet 💻', 'Wired internet plug.'),
('Router', 'Tech & Internet 💻', 'Home network hub.'),
('Domain Name', 'Tech & Internet 💻', 'A website address.'),
('Internet of Things', 'Tech & Internet 💻', 'Connected smart devices.'),
('Big Data', 'Tech & Internet 💻', 'Massive data analysis.'),
('Voice Assistant', 'Tech & Internet 💻', 'Hey, talking helper.'),
('QR Code', 'Tech & Internet 💻', 'Scannable square barcode.'),
('Geotagging', 'Tech & Internet 💻', 'Location stamped on posts.'),
('Clickbait', 'Tech & Internet 💻', 'Tempting misleading headline.'),
-- ===== Video Games 🎮 =====
('Splatoon', 'Video Games 🎮', 'Inky Nintendo shooter.'),
('Bloodborne', 'Video Games 🎮', 'Gothic FromSoftware nightmare.'),
('Sekiro', 'Video Games 🎮', 'One armed shinobi.'),
('Ghost of Tsushima', 'Video Games 🎮', 'Samurai open world.'),
('Death Stranding', 'Video Games 🎮', 'Delivery across ruined land.'),
('Horizon Zero Dawn', 'Video Games 🎮', 'Robot dinosaur hunter.'),
('The Elder Scrolls', 'Video Games 🎮', 'Skyrims vast fantasy.'),
('Apex Legends', 'Video Games 🎮', 'Hero battle royale.'),
('Valorant', 'Video Games 🎮', 'Tactical hero shooter.'),
('Genshin Impact', 'Video Games 🎮', 'Anime open world gacha.'),
('Destiny', 'Video Games 🎮', 'Sci fi shooter looter.'),
('Mass Effect', 'Video Games 🎮', 'Space opera RPG.'),
('Dragon Age', 'Video Games 🎮', 'Fantasy party RPG.'),
('Bayonetta', 'Video Games 🎮', 'Witch with hair magic.'),
('Devil May Cry', 'Video Games 🎮', 'Stylish demon hunter.'),
('Ratchet and Clank', 'Video Games 🎮', 'Lombax and robot duo.'),
('Sly Cooper', 'Video Games 🎮', 'Raccoon master thief.'),
('Banjo Kazooie', 'Video Games 🎮', 'Bear and bird platformer.'),
('Earthworm Jim', 'Video Games 🎮', 'Wriggly space hero.'),
('Cut the Rope', 'Video Games 🎮', 'Feed candy to Om Nom.');

-- Verify counts after running:
-- SELECT category, count(*) FROM public.daily_puzzles GROUP BY category ORDER BY category;
