-- ============================================================================
-- Puzzle pool expansion — batch 4: +25 per category (×12 = 300), deduped.
-- Same pattern as batch 3: ~17 daily / 8 casual per category, $$..$$ clue quoting,
-- WHERE NOT EXISTS (case-insensitive) so re-runs are safe and no dupes slip in.
-- Data-only (applied to prod): no binary change, no App Store impact, survives reset.
-- ============================================================================
BEGIN;

INSERT INTO public.daily_puzzles (phrase, category, clue, pool)
SELECT v.phrase, v.category, v.clue, v.pool
FROM (VALUES
-- ── Books & Characters 📚 ──────────────────────────────────────────────────
('A Clockwork Orange', 'Books & Characters 📚', $$Droogs, ultraviolence, Alex.$$, 'daily'),
('The Sun Also Rises', 'Books & Characters 📚', $$Hemingways lost generation.$$, 'daily'),
('A Farewell to Arms', 'Books & Characters 📚', $$Hemingway, WWI, love and war.$$, 'daily'),
('The Metamorphosis', 'Books & Characters 📚', $$Wakes up as a giant bug.$$, 'daily'),
('The Stranger', 'Books & Characters 📚', $$Camus, an absurd killing.$$, 'daily'),
('Heart of Darkness', 'Books & Characters 📚', $$Up the Congo, the horror.$$, 'daily'),
('The Brothers Karamazov', 'Books & Characters 📚', $$Dostoevsky, faith and patricide.$$, 'daily'),
('One Hundred Years of Solitude', 'Books & Characters 📚', $$Macondo and the Buendia family.$$, 'daily'),
('Things Fall Apart', 'Books & Characters 📚', $$Okonkwo, colonial Nigeria.$$, 'daily'),
('The Bourne Identity', 'Books & Characters 📚', $$Amnesiac assassin on the run.$$, 'daily'),
('The Girl with the Dragon Tattoo', 'Books & Characters 📚', $$Lisbeth Salander, Swedish thriller.$$, 'daily'),
('The Pillars of the Earth', 'Books & Characters 📚', $$Building a medieval cathedral.$$, 'daily'),
('Angels and Demons', 'Books & Characters 📚', $$Langdon, the Illuminati, the Vatican.$$, 'daily'),
('The Silmarillion', 'Books & Characters 📚', $$Tolkiens creation myths.$$, 'daily'),
('A Clash of Kings', 'Books & Characters 📚', $$Second book of the Westeros war.$$, 'daily'),
('A Storm of Swords', 'Books & Characters 📚', $$The Red Wedding book.$$, 'daily'),
('The Testaments', 'Books & Characters 📚', $$Sequel to the Gilead handmaids.$$, 'daily'),
('Mistborn', 'Books & Characters 📚', $$Ash falls; magic from metals.$$, 'casual'),
('The Way of Kings', 'Books & Characters 📚', $$Stormlight epic fantasy.$$, 'casual'),
('Foundation', 'Books & Characters 📚', $$Asimov, predicting an empires fall.$$, 'casual'),
('Neuromancer', 'Books & Characters 📚', $$Cyberpunk hacker, coined cyberspace.$$, 'casual'),
('Snow Crash', 'Books & Characters 📚', $$Pizza-delivery samurai, the Metaverse.$$, 'casual'),
('A Wizard of Earthsea', 'Books & Characters 📚', $$Ged learns true names of magic.$$, 'casual'),
('The Name of the Rose', 'Books & Characters 📚', $$Monastery murders, Brother William.$$, 'casual'),
('American Gods', 'Books & Characters 📚', $$Old gods vs new in a road trip.$$, 'casual'),
-- ── Brands & Logos 🏷️ ──────────────────────────────────────────────────────
('Walgreens', 'Brands & Logos 🏷️', $$Corner drugstore chain.$$, 'daily'),
('CVS', 'Brands & Logos 🏷️', $$Pharmacy with mile-long receipts.$$, 'daily'),
('Kroger', 'Brands & Logos 🏷️', $$Big American grocery chain.$$, 'daily'),
('Trader Joes', 'Brands & Logos 🏷️', $$Quirky grocer in Hawaiian shirts.$$, 'daily'),
('Whole Foods', 'Brands & Logos 🏷️', $$Organic grocer, Amazon-owned.$$, 'daily'),
('Aldi', 'Brands & Logos 🏷️', $$No-frills grocer, quarter carts.$$, 'daily'),
('Seven Eleven', 'Brands & Logos 🏷️', $$Slurpees, open all hours.$$, 'daily'),
('Wells Fargo', 'Brands & Logos 🏷️', $$Stagecoach bank.$$, 'daily'),
('Bank of America', 'Brands & Logos 🏷️', $$Red-white-blue flag logo bank.$$, 'daily'),
('Chase', 'Brands & Logos 🏷️', $$Blue octagon bank.$$, 'daily'),
('American Express', 'Brands & Logos 🏷️', $$Dont leave home without it.$$, 'daily'),
('Verizon', 'Brands & Logos 🏷️', $$Red checkmark carrier.$$, 'daily'),
('Comcast', 'Brands & Logos 🏷️', $$Xfinity cable giant.$$, 'daily'),
('Delta', 'Brands & Logos 🏷️', $$Widget-logo airline.$$, 'daily'),
('United Airlines', 'Brands & Logos 🏷️', $$Fly the friendly skies.$$, 'daily'),
('Southwest', 'Brands & Logos 🏷️', $$Bags fly free airline.$$, 'daily'),
('Discover', 'Brands & Logos 🏷️', $$Cashback credit card.$$, 'daily'),
('Marriott', 'Brands & Logos 🏷️', $$Global hotel chain.$$, 'casual'),
('Hilton', 'Brands & Logos 🏷️', $$Classic hotel brand.$$, 'casual'),
('Hyatt', 'Brands & Logos 🏷️', $$Upscale hotel chain.$$, 'casual'),
('Expedia', 'Brands & Logos 🏷️', $$Online trip booking.$$, 'casual'),
('TripAdvisor', 'Brands & Logos 🏷️', $$Owl-logo review site.$$, 'casual'),
('Etsy', 'Brands & Logos 🏷️', $$Handmade and vintage marketplace.$$, 'casual'),
('eBay', 'Brands & Logos 🏷️', $$Online auction pioneer.$$, 'casual'),
('Panera', 'Brands & Logos 🏷️', $$Bakery-cafe, soup in a bread bowl.$$, 'casual'),
-- ── Famous People 🌟 ───────────────────────────────────────────────────────
('Franklin Roosevelt', 'Famous People 🌟', $$New Deal, four terms.$$, 'daily'),
('Ulysses S Grant', 'Famous People 🌟', $$Union general, fifty-dollar bill.$$, 'daily'),
('Andrew Jackson', 'Famous People 🌟', $$Old Hickory, twenty-dollar bill.$$, 'daily'),
('Woodrow Wilson', 'Famous People 🌟', $$WWI president, League of Nations.$$, 'daily'),
('Dwight Eisenhower', 'Famous People 🌟', $$D-Day general turned president.$$, 'daily'),
('Michelangelo', 'Famous People 🌟', $$Sistine ceiling and David.$$, 'daily'),
('Rembrandt', 'Famous People 🌟', $$Dutch master of light and shadow.$$, 'daily'),
('Andy Warhol', 'Famous People 🌟', $$Pop art, soup cans.$$, 'daily'),
('Georgia OKeeffe', 'Famous People 🌟', $$Giant flowers, desert bones.$$, 'daily'),
('Jackson Pollock', 'Famous People 🌟', $$Drip-splatter abstractions.$$, 'daily'),
('Ferdinand Magellan', 'Famous People 🌟', $$First to circumnavigate.$$, 'daily'),
('Vasco da Gama', 'Famous People 🌟', $$Sailed to India round Africa.$$, 'daily'),
('Sir Edmund Hillary', 'Famous People 🌟', $$First atop Everest.$$, 'daily'),
('Ernest Shackleton', 'Famous People 🌟', $$Antarctic survival epic.$$, 'daily'),
('Roald Amundsen', 'Famous People 🌟', $$First to the South Pole.$$, 'daily'),
('Alexander the Great', 'Famous People 🌟', $$Macedonian world conqueror.$$, 'daily'),
('Attila the Hun', 'Famous People 🌟', $$Scourge of Rome.$$, 'daily'),
('Tim Cook', 'Famous People 🌟', $$Apples CEO after Jobs.$$, 'casual'),
('Bill Nye', 'Famous People 🌟', $$The Science Guy.$$, 'casual'),
('Carl Sagan', 'Famous People 🌟', $$Cosmos, billions and billions.$$, 'casual'),
('Richard Feynman', 'Famous People 🌟', $$Playful physicist, bongo drums.$$, 'casual'),
('Ada Lovelace', 'Famous People 🌟', $$First computer programmer.$$, 'casual'),
('Alan Turing', 'Famous People 🌟', $$Cracked Enigma, father of computing.$$, 'casual'),
('Charles Babbage', 'Famous People 🌟', $$Designed the Difference Engine.$$, 'casual'),
('Grace Hopper', 'Famous People 🌟', $$Coined the computer bug.$$, 'casual'),
-- ── Food & Drink 🍔 ────────────────────────────────────────────────────────
('Prime Rib', 'Food & Drink 🍔', $$Standing roast centerpiece.$$, 'daily'),
('Rack of Lamb', 'Food & Drink 🍔', $$Frenched chops in a crown.$$, 'daily'),
('Corn Dog', 'Food & Drink 🍔', $$Battered hot dog on a stick.$$, 'daily'),
('Sloppy Joe', 'Food & Drink 🍔', $$Saucy ground beef on a bun.$$, 'daily'),
('Club Sandwich', 'Food & Drink 🍔', $$Triple-decker with toothpicks.$$, 'daily'),
('Reuben', 'Food & Drink 🍔', $$Corned beef, kraut, rye.$$, 'daily'),
('Philly Cheesesteak', 'Food & Drink 🍔', $$Chopped steak and melted cheese.$$, 'daily'),
('Deviled Eggs', 'Food & Drink 🍔', $$Piped yolk halves.$$, 'daily'),
('Coleslaw', 'Food & Drink 🍔', $$Shredded cabbage side.$$, 'daily'),
('Potato Salad', 'Food & Drink 🍔', $$Picnic mayo spuds.$$, 'daily'),
('Baked Beans', 'Food & Drink 🍔', $$Sweet barbecue side.$$, 'daily'),
('Corn on the Cob', 'Food & Drink 🍔', $$Buttered summer ear.$$, 'daily'),
('Stuffed Peppers', 'Food & Drink 🍔', $$Filled and baked bells.$$, 'daily'),
('Chow Mein', 'Food & Drink 🍔', $$Stir-fried Chinese noodles.$$, 'daily'),
('Egg Roll', 'Food & Drink 🍔', $$Crispy fried wrapper.$$, 'daily'),
('Beef Bourguignon', 'Food & Drink 🍔', $$French red-wine beef stew.$$, 'daily'),
('Chicken Tikka Masala', 'Food & Drink 🍔', $$Creamy spiced curry.$$, 'daily'),
('Sangria', 'Food & Drink 🍔', $$Wine-and-fruit punch.$$, 'casual'),
('Whiskey Sour', 'Food & Drink 🍔', $$Whiskey, lemon, sugar.$$, 'casual'),
('Espresso Martini', 'Food & Drink 🍔', $$Coffee cocktail pick-me-up.$$, 'casual'),
('Hot Toddy', 'Food & Drink 🍔', $$Warm whiskey cold remedy.$$, 'casual'),
('Ginger Ale', 'Food & Drink 🍔', $$Fizzy ginger soda.$$, 'casual'),
('Apple Cider', 'Food & Drink 🍔', $$Autumn pressed apples.$$, 'casual'),
('Eggnog', 'Food & Drink 🍔', $$Creamy holiday drink.$$, 'casual'),
('Sparkling Water', 'Food & Drink 🍔', $$Bubbly and plain.$$, 'casual'),
-- ── Movies & TV 🎬 ─────────────────────────────────────────────────────────
('Good Will Hunting', 'Movies & TV 🎬', $$Janitor math genius, how do you like them apples.$$, 'daily'),
('A Beautiful Mind', 'Movies & TV 🎬', $$Mathematician Nash and his mind.$$, 'daily'),
('The Social Network', 'Movies & TV 🎬', $$Facebooks founding feud.$$, 'daily'),
('Catch Me If You Can', 'Movies & TV 🎬', $$Con-man check forger chase.$$, 'daily'),
('The Wolf of Wall Street', 'Movies & TV 🎬', $$Excess, fraud, sell me this pen.$$, 'daily'),
('The Prestige', 'Movies & TV 🎬', $$Rival magicians obsession.$$, 'daily'),
('Memento', 'Movies & TV 🎬', $$Told backwards, memory tattoos.$$, 'daily'),
('Shutter Island', 'Movies & TV 🎬', $$Detective on an asylum island.$$, 'daily'),
('American Beauty', 'Movies & TV 🎬', $$Look closer, suburban malaise.$$, 'daily'),
('Trainspotting', 'Movies & TV 🎬', $$Choose life, Scottish addicts.$$, 'daily'),
('Slumdog Millionaire', 'Movies & TV 🎬', $$Mumbai quiz-show love story.$$, 'daily'),
('Life Is Beautiful', 'Movies & TV 🎬', $$Father shields son in a camp.$$, 'daily'),
('The Pianist', 'Movies & TV 🎬', $$Survival in the Warsaw Ghetto.$$, 'daily'),
('Amelie', 'Movies & TV 🎬', $$Whimsical Parisian do-gooder.$$, 'daily'),
('Spirited Away', 'Movies & TV 🎬', $$Girl in a spirit bathhouse.$$, 'daily'),
('My Neighbor Totoro', 'Movies & TV 🎬', $$Forest spirit and a cat bus.$$, 'daily'),
('Requiem for a Dream', 'Movies & TV 🎬', $$Harrowing addiction spiral.$$, 'daily'),
('Chernobyl', 'Movies & TV 🎬', $$Nuclear disaster miniseries.$$, 'casual'),
('Band of Brothers', 'Movies & TV 🎬', $$WWII Easy Company.$$, 'casual'),
('True Detective', 'Movies & TV 🎬', $$Time is a flat circle.$$, 'casual'),
('Fargo', 'Movies & TV 🎬', $$Wood-chipper Minnesota crime.$$, 'casual'),
('The Wire', 'Movies & TV 🎬', $$Baltimore drugs and cops.$$, 'casual'),
('Sex and the City', 'Movies & TV 🎬', $$Four friends, Manhattan, Cosmos.$$, 'casual'),
('Gilmore Girls', 'Movies & TV 🎬', $$Fast-talking mother and daughter.$$, 'casual'),
('Downton Abbey', 'Movies & TV 🎬', $$English estate, upstairs and down.$$, 'casual'),
-- ── Music 🎵 ───────────────────────────────────────────────────────────────
('Purple Haze', 'Music 🎵', $$Hendrix, scuse me while I kiss the sky.$$, 'daily'),
('All Along the Watchtower', 'Music 🎵', $$Dylan song, Hendrix cover.$$, 'daily'),
('Layla', 'Music 🎵', $$Clapton, unrequited love.$$, 'daily'),
('Free Bird', 'Music 🎵', $$Skynyrd, play Free Bird!$$, 'daily'),
('More Than a Feeling', 'Music 🎵', $$Boston rock anthem.$$, 'daily'),
('Dont Fear the Reaper', 'Music 🎵', $$Blue Oyster Cult, more cowbell.$$, 'daily'),
('Carry On Wayward Son', 'Music 🎵', $$Kansas rock classic.$$, 'daily'),
('Baba OReilly', 'Music 🎵', $$The Who, teenage wasteland.$$, 'daily'),
('Born in the USA', 'Music 🎵', $$Springsteen, often misread anthem.$$, 'daily'),
('Every Breath You Take', 'Music 🎵', $$The Police, Ill be watching you.$$, 'daily'),
('With or Without You', 'Music 🎵', $$U2 ballad.$$, 'daily'),
('Where the Streets Have No Name', 'Music 🎵', $$U2 soaring opener.$$, 'daily'),
('Zombie', 'Music 🎵', $$The Cranberries protest song.$$, 'daily'),
('Losing My Religion', 'Music 🎵', $$R.E.M., mandolin hit.$$, 'daily'),
('Black Hole Sun', 'Music 🎵', $$Soundgarden, surreal video.$$, 'daily'),
('Dream On', 'Music 🎵', $$Aerosmith power ballad.$$, 'daily'),
('Barracuda', 'Music 🎵', $$Heart rock anthem.$$, 'daily'),
('Creep', 'Music 🎵', $$Radiohead, Im a weirdo.$$, 'casual'),
('Yellow', 'Music 🎵', $$Coldplay, look at the stars.$$, 'casual'),
('Fix You', 'Music 🎵', $$Coldplay, lights will guide you home.$$, 'casual'),
('Chasing Cars', 'Music 🎵', $$Snow Patrol, lay here with me.$$, 'casual'),
('Iris', 'Music 🎵', $$Goo Goo Dolls, who I am.$$, 'casual'),
('The Scientist', 'Music 🎵', $$Coldplay, nobody said it was easy.$$, 'casual'),
('Fast Car', 'Music 🎵', $$Tracy Chapman classic.$$, 'casual'),
('How to Save a Life', 'Music 🎵', $$The Fray hit.$$, 'casual'),
-- ── Phrases & Sayings 🗣️ ───────────────────────────────────────────────────
('A Leopard Cant Change Its Spots', 'Phrases & Sayings 🗣️', $$People dont change their nature.$$, 'daily'),
('All That Glitters Is Not Gold', 'Phrases & Sayings 🗣️', $$Shiny isnt always valuable.$$, 'daily'),
('An Apple a Day', 'Phrases & Sayings 🗣️', $$Keeps the doctor away.$$, 'daily'),
('Beauty Is in the Eye of the Beholder', 'Phrases & Sayings 🗣️', $$Attractiveness is subjective.$$, 'daily'),
('Blood Is Thicker Than Water', 'Phrases & Sayings 🗣️', $$Family comes first.$$, 'daily'),
('Dont Bite the Hand That Feeds You', 'Phrases & Sayings 🗣️', $$Dont harm your benefactor.$$, 'daily'),
('Every Dog Has Its Day', 'Phrases & Sayings 🗣️', $$Everyone gets their moment.$$, 'daily'),
('Fortune Favors the Bold', 'Phrases & Sayings 🗣️', $$Luck rewards the brave.$$, 'daily'),
('Great Minds Think Alike', 'Phrases & Sayings 🗣️', $$We had the same idea.$$, 'daily'),
('Honesty Is the Best Policy', 'Phrases & Sayings 🗣️', $$Truth wins out.$$, 'daily'),
('If It Aint Broke Dont Fix It', 'Phrases & Sayings 🗣️', $$Leave working things alone.$$, 'daily'),
('Look Before You Leap', 'Phrases & Sayings 🗣️', $$Think before acting.$$, 'daily'),
('Money Doesnt Grow on Trees', 'Phrases & Sayings 🗣️', $$Cash is hard to come by.$$, 'daily'),
('Necessity Is the Mother of Invention', 'Phrases & Sayings 🗣️', $$Need drives creativity.$$, 'daily'),
('Practice Makes Perfect', 'Phrases & Sayings 🗣️', $$Repetition builds skill.$$, 'daily'),
('Rome Wasnt Built in a Day', 'Phrases & Sayings 🗣️', $$Big things take time.$$, 'daily'),
('The Squeaky Wheel Gets the Grease', 'Phrases & Sayings 🗣️', $$The loudest gets attention.$$, 'daily'),
('Too Many Cooks Spoil the Broth', 'Phrases & Sayings 🗣️', $$Too much help ruins it.$$, 'casual'),
('Two Wrongs Dont Make a Right', 'Phrases & Sayings 🗣️', $$Revenge fixes nothing.$$, 'casual'),
('When in Rome', 'Phrases & Sayings 🗣️', $$Do as the locals do.$$, 'casual'),
('You Reap What You Sow', 'Phrases & Sayings 🗣️', $$You get what you give.$$, 'casual'),
('A Rolling Stone Gathers No Moss', 'Phrases & Sayings 🗣️', $$Keep moving, stay fresh.$$, 'casual'),
('Absence Makes the Heart Grow Fonder', 'Phrases & Sayings 🗣️', $$Distance deepens love.$$, 'casual'),
('Beauty Is Only Skin Deep', 'Phrases & Sayings 🗣️', $$Looks arent everything.$$, 'casual'),
('The Pen Is Mightier Than the Sword', 'Phrases & Sayings 🗣️', $$Words beat force.$$, 'casual'),
-- ── Places & Travel ✈️ ─────────────────────────────────────────────────────
('Philadelphia', 'Places & Travel ✈️', $$Liberty Bell, cheesesteaks.$$, 'daily'),
('Washington DC', 'Places & Travel ✈️', $$The Capitol and the Mall.$$, 'daily'),
('Denver', 'Places & Travel ✈️', $$Mile High City.$$, 'daily'),
('Austin', 'Places & Travel ✈️', $$Keep it weird, live music.$$, 'daily'),
('Portland', 'Places & Travel ✈️', $$Roses, food carts, Oregon.$$, 'daily'),
('Atlanta', 'Places & Travel ✈️', $$Peaches, the 1996 Olympics.$$, 'daily'),
('San Diego', 'Places & Travel ✈️', $$Zoo, beaches, perfect weather.$$, 'daily'),
('Kuala Lumpur', 'Places & Travel ✈️', $$Petronas Towers.$$, 'daily'),
('Jakarta', 'Places & Travel ✈️', $$Indonesias sprawling capital.$$, 'daily'),
('Manila', 'Places & Travel ✈️', $$The Philippines capital.$$, 'daily'),
('The White House', 'Places & Travel ✈️', $$1600 Pennsylvania Avenue.$$, 'daily'),
('The Sistine Chapel', 'Places & Travel ✈️', $$Michelangelos ceiling.$$, 'daily'),
('The Vatican', 'Places & Travel ✈️', $$The Popes tiny country.$$, 'daily'),
('Central Park', 'Places & Travel ✈️', $$Manhattans green rectangle.$$, 'daily'),
('The Grand Palace', 'Places & Travel ✈️', $$Bangkoks royal complex.$$, 'daily'),
('Table Mountain', 'Places & Travel ✈️', $$Flat-topped Cape Town peak.$$, 'daily'),
('The Matterhorn', 'Places & Travel ✈️', $$Toblerone-shaped Alpine peak.$$, 'daily'),
('Ibiza', 'Places & Travel ✈️', $$Spanish party island.$$, 'casual'),
('Mykonos', 'Places & Travel ✈️', $$Greek island windmills.$$, 'casual'),
('Phuket', 'Places & Travel ✈️', $$Thai beach island.$$, 'casual'),
('Tulum', 'Places & Travel ✈️', $$Mexican Mayan beach ruins.$$, 'casual'),
('Aspen', 'Places & Travel ✈️', $$Colorado ski resort.$$, 'casual'),
('The Amalfi Coast', 'Places & Travel ✈️', $$Italys cliffside seaside.$$, 'casual'),
('The Cliffs of Moher', 'Places & Travel ✈️', $$Irish sea cliffs.$$, 'casual'),
('Lake Como', 'Places & Travel ✈️', $$Italys glamorous lakeside.$$, 'casual'),
-- ── Science & Nature 🔬 ────────────────────────────────────────────────────
('Adaptation', 'Science & Nature 🔬', $$Trait that aids survival.$$, 'daily'),
('Air Pressure', 'Science & Nature 🔬', $$Weight of the atmosphere.$$, 'daily'),
('Alloy', 'Science & Nature 🔬', $$Metal mixture like bronze.$$, 'daily'),
('Aquifer', 'Science & Nature 🔬', $$Underground water-bearing rock.$$, 'daily'),
('Atomic Number', 'Science & Nature 🔬', $$Count of protons.$$, 'daily'),
('Carbon Footprint', 'Science & Nature 🔬', $$Your emissions total.$$, 'daily'),
('Chemical Bond', 'Science & Nature 🔬', $$Force joining atoms.$$, 'daily'),
('Circulatory System', 'Science & Nature 🔬', $$Heart and blood vessels.$$, 'daily'),
('Convection', 'Science & Nature 🔬', $$Heat rising in a fluid.$$, 'daily'),
('Coral Bleaching', 'Science & Nature 🔬', $$Reefs whitening from heat.$$, 'daily'),
('Deforestation', 'Science & Nature 🔬', $$Clearing the worlds forests.$$, 'daily'),
('Desalination', 'Science & Nature 🔬', $$Making seawater drinkable.$$, 'daily'),
('Electric Charge', 'Science & Nature 🔬', $$Positive or negative property.$$, 'daily'),
('Fossil Fuels', 'Science & Nature 🔬', $$Coal, oil, and gas.$$, 'daily'),
('Genome', 'Science & Nature 🔬', $$An organisms full DNA set.$$, 'daily'),
('Hydroelectric', 'Science & Nature 🔬', $$Power from moving water.$$, 'daily'),
('Renewable Energy', 'Science & Nature 🔬', $$Sun, wind, and tides.$$, 'daily'),
('Nervous System', 'Science & Nature 🔬', $$Brain, spine, and nerves.$$, 'casual'),
('Ocean Current', 'Science & Nature 🔬', $$A river within the sea.$$, 'casual'),
('pH Scale', 'Science & Nature 🔬', $$Acid-to-base measure.$$, 'casual'),
('Radioactivity', 'Science & Nature 🔬', $$Unstable atoms decaying.$$, 'casual'),
('Respiration', 'Science & Nature 🔬', $$How cells make energy.$$, 'casual'),
('Solar Panel', 'Science & Nature 🔬', $$Sunlight-to-electricity plate.$$, 'casual'),
('Species', 'Science & Nature 🔬', $$A group that breeds together.$$, 'casual'),
('Water Vapor', 'Science & Nature 🔬', $$Waters gaseous form.$$, 'casual'),
-- ── Sports 🏆 ──────────────────────────────────────────────────────────────
('Balk', 'Sports 🏆', $$Illegal pitcher fake-out.$$, 'daily'),
('Bank Shot', 'Sports 🏆', $$Off the backboard.$$, 'daily'),
('Base on Balls', 'Sports 🏆', $$A walk in baseball.$$, 'daily'),
('Behind the Back', 'Sports 🏆', $$Flashy no-look handle.$$, 'daily'),
('Between the Legs', 'Sports 🏆', $$Dribble through the legs.$$, 'daily'),
('Charge', 'Sports 🏆', $$Offensive foul into a set defender.$$, 'daily'),
('Clean and Jerk', 'Sports 🏆', $$Two-stage Olympic lift.$$, 'daily'),
('Double Play', 'Sports 🏆', $$Two outs on one hit.$$, 'daily'),
('Drop Kick', 'Sports 🏆', $$Bounce-then-boot the ball.$$, 'daily'),
('First Down', 'Sports 🏆', $$A fresh set of downs.$$, 'daily'),
('Full Nelson', 'Sports 🏆', $$Wrestling hold from behind.$$, 'daily'),
('Half Nelson', 'Sports 🏆', $$One-arm wrestling lock.$$, 'daily'),
('Home Stretch', 'Sports 🏆', $$Final straight of the race.$$, 'daily'),
('In the Paint', 'Sports 🏆', $$Inside the key.$$, 'daily'),
('Kickoff', 'Sports 🏆', $$Opening boot of the game.$$, 'daily'),
('Line Drive', 'Sports 🏆', $$Hard, flat batted ball.$$, 'daily'),
('Long Jump', 'Sports 🏆', $$Sprint-and-leap for distance.$$, 'daily'),
('No Look Pass', 'Sports 🏆', $$Dishing without looking.$$, 'casual'),
('Pinch Runner', 'Sports 🏆', $$Substitute speedster on base.$$, 'casual'),
('Play Action', 'Sports 🏆', $$Fake handoff, then pass.$$, 'casual'),
('Safety Blitz', 'Sports 🏆', $$Defensive back rushes the QB.$$, 'casual'),
('Screen Pass', 'Sports 🏆', $$Short toss behind blockers.$$, 'casual'),
('Shot Clock', 'Sports 🏆', $$Countdown to shoot.$$, 'casual'),
('Squeeze Play', 'Sports 🏆', $$Bunt to score the runner.$$, 'casual'),
('Zone Defense', 'Sports 🏆', $$Guard an area, not a man.$$, 'casual'),
-- ── Tech & Internet 💻 ─────────────────────────────────────────────────────
('Adware', 'Tech & Internet 💻', $$Software that spams ads.$$, 'daily'),
('Analog', 'Tech & Internet 💻', $$Non-digital, like a dial clock.$$, 'daily'),
('API', 'Tech & Internet 💻', $$How apps talk to each other.$$, 'daily'),
('Backend', 'Tech & Internet 💻', $$The server-side machinery.$$, 'daily'),
('Beta Test', 'Tech & Internet 💻', $$Trying it before public release.$$, 'daily'),
('Binary Code', 'Tech & Internet 💻', $$Ones and zeros.$$, 'daily'),
('Boot Up', 'Tech & Internet 💻', $$Starting the computer.$$, 'daily'),
('Broadband', 'Tech & Internet 💻', $$High-speed internet.$$, 'daily'),
('Compression', 'Tech & Internet 💻', $$Shrinking a file.$$, 'daily'),
('Cookie Consent', 'Tech & Internet 💻', $$That accept-all banner.$$, 'daily'),
('Data Mining', 'Tech & Internet 💻', $$Digging patterns from data.$$, 'daily'),
('Debug Mode', 'Tech & Internet 💻', $$Hunting for code errors.$$, 'daily'),
('Frontend', 'Tech & Internet 💻', $$The part users see.$$, 'daily'),
('IP Address', 'Tech & Internet 💻', $$Your devices number on the net.$$, 'daily'),
('Kernel', 'Tech & Internet 💻', $$Core of the operating system.$$, 'daily'),
('Metadata', 'Tech & Internet 💻', $$Data about the data.$$, 'daily'),
('Ping', 'Tech & Internet 💻', $$Testing connection latency.$$, 'daily'),
('Plugin', 'Tech & Internet 💻', $$Add-on that extends software.$$, 'casual'),
('Pop Up Blocker', 'Tech & Internet 💻', $$Stops intrusive windows.$$, 'casual'),
('Processor', 'Tech & Internet 💻', $$The chip that does the thinking.$$, 'casual'),
('Query', 'Tech & Internet 💻', $$A request to a database.$$, 'casual'),
('Screen Time', 'Tech & Internet 💻', $$Hours on your phone.$$, 'casual'),
('Sidebar', 'Tech & Internet 💻', $$Vertical menu panel.$$, 'casual'),
('Terabyte', 'Tech & Internet 💻', $$A thousand gigabytes.$$, 'casual'),
('Widget', 'Tech & Internet 💻', $$Mini app on your home screen.$$, 'casual'),
-- ── Video Games 🎮 ─────────────────────────────────────────────────────────
('Alan Wake', 'Video Games 🎮', $$Writer battles darkness with light.$$, 'daily'),
('Astro Bot', 'Video Games 🎮', $$PlayStation mascot platformer.$$, 'daily'),
('Battletoads', 'Video Games 🎮', $$Brutal beat-em-up amphibians.$$, 'daily'),
('Bomberman', 'Video Games 🎮', $$Grid maze, exploding bombs.$$, 'daily'),
('Braid', 'Video Games 🎮', $$Time-bending indie platformer.$$, 'daily'),
('Bubble Bobble', 'Video Games 🎮', $$Dragons trapping foes in bubbles.$$, 'daily'),
('Burnout', 'Video Games 🎮', $$Crash-happy arcade racer.$$, 'daily'),
('Chrono Trigger', 'Video Games 🎮', $$Time-travel SNES RPG.$$, 'daily'),
('Command and Conquer', 'Video Games 🎮', $$Real-time war strategy.$$, 'daily'),
('Dead Space', 'Video Games 🎮', $$Dismember space horrors.$$, 'daily'),
('Dig Dug', 'Video Games 🎮', $$Inflate underground monsters.$$, 'daily'),
('Dragon Quest', 'Video Games 🎮', $$Classic Japanese RPG series.$$, 'daily'),
('Fallout', 'Video Games 🎮', $$Post-nuclear wasteland RPG.$$, 'daily'),
('Forza', 'Video Games 🎮', $$Xbox racing sim.$$, 'daily'),
('Gears of War', 'Video Games 🎮', $$Chainsaw-gun cover shooter.$$, 'daily'),
('Golden Eye', 'Video Games 🎮', $$N64 Bond shooter classic.$$, 'daily'),
('Guild Wars', 'Video Games 🎮', $$Online fantasy MMO.$$, 'daily'),
('Hitman', 'Video Games 🎮', $$Bald bar-coded Agent 47.$$, 'casual'),
('Jak and Daxter', 'Video Games 🎮', $$Platforming duo on PS2.$$, 'casual'),
('Just Cause', 'Video Games 🎮', $$Grappling-hook chaos sandbox.$$, 'casual'),
('Kirby', 'Video Games 🎮', $$Pink puffball who inhales foes.$$, 'casual'),
('Max Payne', 'Video Games 🎮', $$Bullet-time noir shooter.$$, 'casual'),
('Myst', 'Video Games 🎮', $$Surreal island puzzle adventure.$$, 'casual'),
('Need for Speed', 'Video Games 🎮', $$Street-racing series.$$, 'casual'),
('Paper Mario', 'Video Games 🎮', $$Flat papercraft Mario RPG.$$, 'casual')
) AS v(phrase, category, clue, pool)
WHERE NOT EXISTS (
  SELECT 1 FROM public.daily_puzzles d WHERE upper(d.phrase) = upper(v.phrase)
);

COMMIT;
