-- ╔══════════════════════════════════════════════════════════════════════════╗
-- ║  Play Log read side — history list, 1v1 head-to-head, challenge detail      ║
-- ║  (migration: play_log_v2_read_rpcs — applied via MCP)                       ║
-- ╚══════════════════════════════════════════════════════════════════════════╝
-- Powers the /history page. Reads the enriched game_results (see supabase-play-log-v2.sql).
--
-- get_history(p_mode, p_result, p_category, p_opponent, p_group, p_since, p_until,
--             p_sort, p_limit, p_offset) → TABLE
--   Self-only (auth.uid()). Stackable filters; sort recent|net|multiple|fastest;
--   offset pagination (limit capped 100). Joins daily_puzzles for puzzle_phrase
--   (re-see the answer) + groups for group_name + _display_name for opponent_name.
--   Client wrapper: getHistory(filters) in statsStore.js.
--
-- get_head_to_head(p_opponent) → jsonb { opponent_id, opponent_name, wins, losses,
--   ties, total, last5:[{outcome,played_at,net}] } over game_mode='challenge' rows
--   where opponent_id = p_opponent. No new table — pure query over the Play Log.
--   Client: getHeadToHead(opponentId).
--
-- get_match_detail(p_match_id) → jsonb { match{...,budget}, group_name, participants[
--   {user_id,name,is_me,solved,score,spent,state,rank} ordered by score], pack[
--   {position,category,phrase}] }. Participants-only (returns NULL otherwise).
--   spent = GREATEST(0, budget − bankroll), budget = max(wager,500) (matches get_match).
--   Spoiler-safe: pack phrases are NULL until the match status='settled'.
--   Client: getMatchDetail(matchId) → shared MatchDetailModal.svelte, opened from a
--   challenge row in /history AND the challenge inbox "Results" button.
--   (migrations: match_detail_add_spent, fix_match_detail_window_in_agg — the latter
--    moves rank() into a subquery; window fns can't nest inside jsonb_agg, a runtime bug.)
--
-- All three GRANT EXECUTE TO authenticated. Full bodies applied via MCP; see git
-- history / live definitions. Verified: get_history returns rows under jwt-impersonation.
--
-- get_public_profile(p_username) → jsonb — another player's public stats (net_worth,
--   streaks, games, puzzles_solved, climb_position, challenge_wins, avg/best multiple,
--   badges, title/color) + the VIEWER's head_to_head vs them + relationship flags
--   (is_self, is_friend, request_outgoing/incoming). Resolves username case-insensitively;
--   NULL if not found. Calls get_head_to_head(target) internally (auth.uid() = viewer).
--   (migration get_public_profile.) Client: getPublicProfile(username) → /u/[username] page.
--   Friendships live in friendships(user_id, friend_id); pending in friend_requests(requester, addressee).
--
-- get_group_standings(p_group_id) → jsonb { total_matches, members[{user_id,name,is_me,
--   played,wins,win_pct} ordered by wins desc], recent[{match_id,pack_size,wager,players,
--   winner} last 8 settled] }. Members-only (NULL otherwise). "win" = top total_score in a
--   settled group challenge_matches (topscore>0). (migration get_group_standings.)
--   Client: getGroupStandings(groupId) → /groups "Compete" tab.
--
-- get_activity_feed(p_limit, p_offset) → TABLE(ts, type, actor_id, actor_name, group_id,
--   group_name, meta jsonb). Read-only UNION over game_results (daily wins, challenge WINS
--   [winner-centric → 1 row/match], climb solves ≥4×), user_badges(earned_at), and
--   group_members(joined_at), scoped to viewer + friends + their groups. No events table,
--   no write hooks. (migration get_activity_feed.) Client: getActivityFeed → /activity page.
--
-- STATS/HISTORY SYSTEM COMPLETE (design §8 steps 1–6). Remaining/deferred: competitive
--   spent/earned/net (matches rank by total_score, not the v3.1 pot-of-spend model).
