-- ============================================================
-- WordBank puzzle seed — 60 per category × 12 categories = 720
-- (round 1 = first 20 each; rounds 2 and 3 = +20 each, appended at the end).
-- Clues are deliberately SHORT (3–6 words) and oblique: a nudge, not a
-- description (the old 11–13 word clues gave the answer away).
-- Phrases are letters + single spaces only (the board has no punctuation/digits).
--
-- ⚠️ Full reset: clears the daily schedule + in-progress sessions/runs first
-- (they reference daily_puzzles with ON DELETE RESTRICT), then reseeds.
-- ============================================================

DELETE FROM public.daily_puzzle_schedule;
DELETE FROM public.daily_sessions;
DELETE FROM public.arcade_runs;
DELETE FROM public.freeplay_sessions;   -- CASCADEs anyway, explicit for clarity
DELETE FROM public.daily_puzzles;

INSERT INTO public.daily_puzzles (phrase, category, clue) VALUES
-- ===== Movies & TV 🎬 =====
('Star Wars',            'Movies & TV 🎬', $$Space wizards, laser swords.$$),
('The Godfather',        'Movies & TV 🎬', $$An offer, a horse head.$$),
('Breaking Bad',         'Movies & TV 🎬', $$Chemistry teacher turns kingpin.$$),
('Jurassic Park',        'Movies & TV 🎬', $$Cloned dinosaurs, bad idea.$$),
('Forrest Gump',         'Movies & TV 🎬', $$Running man, box of chocolates.$$),
('The Lion King',        'Movies & TV 🎬', $$Cub exile, royal comeback.$$),
('Stranger Things',      'Movies & TV 🎬', $$Upside-down kids, one monster.$$),
('The Matrix',           'Movies & TV 🎬', $$Red pill, bullet time.$$),
('Game of Thrones',      'Movies & TV 🎬', $$Iron chair, frequent funerals.$$),
('Pulp Fiction',         'Movies & TV 🎬', $$Briefcase, dance, diner robbery.$$),
('The Office',           'Movies & TV 🎬', $$Paper company, cringing boss.$$),
('Titanic',              'Movies & TV 🎬', $$Big boat, small door.$$),
('Toy Story',            'Movies & TV 🎬', $$Toys move when alone.$$),
('Friends',              'Movies & TV 🎬', $$Coffee shop, six roommates.$$),
('The Dark Knight',      'Movies & TV 🎬', $$Clown versus caped vigilante.$$),
('Back to the Future',   'Movies & TV 🎬', $$Time-traveling sports car.$$),
('Inception',            'Movies & TV 🎬', $$Dream inside a dream.$$),
('Avatar',               'Movies & TV 🎬', $$Blue aliens, glowing forest.$$),
('The Simpsons',         'Movies & TV 🎬', $$Yellow family, donut dad.$$),
('Jaws',                 'Movies & TV 🎬', $$Bigger boat needed.$$),

-- ===== Music 🎵 =====
('Bohemian Rhapsody',    'Music 🎵', $$Opera meets headbang.$$),
('Thriller',             'Music 🎵', $$Zombie dance, red jacket.$$),
('The Beatles',          'Music 🎵', $$Liverpool four, Abbey Road.$$),
('Taylor Swift',         'Music 🎵', $$Breakups become stadium tours.$$),
('Billie Jean',          'Music 🎵', $$Lit sidewalk, denied paternity.$$),
('November Rain',        'Music 🎵', $$Long ballad, longer solo.$$),
('Hotel California',     'Music 🎵', $$Lovely place, no checkout.$$),
('Rolling Stones',       'Music 🎵', $$Tongue logo, no satisfaction.$$),
('Smells Like Teen Spirit','Music 🎵', $$Grunge anthem, mumbled chorus.$$),
('Bad Romance',          'Music 🎵', $$Gaga wants your love.$$),
('Stairway to Heaven',   'Music 🎵', $$Buying a cloud ladder.$$),
('Old Town Road',        'Music 🎵', $$Country trap, horses out back.$$),
('Imagine',              'Music 🎵', $$Lennon dreams, no heaven.$$),
('Purple Rain',          'Music 🎵', $$Prince weeps in violet.$$),
('Rolling in the Deep',  'Music 🎵', $$Adele, scorched-earth breakup.$$),
('Sweet Caroline',       'Music 🎵', $$Crowd shouts ba ba ba.$$),
('Lose Yourself',        'Music 🎵', $$One shot, mom spaghetti.$$),
('Despacito',            'Music 🎵', $$Slow Spanish summer smash.$$),
('Dancing Queen',        'Music 🎵', $$Seventeen, tambourine, Swedish disco.$$),
('Uptown Funk',          'Music 🎵', $$Too hot, call somebody.$$),

-- ===== Famous People 🌟 =====
('Albert Einstein',      'Famous People 🌟', $$Wild hair, wilder equations.$$),
('Oprah Winfrey',        'Famous People 🌟', $$You get a car!$$),
('Elon Musk',            'Famous People 🌟', $$Rockets, tweets, electric cars.$$),
('Lady Gaga',            'Famous People 🌟', $$Meat dress, piano pop.$$),
('Michael Jackson',      'Famous People 🌟', $$Moonwalk, single glove.$$),
('Beyonce',              'Famous People 🌟', $$Houston queen, flawless reign.$$),
('Abraham Lincoln',      'Famous People 🌟', $$Tall hat, mended nation.$$),
('Cleopatra',            'Famous People 🌟', $$Egypt last pharaoh, Roman flings.$$),
('William Shakespeare',  'Famous People 🌟', $$Bard of doomed lovers.$$),
('Steve Jobs',           'Famous People 🌟', $$Black turtleneck, bitten apple.$$),
('Marilyn Monroe',       'Famous People 🌟', $$White dress over a vent.$$),
('Nelson Mandela',       'Famous People 🌟', $$Prisoner turned president.$$),
('Leonardo da Vinci',    'Famous People 🌟', $$Painter who sketched helicopters.$$),
('Muhammad Ali',         'Famous People 🌟', $$Float, sting, loud mouth.$$),
('Princess Diana',       'Famous People 🌟', $$People princess, paparazzi chase.$$),
('Mahatma Gandhi',       'Famous People 🌟', $$Spinning wheel, salt march.$$),
('Walt Disney',          'Famous People 🌟', $$Mouse mogul, frozen rumor.$$),
('Kim Kardashian',       'Famous People 🌟', $$Famous for being famous.$$),
('Vincent van Gogh',     'Famous People 🌟', $$Starry nights, one ear.$$),
('Barack Obama',         'Famous People 🌟', $$Hope posters, yes we can.$$),

-- ===== Food & Drink 🍔 =====
('Chicken Parmesan',     'Food & Drink 🍔', $$Breaded cutlet, melted mozzarella.$$),
('Pizza',                'Food & Drink 🍔', $$Round, sliced, pineapple debated.$$),
('Sushi',                'Food & Drink 🍔', $$Raw fish, vinegared rice.$$),
('Tacos',                'Food & Drink 🍔', $$Tuesday folded handful.$$),
('Hamburger',            'Food & Drink 🍔', $$Patty between two buns.$$),
('Ice Cream',            'Food & Drink 🍔', $$Cold scoop, summer drip.$$),
('Spaghetti',            'Food & Drink 🍔', $$Twirled strings, red sauce.$$),
('Pancakes',             'Food & Drink 🍔', $$Stacked, syrup-flooded mornings.$$),
('Guacamole',            'Food & Drink 🍔', $$Mashed green, costs extra.$$),
('Coffee',               'Food & Drink 🍔', $$Bitter morning lifeline.$$),
('French Fries',         'Food & Drink 🍔', $$Golden salted sticks.$$),
('Hot Dog',              'Food & Drink 🍔', $$Bun, mystery meat, ballpark.$$),
('Macaroni and Cheese',  'Food & Drink 🍔', $$Orange noodle comfort.$$),
('Pad Thai',             'Food & Drink 🍔', $$Stir-fried noodles, peanut dust.$$),
('Chocolate',            'Food & Drink 🍔', $$Melts in mouth, allegedly.$$),
('Pumpkin Spice',        'Food & Drink 🍔', $$Autumn in a cup.$$),
('Margarita',            'Food & Drink 🍔', $$Salt rim, lime, regret.$$),
('Ramen',                'Food & Drink 🍔', $$Broth, noodles, dorm survival.$$),
('Bacon',                'Food & Drink 🍔', $$Sizzling breakfast vice.$$),
('Avocado Toast',        'Food & Drink 🍔', $$Millennial pricey breakfast.$$),

-- ===== Places & Travel ✈️ =====
('The Eiffel Tower',     'Places & Travel ✈️', $$Iron giant over Paris.$$),
('Grand Canyon',         'Places & Travel ✈️', $$Big colorful hole, Arizona.$$),
('Mount Everest',        'Places & Travel ✈️', $$Highest, deadliest selfie spot.$$),
('Great Wall of China',  'Places & Travel ✈️', $$Very long ancient barrier.$$),
('Statue of Liberty',    'Places & Travel ✈️', $$Green lady, raised torch.$$),
('Times Square',         'Places & Travel ✈️', $$Neon, crowds, dropping ball.$$),
('Niagara Falls',        'Places & Travel ✈️', $$Honeymoon roaring water.$$),
('Las Vegas',            'Places & Travel ✈️', $$Sin city, neon desert.$$),
('Big Ben',              'Places & Travel ✈️', $$London chiming clock tower.$$),
('The Colosseum',        'Places & Travel ✈️', $$Roman arena, lion seating.$$),
('Mount Rushmore',       'Places & Travel ✈️', $$Four presidents in rock.$$),
('Santorini',            'Places & Travel ✈️', $$Blue domes, white cliffs.$$),
('The Pyramids',         'Places & Travel ✈️', $$Pharaoh tombs, desert triangles.$$),
('Hollywood',            'Places & Travel ✈️', $$Hillside sign, broken dreams.$$),
('Venice',               'Places & Travel ✈️', $$Sinking city, canal taxis.$$),
('Machu Picchu',         'Places & Travel ✈️', $$Lost Inca mountain city.$$),
('Sydney Opera House',   'Places & Travel ✈️', $$Sailboat roof down under.$$),
('The Sahara',           'Places & Travel ✈️', $$Endless sand, no shortcuts.$$),
('Bora Bora',            'Places & Travel ✈️', $$Overwater bungalow fantasy.$$),
('Tokyo',                'Places & Travel ✈️', $$Neon megacity, bullet trains.$$),

-- ===== Sports 🏆 =====
('Hail Mary',            'Sports 🏆', $$Desperate last-second heave.$$),
('Super Bowl',           'Sports 🏆', $$Football ad-filled finale.$$),
('Slam Dunk',            'Sports 🏆', $$Gravity-defying basket.$$),
('Home Run',             'Sports 🏆', $$Ball over the fence.$$),
('Grand Slam',           'Sports 🏆', $$Bases loaded, then gone.$$),
('The Olympics',         'Sports 🏆', $$Five rings, every fourth year.$$),
('Hat Trick',            'Sports 🏆', $$Three goals, one player.$$),
('World Cup',            'Sports 🏆', $$Global soccer obsession.$$),
('Knockout',             'Sports 🏆', $$Lights out, count ten.$$),
('Penalty Kick',         'Sports 🏆', $$One shot, one keeper.$$),
('Triple Double',        'Sports 🏆', $$Tens across three stats.$$),
('Touchdown',            'Sports 🏆', $$Six points, end zone.$$),
('Checkmate',            'Sports 🏆', $$King trapped, game over.$$),
('Photo Finish',         'Sports 🏆', $$Camera decides the winner.$$),
('March Madness',        'Sports 🏆', $$Bracket-busting hoops chaos.$$),
('Heisman Trophy',       'Sports 🏆', $$Stiff-arm pose, college honor.$$),
('Stanley Cup',          'Sports 🏆', $$Hockey dented silver chalice.$$),
('Tour de France',       'Sports 🏆', $$Yellow jersey, mountain suffering.$$),
('The Masters',          'Sports 🏆', $$Green jacket, Augusta greens.$$),
('Buzzer Beater',        'Sports 🏆', $$Shot at zero seconds.$$),

-- ===== Phrases & Sayings 🗣️ =====
('Bite the Bullet',      'Phrases & Sayings 🗣️', $$Endure the painful thing.$$),
('Break the Ice',        'Phrases & Sayings 🗣️', $$Ease first awkwardness.$$),
('Piece of Cake',        'Phrases & Sayings 🗣️', $$Absurdly easy task.$$),
('Cold Feet',            'Phrases & Sayings 🗣️', $$Last-minute wedding panic.$$),
('Spill the Beans',      'Phrases & Sayings 🗣️', $$Leak the secret.$$),
('Couch Potato',         'Phrases & Sayings 🗣️', $$Sofa-dwelling channel surfer.$$),
('Hit the Hay',          'Phrases & Sayings 🗣️', $$Off to sleep.$$),
('Under the Weather',    'Phrases & Sayings 🗣️', $$Feeling a bit sick.$$),
('Once in a Blue Moon',  'Phrases & Sayings 🗣️', $$Almost never happens.$$),
('Burning the Midnight Oil','Phrases & Sayings 🗣️', $$Working absurdly late.$$),
('Raining Cats and Dogs','Phrases & Sayings 🗣️', $$Absolute downpour.$$),
('Bull in a China Shop', 'Phrases & Sayings 🗣️', $$Clumsy among delicate things.$$),
('Kill Two Birds',       'Phrases & Sayings 🗣️', $$One stone, two wins.$$),
('Barking up the Wrong Tree','Phrases & Sayings 🗣️', $$Chasing the wrong lead.$$),
('The Ball Is in Your Court','Phrases & Sayings 🗣️', $$Your move now.$$),
('Caught Red Handed',    'Phrases & Sayings 🗣️', $$Busted mid-crime.$$),
('Let the Cat Out of the Bag','Phrases & Sayings 🗣️', $$Reveal the surprise.$$),
('Best of Both Worlds',  'Phrases & Sayings 🗣️', $$Win without trade-offs.$$),
('Speak of the Devil',   'Phrases & Sayings 🗣️', $$They just appeared.$$),
('Cut to the Chase',     'Phrases & Sayings 🗣️', $$Skip to the point.$$),

-- ===== Science & Nature 🔬 =====
('The Solar System',     'Science & Nature 🔬', $$One star, eight planets.$$),
('Black Hole',           'Science & Nature 🔬', $$Light point of no return.$$),
('Photosynthesis',       'Science & Nature 🔬', $$Plants eating sunlight.$$),
('Big Bang',             'Science & Nature 🔬', $$Everything loud beginning.$$),
('Gravity',              'Science & Nature 🔬', $$Why apples fall down.$$),
('Double Helix',         'Science & Nature 🔬', $$Twisted ladder of life.$$),
('Evolution',            'Science & Nature 🔬', $$Survival rewrites the species.$$),
('The Northern Lights',  'Science & Nature 🔬', $$Sky green curtain.$$),
('Tectonic Plates',      'Science & Nature 🔬', $$Earth shifting puzzle pieces.$$),
('Volcano',              'Science & Nature 🔬', $$Mountain that spits fire.$$),
('Periodic Table',       'Science & Nature 🔬', $$Elements in tidy boxes.$$),
('Lightning',            'Science & Nature 🔬', $$Sky electric crack.$$),
('The Water Cycle',      'Science & Nature 🔬', $$Rain endless commute.$$),
('Quantum Physics',      'Science & Nature 🔬', $$Tiny things, big headaches.$$),
('Coral Reef',           'Science & Nature 🔬', $$Underwater rainbow city.$$),
('Hurricane',            'Science & Nature 🔬', $$Spinning ocean fury.$$),
('Speed of Light',       'Science & Nature 🔬', $$Universe hard limit.$$),
('Natural Selection',    'Science & Nature 🔬', $$Nature picks the fittest.$$),
('The Food Chain',       'Science & Nature 🔬', $$Who eats whom.$$),
('Solar Eclipse',        'Science & Nature 🔬', $$Moon photobombs the sun.$$),

-- ===== Books & Characters 📚 =====
('Sherlock Holmes',      'Books & Characters 📚', $$Pipe, violin, smug deductions.$$),
('Harry Potter',         'Books & Characters 📚', $$Lightning scar, boy wizard.$$),
('Romeo and Juliet',     'Books & Characters 📚', $$Teen lovers, terrible plan.$$),
('Moby Dick',            'Books & Characters 📚', $$Captain, white whale obsession.$$),
('Pride and Prejudice',  'Books & Characters 📚', $$Mr Darcy slow thaw.$$),
('The Great Gatsby',     'Books & Characters 📚', $$Green light, doomed parties.$$),
('Frankenstein',         'Books & Characters 📚', $$Doctor regrettable creation.$$),
('Alice in Wonderland',  'Books & Characters 📚', $$Rabbit hole, mad tea.$$),
('The Hobbit',           'Books & Characters 📚', $$Reluctant burglar, dragon gold.$$),
('Dracula',              'Books & Characters 📚', $$Transylvanian neck enthusiast.$$),
('Peter Pan',            'Books & Characters 📚', $$Boy refusing to grow.$$),
('The Cat in the Hat',   'Books & Characters 📚', $$Chaos in striped headwear.$$),
('Winnie the Pooh',      'Books & Characters 📚', $$Honey-obsessed stuffed bear.$$),
('Lord of the Flies',    'Books & Characters 📚', $$Schoolboys, island, savagery.$$),
('The Hunger Games',     'Books & Characters 📚', $$Televised teen deathmatch.$$),
('Don Quixote',          'Books & Characters 📚', $$Old knight fights windmills.$$),
('Little Women',         'Books & Characters 📚', $$Four sisters, wartime growing.$$),
('Huckleberry Finn',     'Books & Characters 📚', $$Raft kid, big river.$$),
('Tom Sawyer',           'Books & Characters 📚', $$Fence-painting con artist.$$),
('The Odyssey',          'Books & Characters 📚', $$Ten-year voyage home.$$),

-- ===== Video Games 🎮 =====
('Donkey Kong',          'Video Games 🎮', $$Barrel-throwing ape, trapped girl.$$),
('Super Mario',          'Video Games 🎮', $$Plumber, mushrooms, princess rescue.$$),
('The Legend of Zelda',  'Video Games 🎮', $$Green elf, master sword.$$),
('Minecraft',            'Video Games 🎮', $$Blocky world, creepers explode.$$),
('Pac Man',              'Video Games 🎮', $$Pellet muncher, ghost dodger.$$),
('Tetris',               'Video Games 🎮', $$Falling blocks, no breaks.$$),
('Fortnite',             'Video Games 🎮', $$Last standing, dance emotes.$$),
('Sonic the Hedgehog',   'Video Games 🎮', $$Blue blur, gold rings.$$),
('Pokemon',              'Video Games 🎮', $$Gotta catch them all.$$),
('Grand Theft Auto',     'Video Games 🎮', $$Crime sandbox mayhem.$$),
('Space Invaders',       'Video Games 🎮', $$Descending pixel aliens.$$),
('Call of Duty',         'Video Games 🎮', $$Military shooter, loud lobbies.$$),
('Street Fighter',       'Video Games 🎮', $$Fireball, arcade brawls.$$),
('Angry Birds',          'Video Games 🎮', $$Slingshot vengeance on pigs.$$),
('Final Fantasy',        'Video Games 🎮', $$Spiky hair, endless sequels.$$),
('Candy Crush',          'Video Games 🎮', $$Matching sweets, sneaky charges.$$),
('World of Warcraft',    'Video Games 🎮', $$Orcs, raids, lost weekends.$$),
('Mortal Kombat',        'Video Games 🎮', $$Spine-ripping finishers.$$),
('Among Us',             'Video Games 🎮', $$Spaceship trust issues.$$),
('Halo',                 'Video Games 🎮', $$Green armor, alien war.$$),

-- ===== Brands & Logos 🏷️ =====
('Coca Cola',            'Brands & Logos 🏷️', $$Secret formula, red can.$$),
('Nike',                 'Brands & Logos 🏷️', $$Swoosh, just do it.$$),
('Apple',                'Brands & Logos 🏷️', $$Bitten fruit, pricey gadgets.$$),
('McDonalds',            'Brands & Logos 🏷️', $$Golden arches, clown mascot.$$),
('Google',               'Brands & Logos 🏷️', $$Verb for searching.$$),
('Starbucks',            'Brands & Logos 🏷️', $$Green siren, misspelled cups.$$),
('Amazon',               'Brands & Logos 🏷️', $$Smiling arrow, doorstep boxes.$$),
('Netflix',              'Brands & Logos 🏷️', $$Red N, chill euphemism.$$),
('Disney',               'Brands & Logos 🏷️', $$Mouse ears, castle logo.$$),
('Tesla',                'Brands & Logos 🏷️', $$Electric cars, eccentric boss.$$),
('Lego',                 'Brands & Logos 🏷️', $$Plastic bricks, barefoot menace.$$),
('Ferrari',              'Brands & Logos 🏷️', $$Prancing horse, red speed.$$),
('Rolex',                'Brands & Logos 🏷️', $$Crown logo, wrist flex.$$),
('Adidas',               'Brands & Logos 🏷️', $$Three stripes rival.$$),
('Spotify',              'Brands & Logos 🏷️', $$Green circle, shuffled playlists.$$),
('Lays',                 'Brands & Logos 🏷️', $$Cannot eat just one.$$),
('Gucci',                'Brands & Logos 🏷️', $$Double G, loud luxury.$$),
('Red Bull',             'Brands & Logos 🏷️', $$Wings in a can.$$),
('Ikea',                 'Brands & Logos 🏷️', $$Flat-pack, allen-wrench tears.$$),
('Pringles',             'Brands & Logos 🏷️', $$Mustached man, stackable chips.$$),

-- ===== Tech & Internet 💻 =====
('Artificial Intelligence','Tech & Internet 💻', $$Machines that improvise facts.$$),
('World Wide Web',       'Tech & Internet 💻', $$The www prefix.$$),
('Social Media',         'Tech & Internet 💻', $$Scrolling for validation.$$),
('Bitcoin',              'Tech & Internet 💻', $$Imaginary coins, real volatility.$$),
('Cloud Storage',        'Tech & Internet 💻', $$Files on someone computer.$$),
('Emoji',                'Tech & Internet 💻', $$Tiny faces, big feelings.$$),
('Smartphone',           'Tech & Internet 💻', $$Pocket-sized everything.$$),
('Cryptocurrency',       'Tech & Internet 💻', $$Digital gold rush.$$),
('Virtual Reality',      'Tech & Internet 💻', $$Headset, fake worlds.$$),
('Search Engine',        'Tech & Internet 💻', $$Question answering machine.$$),
('Cybersecurity',        'Tech & Internet 💻', $$Hackers worst day.$$),
('Streaming',            'Tech & Internet 💻', $$Binge without downloads.$$),
('The Metaverse',        'Tech & Internet 💻', $$Promised digital nowhere.$$),
('Hashtag',              'Tech & Internet 💻', $$Pound sign goes viral.$$),
('Going Viral',          'Tech & Internet 💻', $$Internet wildfire fame.$$),
('Operating System',     'Tech & Internet 💻', $$The boss software.$$),
('Touchscreen',          'Tech & Internet 💻', $$Fingerprints as input.$$),
('Data Breach',          'Tech & Internet 💻', $$Passwords on the loose.$$),
('Wireless Charging',    'Tech & Internet 💻', $$Powered by a pad.$$),
('Two Factor Authentication','Tech & Internet 💻', $$Code after your password.$$);

-- ============================================================
-- Round 2: +20 per category (total 40 each). Additive — distinct from round 1.
-- ============================================================
INSERT INTO public.daily_puzzles (phrase, category, clue) VALUES
('The Avengers',         'Movies & TV 🎬', $$Earth's mightiest squabbling heroes.$$),
('Frozen',               'Movies & TV 🎬', $$Snow queen, let it go.$$),
('Finding Nemo',         'Movies & TV 🎬', $$Lost clownfish, forgetful sidekick.$$),
('Shrek',                'Movies & TV 🎬', $$Ogre, donkey, swamp romance.$$),
('The Wizard of Oz',     'Movies & TV 🎬', $$Yellow brick road trip.$$),
('Rocky',                'Movies & TV 🎬', $$Philadelphia boxer, frozen meat.$$),
('Home Alone',           'Movies & TV 🎬', $$Forgotten kid booby-traps house.$$),
('Mean Girls',           'Movies & TV 🎬', $$Pink on Wednesdays.$$),
('The Hangover',         'Movies & TV 🎬', $$Vegas blackout, missing groom.$$),
('Spider Man',           'Movies & TV 🎬', $$Radioactive bite, web slinger.$$),
('Black Panther',        'Movies & TV 🎬', $$Wakanda forever.$$),
('Squid Game',           'Movies & TV 🎬', $$Deadly children's games.$$),
('Ted Lasso',            'Movies & TV 🎬', $$Optimistic coach abroad.$$),
('Seinfeld',             'Movies & TV 🎬', $$Show about nothing.$$),
('The Sopranos',         'Movies & TV 🎬', $$Mob boss in therapy.$$),
('The Mandalorian',      'Movies & TV 🎬', $$Bounty hunter, tiny ward.$$),
('Wednesday',            'Movies & TV 🎬', $$Deadpan Addams daughter.$$),
('Better Call Saul',     'Movies & TV 🎬', $$Crooked lawyer origin.$$),
('Gladiator',            'Movies & TV 🎬', $$Are you not entertained?$$),
('Grease',               'Movies & TV 🎬', $$Summer lovin, greased lightning.$$),
('Shake It Off',         'Music 🎵', $$Haters gonna hate.$$),
('Single Ladies',        'Music 🎵', $$Put a ring on it.$$),
('Like a Rolling Stone', 'Music 🎵', $$Dylan asks how it feels.$$),
('Sweet Home Alabama',   'Music 🎵', $$Southern rock pride.$$),
('Wonderwall',           'Music 🎵', $$Oasis singalong staple.$$),
('Hey Jude',             'Music 🎵', $$Sad song made better.$$),
('Smooth Criminal',      'Music 🎵', $$Annie, are you okay?$$),
('Blinding Lights',      'Music 🎵', $$Eighties synth, midnight drive.$$),
('Shape of You',         'Music 🎵', $$Sheeran club romance.$$),
('Levitating',           'Music 🎵', $$Dua Lipa disco float.$$),
('Seven Nation Army',    'Music 🎵', $$Stadium chant riff.$$),
('Mr Brightside',        'Music 🎵', $$Killers jealousy spiral.$$),
('Viva la Vida',         'Music 🎵', $$Coldplay's fallen king.$$),
('Bad Guy',              'Music 🎵', $$Whispered, duh.$$),
('Gangnam Style',        'Music 🎵', $$Horse dance gone viral.$$),
('Africa',               'Music 🎵', $$Toto blesses the rains.$$),
('Hey Ya',               'Music 🎵', $$Shake it, Polaroid.$$),
('Take On Me',           'Music 🎵', $$Pencil-sketch chase.$$),
('Born to Run',          'Music 🎵', $$Springsteen escape anthem.$$),
('Crazy in Love',        'Music 🎵', $$Beyonce, uh oh horns.$$),
('Martin Luther King',   'Famous People 🌟', $$Dream speech, march leader.$$),
('Mother Teresa',        'Famous People 🌟', $$Saint of the slums.$$),
('Stephen Hawking',      'Famous People 🌟', $$Black holes, robotic voice.$$),
('Queen Elizabeth',      'Famous People 🌟', $$Longest-reigning British monarch.$$),
('Napoleon Bonaparte',   'Famous People 🌟', $$Short emperor, big ambition.$$),
('Pablo Picasso',        'Famous People 🌟', $$Cubism, scrambled faces.$$),
('Frida Kahlo',          'Famous People 🌟', $$Unibrow, painful self-portraits.$$),
('Mark Zuckerberg',      'Famous People 🌟', $$Hoodie, your data.$$),
('Tom Hanks',            'Famous People 🌟', $$Nicest man, deserted island.$$),
('Serena Williams',      'Famous People 🌟', $$Tennis power, sister rivalry.$$),
('Bill Gates',           'Famous People 🌟', $$Windows mogul turned philanthropist.$$),
('Rosa Parks',           'Famous People 🌟', $$Stayed in her seat.$$),
('Charlie Chaplin',      'Famous People 🌟', $$Silent tramp, tiny mustache.$$),
('Neil Armstrong',       'Famous People 🌟', $$One small step.$$),
('Greta Thunberg',       'Famous People 🌟', $$How dare you.$$),
('Elvis Presley',        'Famous People 🌟', $$Hips, jumpsuit, the King.$$),
('Joan of Arc',          'Famous People 🌟', $$Teen saint, burning stake.$$),
('Winston Churchill',    'Famous People 🌟', $$Cigar, never surrender.$$),
('Audrey Hepburn',       'Famous People 🌟', $$Tiffany breakfast elegance.$$),
('Christopher Columbus', 'Famous People 🌟', $$Sailed, got famously lost.$$),
('Cheeseburger',         'Food & Drink 🍔', $$Patty plus a slice.$$),
('Donut',                'Food & Drink 🍔', $$Sweet ring, cop cliche.$$),
('Burrito',              'Food & Drink 🍔', $$Foil-wrapped, overstuffed.$$),
('Lasagna',              'Food & Drink 🍔', $$Layered pasta, Garfield's love.$$),
('Fried Chicken',        'Food & Drink 🍔', $$Crispy, finger-licking bird.$$),
('Milkshake',            'Food & Drink 🍔', $$Brings boys to the yard.$$),
('Nachos',               'Food & Drink 🍔', $$Chips drowning in cheese.$$),
('Cheesecake',           'Food & Drink 🍔', $$Dense, creamy, New York.$$),
('Steak',                'Food & Drink 🍔', $$Sizzling slab, medium rare.$$),
('Popcorn',              'Food & Drink 🍔', $$Movie night kernels.$$),
('Apple Pie',            'Food & Drink 🍔', $$America in a crust.$$),
('Pho',                  'Food & Drink 🍔', $$Vietnamese broth bowl.$$),
('Dumplings',            'Food & Drink 🍔', $$Steamed pockets, soy dip.$$),
('Lemonade',             'Food & Drink 🍔', $$Sour summer stand.$$),
('Waffles',              'Food & Drink 🍔', $$Syrup grids.$$),
('Curry',                'Food & Drink 🍔', $$Spiced stew, regional pride.$$),
('Smoothie',             'Food & Drink 🍔', $$Blended fruit, fake health.$$),
('Cotton Candy',         'Food & Drink 🍔', $$Spun sugar cloud.$$),
('Espresso',             'Food & Drink 🍔', $$Tiny cup, big jolt.$$),
('Bagel',                'Food & Drink 🍔', $$Boiled, holey, schmear ready.$$),
('Mount Fuji',           'Places & Travel ✈️', $$Japan's snowy cone.$$),
('The Leaning Tower',    'Places & Travel ✈️', $$Pisa's tilting mistake.$$),
('Stonehenge',           'Places & Travel ✈️', $$Mysterious standing stones.$$),
('The Taj Mahal',        'Places & Travel ✈️', $$Marble monument to love.$$),
('New York City',        'Places & Travel ✈️', $$The big apple.$$),
('London',               'Places & Travel ✈️', $$Red buses, foggy crown.$$),
('Paris',                'Places & Travel ✈️', $$City of lights.$$),
('Mount Kilimanjaro',    'Places & Travel ✈️', $$Africa's snowy summit.$$),
('The Amazon',           'Places & Travel ✈️', $$Vast green rainforest.$$),
('Dubai',                'Places & Travel ✈️', $$Desert skyscrapers, instant wealth.$$),
('Antarctica',           'Places & Travel ✈️', $$Frozen penguin continent.$$),
('Rome',                 'Places & Travel ✈️', $$All roads lead here.$$),
('The Golden Gate',      'Places & Travel ✈️', $$Foggy orange bridge.$$),
('Mount Vesuvius',       'Places & Travel ✈️', $$Buried Pompeii in ash.$$),
('The Maldives',         'Places & Travel ✈️', $$Sinking island paradise.$$),
('Yellowstone',          'Places & Travel ✈️', $$Geysers and grumpy bears.$$),
('Easter Island',        'Places & Travel ✈️', $$Giant stone heads.$$),
('The Alps',             'Places & Travel ✈️', $$Snowy European spine.$$),
('Cairo',                'Places & Travel ✈️', $$Pyramids next door.$$),
('Barcelona',            'Places & Travel ✈️', $$Gaudi's melting cathedral.$$),
('Free Throw',           'Sports 🏆', $$Uncontested foul-line shot.$$),
('Offside',              'Sports 🏆', $$Soccer's confusing flag.$$),
('Half Time',            'Sports 🏆', $$Show with snacks.$$),
('Wimbledon',            'Sports 🏆', $$Strawberries and grass tennis.$$),
('The World Series',     'Sports 🏆', $$Baseball's autumn crown.$$),
('Field Goal',           'Sports 🏆', $$Three points, uprights.$$),
('Bicycle Kick',         'Sports 🏆', $$Overhead acrobatic strike.$$),
('Royal Rumble',         'Sports 🏆', $$Thirty wrestlers, one ring.$$),
('Sudden Death',         'Sports 🏆', $$Next score wins.$$),
('Pole Vault',           'Sports 🏆', $$Pole-assisted high jump.$$),
('Marathon',             'Sports 🏆', $$Twenty-six grueling miles.$$),
('Strikeout',            'Sports 🏆', $$Three swings, sit down.$$),
('Hole in One',          'Sports 🏆', $$Tee to cup, once.$$),
('Red Card',             'Sports 🏆', $$Soccer's ejection slip.$$),
('Power Play',           'Sports 🏆', $$Hockey's man advantage.$$),
('Grand Prix',           'Sports 🏆', $$Formula one circuit.$$),
('The Ryder Cup',        'Sports 🏆', $$Golf, continents collide.$$),
('Triple Crown',         'Sports 🏆', $$Three-race horse glory.$$),
('Full Court Press',     'Sports 🏆', $$Defense, end to end.$$),
('Decathlon',            'Sports 🏆', $$Ten events, one champion.$$),
('Back to Square One',   'Phrases & Sayings 🗣️', $$Start all over.$$),
('Beat Around the Bush', 'Phrases & Sayings 🗣️', $$Avoid the point.$$),
('Hit the Nail on the Head','Phrases & Sayings 🗣️', $$Exactly right.$$),
('The Last Straw',       'Phrases & Sayings 🗣️', $$Final breaking point.$$),
('Cost an Arm and a Leg','Phrases & Sayings 🗣️', $$Painfully expensive.$$),
('Add Fuel to the Fire', 'Phrases & Sayings 🗣️', $$Make it worse.$$),
('A Blessing in Disguise','Phrases & Sayings 🗣️', $$Hidden good news.$$),
('Throw in the Towel',   'Phrases & Sayings 🗣️', $$Give up.$$),
('Read Between the Lines','Phrases & Sayings 🗣️', $$Find hidden meaning.$$),
('Jump on the Bandwagon','Phrases & Sayings 🗣️', $$Join the trend.$$),
('The Tip of the Iceberg','Phrases & Sayings 🗣️', $$Small visible part.$$),
('Pull Yourself Together','Phrases & Sayings 🗣️', $$Calm down.$$),
('Burn the Bridges',     'Phrases & Sayings 🗣️', $$End it permanently.$$),
('Out of the Blue',      'Phrases & Sayings 🗣️', $$Completely unexpected.$$),
('A Penny for Your Thoughts','Phrases & Sayings 🗣️', $$What are you thinking?$$),
('The Whole Nine Yards', 'Phrases & Sayings 🗣️', $$Everything, all of it.$$),
('When Pigs Fly',        'Phrases & Sayings 🗣️', $$Never going to happen.$$),
('Steal the Show',       'Phrases & Sayings 🗣️', $$Outshine everyone.$$),
('Face the Music',       'Phrases & Sayings 🗣️', $$Accept the consequences.$$),
('Down to Earth',        'Phrases & Sayings 🗣️', $$Humble and practical.$$),
('Milky Way',            'Science & Nature 🔬', $$Our home galaxy.$$),
('Climate Change',       'Science & Nature 🔬', $$Warming, melting, denial.$$),
('Greenhouse Effect',    'Science & Nature 🔬', $$Trapped heat blanket.$$),
('Cell Division',        'Science & Nature 🔬', $$One becomes two.$$),
('The Big Dipper',       'Science & Nature 🔬', $$Ladle of stars.$$),
('Supernova',            'Science & Nature 🔬', $$A star's violent death.$$),
('Magnetism',            'Science & Nature 🔬', $$Invisible pulling force.$$),
('Ecosystem',            'Science & Nature 🔬', $$Web of living things.$$),
('Genetics',             'Science & Nature 🔬', $$Inherited blueprint.$$),
('The Ozone Layer',      'Science & Nature 🔬', $$Sky's sunscreen.$$),
('Comet',                'Science & Nature 🔬', $$Icy tail across sky.$$),
('Antibodies',           'Science & Nature 🔬', $$Immune system soldiers.$$),
('Friction',             'Science & Nature 🔬', $$Resistance that slows.$$),
('Density',              'Science & Nature 🔬', $$Mass packed in space.$$),
('Stem Cells',           'Science & Nature 🔬', $$Body's blank-slate cells.$$),
('Erosion',              'Science & Nature 🔬', $$Wind and water sculpting.$$),
('Vaccination',          'Science & Nature 🔬', $$Training the immune system.$$),
('The Atmosphere',       'Science & Nature 🔬', $$Air blanket around Earth.$$),
('Carbon Dioxide',       'Science & Nature 🔬', $$Exhaled greenhouse gas.$$),
('Metamorphosis',        'Science & Nature 🔬', $$Caterpillar to butterfly.$$),
('The Lord of the Rings','Books & Characters 📚', $$One ring, long walk.$$),
('Pinocchio',            'Books & Characters 📚', $$Lying puppet, growing nose.$$),
('Cinderella',           'Books & Characters 📚', $$Lost slipper, midnight curfew.$$),
('Snow White',           'Books & Characters 📚', $$Poisoned apple, seven roommates.$$),
('Treasure Island',      'Books & Characters 📚', $$Pirates, map, buried gold.$$),
('The Jungle Book',      'Books & Characters 📚', $$Boy raised by wolves.$$),
('Wuthering Heights',    'Books & Characters 📚', $$Moors, doomed obsession.$$),
('Of Mice and Men',      'Books & Characters 📚', $$Dreaming of rabbits.$$),
('The Three Musketeers', 'Books & Characters 📚', $$All for one.$$),
('Anna Karenina',        'Books & Characters 📚', $$Affair, oncoming train.$$),
('Crime and Punishment', 'Books & Characters 📚', $$Guilty student spirals.$$),
('War and Peace',        'Books & Characters 📚', $$Very long Russian epic.$$),
('The Catcher in the Rye','Books & Characters 📚', $$Whiny teen, red hat.$$),
('Robinson Crusoe',      'Books & Characters 📚', $$Castaway, lonely island.$$),
('A Christmas Carol',    'Books & Characters 📚', $$Three ghosts visit Scrooge.$$),
('Matilda',              'Books & Characters 📚', $$Telekinetic genius girl.$$),
('Hamlet',               'Books & Characters 📚', $$To be or not.$$),
('The Grinch',           'Books & Characters 📚', $$Green grump steals Christmas.$$),
('Macbeth',              'Books & Characters 📚', $$Bloody crown, guilty hands.$$),
('Oliver Twist',         'Books & Characters 📚', $$Please sir, more gruel.$$),
('The Sims',             'Video Games 🎮', $$Virtual people, pause god.$$),
('Animal Crossing',      'Video Games 🎮', $$Island debt to a raccoon.$$),
('Red Dead Redemption',  'Video Games 🎮', $$Wild west outlaw saga.$$),
('Assassins Creed',      'Video Games 🎮', $$Hooded historical stabbing.$$),
('The Last of Us',       'Video Games 🎮', $$Fungus apocalypse escort.$$),
('League of Legends',    'Video Games 🎮', $$Five-lane war.$$),
('Cyberpunk',            'Video Games 🎮', $$Neon future, buggy launch.$$),
('God of War',           'Video Games 🎮', $$Angry dad, Greek gods.$$),
('Resident Evil',        'Video Games 🎮', $$Mansion of zombies.$$),
('Mario Kart',           'Video Games 🎮', $$Banana peels, blue shells.$$),
('Overwatch',            'Video Games 🎮', $$Hero shooter, payload push.$$),
('Roblox',               'Video Games 🎮', $$Kid-built game universe.$$),
('Elden Ring',           'Video Games 🎮', $$Open world, frequent death.$$),
('Dark Souls',           'Video Games 🎮', $$Prepare to die.$$),
('Metroid',              'Video Games 🎮', $$Bounty hunter, alien caves.$$),
('The Witcher',          'Video Games 🎮', $$Monster hunter, silver sword.$$),
('Bioshock',             'Video Games 🎮', $$Underwater dystopia.$$),
('Temple Run',           'Video Games 🎮', $$Endless sprint from monkeys.$$),
('Counter Strike',       'Video Games 🎮', $$Terrorists versus counter.$$),
('Stardew Valley',       'Video Games 🎮', $$Inherited farm, cozy grind.$$),
('Pepsi',                'Brands & Logos 🏷️', $$Coke's blue rival.$$),
('Microsoft',            'Brands & Logos 🏷️', $$Windows and clippy.$$),
('Samsung',              'Brands & Logos 🏷️', $$Korean everything maker.$$),
('Burger King',          'Brands & Logos 🏷️', $$Have it your way.$$),
('Walmart',              'Brands & Logos 🏷️', $$Big box, low prices.$$),
('Lamborghini',          'Brands & Logos 🏷️', $$Scissor doors, bull badge.$$),
('Chanel',               'Brands & Logos 🏷️', $$Double C, French couture.$$),
('Louis Vuitton',        'Brands & Logos 🏷️', $$Monogram luggage flex.$$),
('Toyota',               'Brands & Logos 🏷️', $$Reliable, runs forever.$$),
('KFC',                  'Brands & Logos 🏷️', $$Colonel's secret spices.$$),
('Subway',               'Brands & Logos 🏷️', $$Footlong sandwich chain.$$),
('Twitter',              'Brands & Logos 🏷️', $$Birds, now an X.$$),
('Instagram',            'Brands & Logos 🏷️', $$Filtered photo grid.$$),
('YouTube',              'Brands & Logos 🏷️', $$Endless video rabbit hole.$$),
('Dominos',              'Brands & Logos 🏷️', $$Thirty-minute pizza promise.$$),
('Heineken',             'Brands & Logos 🏷️', $$Green bottle lager.$$),
('Visa',                 'Brands & Logos 🏷️', $$Everywhere you want to be.$$),
('PlayStation',          'Brands & Logos 🏷️', $$Sony's gaming console.$$),
('Xbox',                 'Brands & Logos 🏷️', $$Green gaming console.$$),
('Reebok',               'Brands & Logos 🏷️', $$Retro pump sneakers.$$),
('Machine Learning',     'Tech & Internet 💻', $$Algorithms that self-improve.$$),
('Self Driving Car',     'Tech & Internet 💻', $$Robot at the wheel.$$),
('Quantum Computing',    'Tech & Internet 💻', $$Qubits break encryption.$$),
('Open Source',          'Tech & Internet 💻', $$Free, shared code.$$),
('Augmented Reality',    'Tech & Internet 💻', $$Digital layer on reality.$$),
('Facial Recognition',   'Tech & Internet 💻', $$Your face unlocks it.$$),
('The Dark Web',         'Tech & Internet 💻', $$Internet's shady basement.$$),
('Net Neutrality',       'Tech & Internet 💻', $$All traffic treated equal.$$),
('Phishing',             'Tech & Internet 💻', $$Fake email, real theft.$$),
('Browser Cookies',      'Tech & Internet 💻', $$Tracking your crumbs.$$),
('Encryption',           'Tech & Internet 💻', $$Scrambled secrets.$$),
('Bandwidth',            'Tech & Internet 💻', $$Pipe size for data.$$),
('The Algorithm',        'Tech & Internet 💻', $$Decides what you see.$$),
('Drone Delivery',       'Tech & Internet 💻', $$Package from the sky.$$),
('Smart Home',           'Tech & Internet 💻', $$Voice-controlled house.$$),
('Blockchain',           'Tech & Internet 💻', $$Tamper-proof ledger.$$),
('Video Call',           'Tech & Internet 💻', $$Pajamas below camera.$$),
('App Store',            'Tech & Internet 💻', $$Tap to download.$$),
('Password Manager',     'Tech & Internet 💻', $$One vault, many keys.$$),
('Fiber Optic',          'Tech & Internet 💻', $$Internet at light speed.$$);

-- ============================================================
-- Round 3: +20 per category (total 60 each). Additive — distinct from rounds 1-2.
-- ============================================================
INSERT INTO public.daily_puzzles (phrase, category, clue) VALUES
('Iron Man',             'Movies & TV 🎬', $$Billionaire in a metal suit.$$),
('The Incredibles',      'Movies & TV 🎬', $$Superhero family in spandex.$$),
('Despicable Me',        'Movies & TV 🎬', $$Villain adopts three girls.$$),
('Fight Club',           'Movies & TV 🎬', $$First rule: stay quiet.$$),
('The Shining',          'Movies & TV 🎬', $$Haunted hotel, here's Johnny.$$),
('Beauty and the Beast', 'Movies & TV 🎬', $$Girl loves cursed host.$$),
('The Truman Show',      'Movies & TV 🎬', $$His life is televised.$$),
('Top Gun',              'Movies & TV 🎬', $$Need for speed, jets.$$),
('Casino Royale',        'Movies & TV 🎬', $$Bond, poker, broken heart.$$),
('The Walking Dead',     'Movies & TV 🎬', $$Zombie apocalypse soap.$$),
('Twilight',             'Movies & TV 🎬', $$Sparkly vampire love triangle.$$),
('The Crown',            'Movies & TV 🎬', $$Royal drama, stiff lip.$$),
('Peaky Blinders',       'Movies & TV 🎬', $$Razor caps, Birmingham gangsters.$$),
('Money Heist',          'Movies & TV 🎬', $$Red jumpsuits, Dali masks.$$),
('Black Mirror',         'Movies & TV 🎬', $$Tech dystopia anthology.$$),
('Euphoria',             'Movies & TV 🎬', $$Glittery teen chaos.$$),
('House of Cards',       'Movies & TV 🎬', $$Ruthless political climber.$$),
('The Boys',             'Movies & TV 🎬', $$Evil superheroes, corporate satire.$$),
('Parasite',             'Movies & TV 🎬', $$Basement family, rich house.$$),
('La La Land',           'Movies & TV 🎬', $$Jazz pianist, aspiring actress.$$),
('Stayin Alive',         'Music 🎵', $$Disco, falsetto, white suit.$$),
('Sweet Dreams',         'Music 🎵', $$Eurythmics, who am I.$$),
('Yesterday',            'Music 🎵', $$Troubles seemed far away.$$),
('Hallelujah',           'Music 🎵', $$Cohen's solemn cold chord.$$),
('Wannabe',              'Music 🎵', $$Spice Girls demand zigazig.$$),
('Toxic',                'Music 🎵', $$Britney flight attendant fantasy.$$),
('Umbrella',             'Music 🎵', $$Rihanna, ella ella.$$),
('Hips Dont Lie',        'Music 🎵', $$Shakira's truthful hips.$$),
('Hotline Bling',        'Music 🎵', $$Drake's awkward dance.$$),
('Happy',                'Music 🎵', $$Pharrell says clap along.$$),
('Royals',               'Music 🎵', $$Lorde, never be royals.$$),
('Somebody That I Used to Know','Music 🎵', $$Gotye's painted breakup.$$),
('Counting Stars',       'Music 🎵', $$OneRepublic loses sleep.$$),
('Radioactive',          'Music 🎵', $$Imagine Dragons apocalypse.$$),
('Stronger',             'Music 🎵', $$Kanye, harder better faster.$$),
('Firework',             'Music 🎵', $$Katy Perry, baby you're a.$$),
('Boulevard of Broken Dreams','Music 🎵', $$Green Day walks alone.$$),
('Clocks',               'Music 🎵', $$Coldplay piano ticking.$$),
('No Scrubs',            'Music 🎵', $$TLC rejects broke guys.$$),
('Wrecking Ball',        'Music 🎵', $$Miley swings, nude demolition.$$),
('Beethoven',            'Famous People 🌟', $$Deaf composer, fateful symphony.$$),
('Mozart',               'Famous People 🌟', $$Child prodigy, powdered wig.$$),
('Isaac Newton',         'Famous People 🌟', $$Apple, gravity, calculus.$$),
('Charles Darwin',       'Famous People 🌟', $$Finches, natural selection.$$),
('Marie Curie',          'Famous People 🌟', $$Radioactive Nobel pioneer.$$),
('Nikola Tesla',         'Famous People 🌟', $$Lightning genius, died broke.$$),
('Genghis Khan',         'Famous People 🌟', $$Mongol conqueror, vast empire.$$),
('Julius Caesar',        'Famous People 🌟', $$Stabbed senate, et tu.$$),
('Bob Marley',           'Famous People 🌟', $$Reggae, dreadlocks, one love.$$),
('Stephen King',         'Famous People 🌟', $$Horror novel machine.$$),
('Bob Dylan',            'Famous People 🌟', $$Nasal folk poet.$$),
('Steven Spielberg',     'Famous People 🌟', $$Sharks, dinosaurs, aliens.$$),
('Michael Jordan',       'Famous People 🌟', $$Tongue out, six rings.$$),
('Usain Bolt',           'Famous People 🌟', $$Fastest man, lightning pose.$$),
('Tiger Woods',          'Famous People 🌟', $$Golf dominance, red Sunday.$$),
('Lionel Messi',         'Famous People 🌟', $$Tiny feet, magic dribble.$$),
('Cristiano Ronaldo',    'Famous People 🌟', $$Siu, chiseled striker.$$),
('Coco Chanel',          'Famous People 🌟', $$Freed women from corsets.$$),
('Florence Nightingale', 'Famous People 🌟', $$Lamp-carrying nursing pioneer.$$),
('Mick Jagger',          'Famous People 🌟', $$Strutting Stones frontman.$$),
('Pretzel',              'Food & Drink 🍔', $$Salty twisted knot.$$),
('Meatballs',            'Food & Drink 🍔', $$Rolled, saucy spheres.$$),
('Quesadilla',           'Food & Drink 🍔', $$Folded cheesy tortilla.$$),
('Onion Rings',          'Food & Drink 🍔', $$Battered golden circles.$$),
('Clam Chowder',         'Food & Drink 🍔', $$Creamy New England soup.$$),
('Fish and Chips',       'Food & Drink 🍔', $$Battered cod, British staple.$$),
('Mashed Potatoes',      'Food & Drink 🍔', $$Whipped buttery comfort.$$),
('Caesar Salad',         'Food & Drink 🍔', $$Croutons, anchovy dressing.$$),
('Brownie',              'Food & Drink 🍔', $$Fudgy chocolate square.$$),
('Hummus',               'Food & Drink 🍔', $$Chickpea dip, pita scoop.$$),
('Sourdough',            'Food & Drink 🍔', $$Tangy pandemic bread.$$),
('Iced Tea',             'Food & Drink 🍔', $$Sweet southern sipper.$$),
('Cappuccino',           'Food & Drink 🍔', $$Foamy espresso art.$$),
('Churros',              'Food & Drink 🍔', $$Fried dough, cinnamon sugar.$$),
('Falafel',              'Food & Drink 🍔', $$Fried chickpea balls.$$),
('Gnocchi',              'Food & Drink 🍔', $$Pillowy potato dumplings.$$),
('Sundae',               'Food & Drink 🍔', $$Ice cream, cherry top.$$),
('Hot Chocolate',        'Food & Drink 🍔', $$Cocoa, marshmallow blanket.$$),
('Buffalo Wings',        'Food & Drink 🍔', $$Spicy, sticky, messy.$$),
('Tiramisu',             'Food & Drink 🍔', $$Coffee-soaked Italian dessert.$$),
('Mount Etna',           'Places & Travel ✈️', $$Sicily's smoking volcano.$$),
('The Dead Sea',         'Places & Travel ✈️', $$Float, can't sink.$$),
('Buckingham Palace',    'Places & Travel ✈️', $$Guards in tall hats.$$),
('The Great Barrier Reef','Places & Travel ✈️', $$World's biggest coral.$$),
('Petra',                'Places & Travel ✈️', $$Rose-red carved city.$$),
('Amsterdam',            'Places & Travel ✈️', $$Canals, bikes, tulips.$$),
('Berlin',               'Places & Travel ✈️', $$Fallen wall, currywurst.$$),
('Istanbul',             'Places & Travel ✈️', $$Two continents, one city.$$),
('Rio de Janeiro',       'Places & Travel ✈️', $$Christ statue, carnival.$$),
('The Acropolis',        'Places & Travel ✈️', $$Greek temple hilltop.$$),
('Bali',                 'Places & Travel ✈️', $$Temples, rice terraces, yoga.$$),
('Iceland',              'Places & Travel ✈️', $$Geysers, volcanoes, elves.$$),
('The Louvre',           'Places & Travel ✈️', $$Glass pyramid, Mona Lisa.$$),
('Chichen Itza',         'Places & Travel ✈️', $$Mayan step pyramid.$$),
('Angkor Wat',           'Places & Travel ✈️', $$Sprawling Cambodian temple.$$),
('The Serengeti',        'Places & Travel ✈️', $$Lions and great migration.$$),
('Honolulu',             'Places & Travel ✈️', $$Hawaiian beaches, leis.$$),
('Moscow',               'Places & Travel ✈️', $$Red square, onion domes.$$),
('Mount Olympus',        'Places & Travel ✈️', $$Home of Greek gods.$$),
('Greenland',            'Places & Travel ✈️', $$Icy, misleadingly named.$$),
('Alley Oop',            'Sports 🏆', $$Lob, catch, jam.$$),
('Birdie',               'Sports 🏆', $$One under par.$$),
('The Kentucky Derby',   'Sports 🏆', $$Two-minute horse sprint.$$),
('Penalty Shootout',     'Sports 🏆', $$Nerve-wracking soccer tiebreak.$$),
('Slap Shot',            'Sports 🏆', $$Hockey's hardest swing.$$),
('Triple Axel',          'Sports 🏆', $$Figure skating jump.$$),
('Body Slam',            'Sports 🏆', $$Wrestling's flat finisher.$$),
('Pit Stop',             'Sports 🏆', $$Tires changed in seconds.$$),
('Nutmeg',               'Sports 🏆', $$Ball through the legs.$$),
('Eagle',                'Sports 🏆', $$Two under par.$$),
('Sin Bin',              'Sports 🏆', $$Penalty box timeout.$$),
('Walk Off',             'Sports 🏆', $$Game-ending winning hit.$$),
('Two Minute Drill',     'Sports 🏆', $$Hurry-up offense.$$),
('The Davis Cup',        'Sports 🏆', $$National team tennis.$$),
('Suplex',               'Sports 🏆', $$Wrestling overhead throw.$$),
('Knuckleball',          'Sports 🏆', $$Wobbling, unpredictable pitch.$$),
('Free Kick',            'Sports 🏆', $$Wall-jumping set piece.$$),
('The Final Four',       'Sports 🏆', $$College basketball's last teams.$$),
('Dribble',              'Sports 🏆', $$Bouncing the ball.$$),
('Goalkeeper',           'Sports 🏆', $$Last line of defense.$$),
('A Piece of My Mind',   'Phrases & Sayings 🗣️', $$Tell off bluntly.$$),
('Break a Leg',          'Phrases & Sayings 🗣️', $$Good luck, performer.$$),
('Call It a Day',        'Phrases & Sayings 🗣️', $$Stop working now.$$),
('Cry Over Spilled Milk','Phrases & Sayings 🗣️', $$Fret over the past.$$),
('Devils Advocate',      'Phrases & Sayings 🗣️', $$Argue the opposite side.$$),
('Easy as Pie',          'Phrases & Sayings 🗣️', $$Very simple.$$),
('Go the Extra Mile',    'Phrases & Sayings 🗣️', $$Do more than required.$$),
('Hold Your Horses',     'Phrases & Sayings 🗣️', $$Wait, slow down.$$),
('In the Same Boat',     'Phrases & Sayings 🗣️', $$Sharing a predicament.$$),
('Jump the Gun',         'Phrases & Sayings 🗣️', $$Act too soon.$$),
('Keep Your Chin Up',    'Phrases & Sayings 🗣️', $$Stay positive.$$),
('Last but Not Least',   'Phrases & Sayings 🗣️', $$Final, still important.$$),
('Make a Long Story Short','Phrases & Sayings 🗣️', $$Skip the details.$$),
('No Pain No Gain',      'Phrases & Sayings 🗣️', $$Effort brings reward.$$),
('On Thin Ice',          'Phrases & Sayings 🗣️', $$In a risky spot.$$),
('Pull Some Strings',    'Phrases & Sayings 🗣️', $$Use secret influence.$$),
('Rain on Your Parade',  'Phrases & Sayings 🗣️', $$Spoil the fun.$$),
('The Early Bird',       'Phrases & Sayings 🗣️', $$Gets the worm.$$),
('Through Thick and Thin','Phrases & Sayings 🗣️', $$Loyal in all times.$$),
('Wrap Your Head Around','Phrases & Sayings 🗣️', $$Finally understand it.$$),
('Mitochondria',         'Science & Nature 🔬', $$The cell's powerhouse.$$),
('Chlorophyll',          'Science & Nature 🔬', $$Green pigment in leaves.$$),
('Asteroid Belt',        'Science & Nature 🔬', $$Rocks between Mars Jupiter.$$),
('Saturns Rings',        'Science & Nature 🔬', $$Icy planetary halo.$$),
('The Jet Stream',       'Science & Nature 🔬', $$High-altitude wind river.$$),
('Bioluminescence',      'Science & Nature 🔬', $$Living things that glow.$$),
('Continental Drift',    'Science & Nature 🔬', $$Slowly wandering landmasses.$$),
('The Richter Scale',    'Science & Nature 🔬', $$Earthquake magnitude meter.$$),
('Nuclear Fusion',       'Science & Nature 🔬', $$A star's energy source.$$),
('Osmosis',              'Science & Nature 🔬', $$Water crossing a membrane.$$),
('The Aurora',           'Science & Nature 🔬', $$Glowing polar sky.$$),
('Tsunami',              'Science & Nature 🔬', $$Earthquake's giant wave.$$),
('Sedimentary Rock',     'Science & Nature 🔬', $$Layered compressed sediment.$$),
('Inertia',              'Science & Nature 🔬', $$Objects resist change.$$),
('The Ice Age',          'Science & Nature 🔬', $$Glaciers covered Earth.$$),
('Centrifugal Force',    'Science & Nature 🔬', $$Spin flings outward.$$),
('Permafrost',           'Science & Nature 🔬', $$Permanently frozen ground.$$),
('Pollination',          'Science & Nature 🔬', $$Bees moving flower dust.$$),
('Radiation',            'Science & Nature 🔬', $$Invisible energy waves.$$),
('Symbiosis',            'Science & Nature 🔬', $$Two species, mutual benefit.$$),
('The Little Prince',    'Books & Characters 📚', $$Boy from asteroid, rose.$$),
('Jane Eyre',            'Books & Characters 📚', $$Governess, madwoman in attic.$$),
('Great Expectations',   'Books & Characters 📚', $$Orphan, convict, secret fortune.$$),
('The Scarlet Letter',   'Books & Characters 📚', $$Puritan shame, red A.$$),
('Brave New World',      'Books & Characters 📚', $$Engineered happy dystopia.$$),
('Animal Farm',          'Books & Characters 📚', $$Pigs run the revolution.$$),
('Nineteen Eighty Four', 'Books & Characters 📚', $$Big Brother watches.$$),
('The Da Vinci Code',    'Books & Characters 📚', $$Symbologist, church conspiracy.$$),
('Gone with the Wind',   'Books & Characters 📚', $$Frankly, my dear.$$),
('The Chronicles of Narnia','Books & Characters 📚', $$Wardrobe to talking lion.$$),
('A Tale of Two Cities', 'Books & Characters 📚', $$Best and worst times.$$),
('Percy Jackson',        'Books & Characters 📚', $$Demigod fights Greek monsters.$$),
('Where the Wild Things Are','Books & Characters 📚', $$Boy king of monsters.$$),
('The Secret Garden',    'Books & Characters 📚', $$Hidden healing garden.$$),
('Anne of Green Gables', 'Books & Characters 📚', $$Redhead orphan, Prince Edward.$$),
('The Wind in the Willows','Books & Characters 📚', $$Toad, mole, riverbank.$$),
('Les Miserables',       'Books & Characters 📚', $$Stolen bread, lifelong chase.$$),
('The Count of Monte Cristo','Books & Characters 📚', $$Wronged prisoner's revenge.$$),
('Wonder',               'Books & Characters 📚', $$Boy with facial difference.$$),
('The Giver',            'Books & Characters 📚', $$Colorless utopia, one keeper.$$),
('Super Smash Bros',     'Video Games 🎮', $$Nintendo all-star brawl.$$),
('Kingdom Hearts',       'Video Games 🎮', $$Disney meets Final Fantasy.$$),
('Crash Bandicoot',      'Video Games 🎮', $$Spinning orange marsupial.$$),
('Spyro',                'Video Games 🎮', $$Purple dragon, gem hoarder.$$),
('Tomb Raider',          'Video Games 🎮', $$Lara raids ancient ruins.$$),
('Metal Gear Solid',     'Video Games 🎮', $$Stealthy soldier, cardboard box.$$),
('Castlevania',          'Video Games 🎮', $$Whip-cracking vampire hunt.$$),
('Hollow Knight',        'Video Games 🎮', $$Bug knight, ruined kingdom.$$),
('Cuphead',              'Video Games 🎮', $$Cartoon run-and-gun, devil deal.$$),
('Portal',               'Video Games 🎮', $$Test chambers, lying cake.$$),
('Half Life',            'Video Games 🎮', $$Crowbar physicist, alien invasion.$$),
('Borderlands',          'Video Games 🎮', $$Cel-shaded loot shooter.$$),
('Diablo',               'Video Games 🎮', $$Click demons, grab loot.$$),
('Fall Guys',            'Video Games 🎮', $$Bean people obstacle race.$$),
('Subway Surfers',       'Video Games 🎮', $$Endless runner, graffiti kid.$$),
('Plants vs Zombies',    'Video Games 🎮', $$Garden defense, sunflowers.$$),
('Hearthstone',          'Video Games 🎮', $$Warcraft card battler.$$),
('Rocket League',        'Video Games 🎮', $$Cars playing soccer.$$),
('Far Cry',              'Video Games 🎮', $$Open-world outpost chaos.$$),
('Sea of Thieves',       'Video Games 🎮', $$Pirate co-op shanties.$$),
('Mastercard',           'Brands & Logos 🏷️', $$Two overlapping circles.$$),
('Honda',                'Brands & Logos 🏷️', $$Reliable cars and mowers.$$),
('BMW',                  'Brands & Logos 🏷️', $$Blue propeller badge.$$),
('Mercedes Benz',        'Brands & Logos 🏷️', $$Three-pointed star luxury.$$),
('Porsche',              'Brands & Logos 🏷️', $$Crest, rear-engine sports car.$$),
('Puma',                 'Brands & Logos 🏷️', $$Leaping cat sportswear.$$),
('Under Armour',         'Brands & Logos 🏷️', $$Crossed arcs athletic gear.$$),
('Prada',                'Brands & Logos 🏷️', $$Quiet luxury fashion.$$),
('Rolls Royce',          'Brands & Logos 🏷️', $$Spirit of Ecstasy hood.$$),
('Audi',                 'Brands & Logos 🏷️', $$Four interlocked rings.$$),
('Snapchat',             'Brands & Logos 🏷️', $$Yellow ghost, vanishing photos.$$),
('TikTok',               'Brands & Logos 🏷️', $$Short videos, endless scroll.$$),
('Facebook',             'Brands & Logos 🏷️', $$Blue thumb, friend requests.$$),
('LinkedIn',             'Brands & Logos 🏷️', $$Professional humblebrag network.$$),
('Uber',                 'Brands & Logos 🏷️', $$Tap for a ride.$$),
('Airbnb',               'Brands & Logos 🏷️', $$Stranger's couch for rent.$$),
('Dunkin',               'Brands & Logos 🏷️', $$America runs on it.$$),
('Oreo',                 'Brands & Logos 🏷️', $$Twist, lick, dunk.$$),
('Doritos',              'Brands & Logos 🏷️', $$Bold triangular chips.$$),
('Sprite',               'Brands & Logos 🏷️', $$Lemon-lime thirst quencher.$$),
('Wifi',                 'Tech & Internet 💻', $$Invisible internet lifeline.$$),
('Spam',                 'Tech & Internet 💻', $$Unwanted inbox flood.$$),
('Firewall',             'Tech & Internet 💻', $$The network's bouncer.$$),
('The Cloud',            'Tech & Internet 💻', $$Servers you can't see.$$),
('Pixel',                'Tech & Internet 💻', $$Tiny screen dot.$$),
('Bluetooth',            'Tech & Internet 💻', $$Wireless gadget handshake.$$),
('Megabyte',             'Tech & Internet 💻', $$A million bytes.$$),
('Captcha',              'Tech & Internet 💻', $$Prove you're human.$$),
('Incognito Mode',       'Tech & Internet 💻', $$Pretend-private browsing.$$),
('Autocorrect',          'Tech & Internet 💻', $$Fixes ducking typos.$$),
('Influencer',           'Tech & Internet 💻', $$Paid to recommend things.$$),
('Podcast',              'Tech & Internet 💻', $$On-demand talk radio.$$),
('The Inbox',            'Tech & Internet 💻', $$Unread email pile.$$),
('Livestream',           'Tech & Internet 💻', $$Broadcasting in real time.$$),
('Meme',                 'Tech & Internet 💻', $$Recycled internet joke.$$),
('Source Code',          'Tech & Internet 💻', $$The program's recipe.$$),
('Server Farm',          'Tech & Internet 💻', $$Warehouse of computers.$$),
('Tech Support',         'Tech & Internet 💻', $$Tried restarting it?$$),
('Doomscrolling',        'Tech & Internet 💻', $$Endless bad-news feed.$$),
('Deepfake',             'Tech & Internet 💻', $$AI-forged fake video.$$);
