-- ============================================================
-- WordBank puzzle seed — 40 per category × 12 categories = 480
-- (round 1 = first 20 each; round 2 = +20 each, appended at the end).
-- Clues are deliberately SHORT (3–6 words) and oblique: a nudge, not a
-- description (the old 11–13 word clues gave the answer away).
-- Phrases are letters + single spaces only (the board has no punctuation/digits).
--
-- ⚠️ Full reset: clears the daily schedule + in-progress sessions/runs first
-- (they reference daily_puzzles with ON DELETE RESTRICT), then reseeds.
-- ============================================================

DELETE FROM public.daily_puzzle_schedule;
DELETE FROM public.daily_sessions;
DELETE FROM public.arcade_runs;
DELETE FROM public.freeplay_sessions;   -- CASCADEs anyway, explicit for clarity
DELETE FROM public.daily_puzzles;

INSERT INTO public.daily_puzzles (phrase, category, clue) VALUES
-- ===== Movies & TV 🎬 =====
('Star Wars',            'Movies & TV 🎬', $$Space wizards, laser swords.$$),
('The Godfather',        'Movies & TV 🎬', $$An offer, a horse head.$$),
('Breaking Bad',         'Movies & TV 🎬', $$Chemistry teacher turns kingpin.$$),
('Jurassic Park',        'Movies & TV 🎬', $$Cloned dinosaurs, bad idea.$$),
('Forrest Gump',         'Movies & TV 🎬', $$Running man, box of chocolates.$$),
('The Lion King',        'Movies & TV 🎬', $$Cub exile, royal comeback.$$),
('Stranger Things',      'Movies & TV 🎬', $$Upside-down kids, one monster.$$),
('The Matrix',           'Movies & TV 🎬', $$Red pill, bullet time.$$),
('Game of Thrones',      'Movies & TV 🎬', $$Iron chair, frequent funerals.$$),
('Pulp Fiction',         'Movies & TV 🎬', $$Briefcase, dance, diner robbery.$$),
('The Office',           'Movies & TV 🎬', $$Paper company, cringing boss.$$),
('Titanic',              'Movies & TV 🎬', $$Big boat, small door.$$),
('Toy Story',            'Movies & TV 🎬', $$Toys move when alone.$$),
('Friends',              'Movies & TV 🎬', $$Coffee shop, six roommates.$$),
('The Dark Knight',      'Movies & TV 🎬', $$Clown versus caped vigilante.$$),
('Back to the Future',   'Movies & TV 🎬', $$Time-traveling sports car.$$),
('Inception',            'Movies & TV 🎬', $$Dream inside a dream.$$),
('Avatar',               'Movies & TV 🎬', $$Blue aliens, glowing forest.$$),
('The Simpsons',         'Movies & TV 🎬', $$Yellow family, donut dad.$$),
('Jaws',                 'Movies & TV 🎬', $$Bigger boat needed.$$),

-- ===== Music 🎵 =====
('Bohemian Rhapsody',    'Music 🎵', $$Opera meets headbang.$$),
('Thriller',             'Music 🎵', $$Zombie dance, red jacket.$$),
('The Beatles',          'Music 🎵', $$Liverpool four, Abbey Road.$$),
('Taylor Swift',         'Music 🎵', $$Breakups become stadium tours.$$),
('Billie Jean',          'Music 🎵', $$Lit sidewalk, denied paternity.$$),
('November Rain',        'Music 🎵', $$Long ballad, longer solo.$$),
('Hotel California',     'Music 🎵', $$Lovely place, no checkout.$$),
('Rolling Stones',       'Music 🎵', $$Tongue logo, no satisfaction.$$),
('Smells Like Teen Spirit','Music 🎵', $$Grunge anthem, mumbled chorus.$$),
('Bad Romance',          'Music 🎵', $$Gaga wants your love.$$),
('Stairway to Heaven',   'Music 🎵', $$Buying a cloud ladder.$$),
('Old Town Road',        'Music 🎵', $$Country trap, horses out back.$$),
('Imagine',              'Music 🎵', $$Lennon dreams, no heaven.$$),
('Purple Rain',          'Music 🎵', $$Prince weeps in violet.$$),
('Rolling in the Deep',  'Music 🎵', $$Adele, scorched-earth breakup.$$),
('Sweet Caroline',       'Music 🎵', $$Crowd shouts ba ba ba.$$),
('Lose Yourself',        'Music 🎵', $$One shot, mom spaghetti.$$),
('Despacito',            'Music 🎵', $$Slow Spanish summer smash.$$),
('Dancing Queen',        'Music 🎵', $$Seventeen, tambourine, Swedish disco.$$),
('Uptown Funk',          'Music 🎵', $$Too hot, call somebody.$$),

-- ===== Famous People 🌟 =====
('Albert Einstein',      'Famous People 🌟', $$Wild hair, wilder equations.$$),
('Oprah Winfrey',        'Famous People 🌟', $$You get a car!$$),
('Elon Musk',            'Famous People 🌟', $$Rockets, tweets, electric cars.$$),
('Lady Gaga',            'Famous People 🌟', $$Meat dress, piano pop.$$),
('Michael Jackson',      'Famous People 🌟', $$Moonwalk, single glove.$$),
('Beyonce',              'Famous People 🌟', $$Houston queen, flawless reign.$$),
('Abraham Lincoln',      'Famous People 🌟', $$Tall hat, mended nation.$$),
('Cleopatra',            'Famous People 🌟', $$Egypt last pharaoh, Roman flings.$$),
('William Shakespeare',  'Famous People 🌟', $$Bard of doomed lovers.$$),
('Steve Jobs',           'Famous People 🌟', $$Black turtleneck, bitten apple.$$),
('Marilyn Monroe',       'Famous People 🌟', $$White dress over a vent.$$),
('Nelson Mandela',       'Famous People 🌟', $$Prisoner turned president.$$),
('Leonardo da Vinci',    'Famous People 🌟', $$Painter who sketched helicopters.$$),
('Muhammad Ali',         'Famous People 🌟', $$Float, sting, loud mouth.$$),
('Princess Diana',       'Famous People 🌟', $$People princess, paparazzi chase.$$),
('Mahatma Gandhi',       'Famous People 🌟', $$Spinning wheel, salt march.$$),
('Walt Disney',          'Famous People 🌟', $$Mouse mogul, frozen rumor.$$),
('Kim Kardashian',       'Famous People 🌟', $$Famous for being famous.$$),
('Vincent van Gogh',     'Famous People 🌟', $$Starry nights, one ear.$$),
('Barack Obama',         'Famous People 🌟', $$Hope posters, yes we can.$$),

-- ===== Food & Drink 🍔 =====
('Chicken Parmesan',     'Food & Drink 🍔', $$Breaded cutlet, melted mozzarella.$$),
('Pizza',                'Food & Drink 🍔', $$Round, sliced, pineapple debated.$$),
('Sushi',                'Food & Drink 🍔', $$Raw fish, vinegared rice.$$),
('Tacos',                'Food & Drink 🍔', $$Tuesday folded handful.$$),
('Hamburger',            'Food & Drink 🍔', $$Patty between two buns.$$),
('Ice Cream',            'Food & Drink 🍔', $$Cold scoop, summer drip.$$),
('Spaghetti',            'Food & Drink 🍔', $$Twirled strings, red sauce.$$),
('Pancakes',             'Food & Drink 🍔', $$Stacked, syrup-flooded mornings.$$),
('Guacamole',            'Food & Drink 🍔', $$Mashed green, costs extra.$$),
('Coffee',               'Food & Drink 🍔', $$Bitter morning lifeline.$$),
('French Fries',         'Food & Drink 🍔', $$Golden salted sticks.$$),
('Hot Dog',              'Food & Drink 🍔', $$Bun, mystery meat, ballpark.$$),
('Macaroni and Cheese',  'Food & Drink 🍔', $$Orange noodle comfort.$$),
('Pad Thai',             'Food & Drink 🍔', $$Stir-fried noodles, peanut dust.$$),
('Chocolate',            'Food & Drink 🍔', $$Melts in mouth, allegedly.$$),
('Pumpkin Spice',        'Food & Drink 🍔', $$Autumn in a cup.$$),
('Margarita',            'Food & Drink 🍔', $$Salt rim, lime, regret.$$),
('Ramen',                'Food & Drink 🍔', $$Broth, noodles, dorm survival.$$),
('Bacon',                'Food & Drink 🍔', $$Sizzling breakfast vice.$$),
('Avocado Toast',        'Food & Drink 🍔', $$Millennial pricey breakfast.$$),

-- ===== Places & Travel ✈️ =====
('The Eiffel Tower',     'Places & Travel ✈️', $$Iron giant over Paris.$$),
('Grand Canyon',         'Places & Travel ✈️', $$Big colorful hole, Arizona.$$),
('Mount Everest',        'Places & Travel ✈️', $$Highest, deadliest selfie spot.$$),
('Great Wall of China',  'Places & Travel ✈️', $$Very long ancient barrier.$$),
('Statue of Liberty',    'Places & Travel ✈️', $$Green lady, raised torch.$$),
('Times Square',         'Places & Travel ✈️', $$Neon, crowds, dropping ball.$$),
('Niagara Falls',        'Places & Travel ✈️', $$Honeymoon roaring water.$$),
('Las Vegas',            'Places & Travel ✈️', $$Sin city, neon desert.$$),
('Big Ben',              'Places & Travel ✈️', $$London chiming clock tower.$$),
('The Colosseum',        'Places & Travel ✈️', $$Roman arena, lion seating.$$),
('Mount Rushmore',       'Places & Travel ✈️', $$Four presidents in rock.$$),
('Santorini',            'Places & Travel ✈️', $$Blue domes, white cliffs.$$),
('The Pyramids',         'Places & Travel ✈️', $$Pharaoh tombs, desert triangles.$$),
('Hollywood',            'Places & Travel ✈️', $$Hillside sign, broken dreams.$$),
('Venice',               'Places & Travel ✈️', $$Sinking city, canal taxis.$$),
('Machu Picchu',         'Places & Travel ✈️', $$Lost Inca mountain city.$$),
('Sydney Opera House',   'Places & Travel ✈️', $$Sailboat roof down under.$$),
('The Sahara',           'Places & Travel ✈️', $$Endless sand, no shortcuts.$$),
('Bora Bora',            'Places & Travel ✈️', $$Overwater bungalow fantasy.$$),
('Tokyo',                'Places & Travel ✈️', $$Neon megacity, bullet trains.$$),

-- ===== Sports 🏆 =====
('Hail Mary',            'Sports 🏆', $$Desperate last-second heave.$$),
('Super Bowl',           'Sports 🏆', $$Football ad-filled finale.$$),
('Slam Dunk',            'Sports 🏆', $$Gravity-defying basket.$$),
('Home Run',             'Sports 🏆', $$Ball over the fence.$$),
('Grand Slam',           'Sports 🏆', $$Bases loaded, then gone.$$),
('The Olympics',         'Sports 🏆', $$Five rings, every fourth year.$$),
('Hat Trick',            'Sports 🏆', $$Three goals, one player.$$),
('World Cup',            'Sports 🏆', $$Global soccer obsession.$$),
('Knockout',             'Sports 🏆', $$Lights out, count ten.$$),
('Penalty Kick',         'Sports 🏆', $$One shot, one keeper.$$),
('Triple Double',        'Sports 🏆', $$Tens across three stats.$$),
('Touchdown',            'Sports 🏆', $$Six points, end zone.$$),
('Checkmate',            'Sports 🏆', $$King trapped, game over.$$),
('Photo Finish',         'Sports 🏆', $$Camera decides the winner.$$),
('March Madness',        'Sports 🏆', $$Bracket-busting hoops chaos.$$),
('Heisman Trophy',       'Sports 🏆', $$Stiff-arm pose, college honor.$$),
('Stanley Cup',          'Sports 🏆', $$Hockey dented silver chalice.$$),
('Tour de France',       'Sports 🏆', $$Yellow jersey, mountain suffering.$$),
('The Masters',          'Sports 🏆', $$Green jacket, Augusta greens.$$),
('Buzzer Beater',        'Sports 🏆', $$Shot at zero seconds.$$),

-- ===== Phrases & Sayings 🗣️ =====
('Bite the Bullet',      'Phrases & Sayings 🗣️', $$Endure the painful thing.$$),
('Break the Ice',        'Phrases & Sayings 🗣️', $$Ease first awkwardness.$$),
('Piece of Cake',        'Phrases & Sayings 🗣️', $$Absurdly easy task.$$),
('Cold Feet',            'Phrases & Sayings 🗣️', $$Last-minute wedding panic.$$),
('Spill the Beans',      'Phrases & Sayings 🗣️', $$Leak the secret.$$),
('Couch Potato',         'Phrases & Sayings 🗣️', $$Sofa-dwelling channel surfer.$$),
('Hit the Hay',          'Phrases & Sayings 🗣️', $$Off to sleep.$$),
('Under the Weather',    'Phrases & Sayings 🗣️', $$Feeling a bit sick.$$),
('Once in a Blue Moon',  'Phrases & Sayings 🗣️', $$Almost never happens.$$),
('Burning the Midnight Oil','Phrases & Sayings 🗣️', $$Working absurdly late.$$),
('Raining Cats and Dogs','Phrases & Sayings 🗣️', $$Absolute downpour.$$),
('Bull in a China Shop', 'Phrases & Sayings 🗣️', $$Clumsy among delicate things.$$),
('Kill Two Birds',       'Phrases & Sayings 🗣️', $$One stone, two wins.$$),
('Barking up the Wrong Tree','Phrases & Sayings 🗣️', $$Chasing the wrong lead.$$),
('The Ball Is in Your Court','Phrases & Sayings 🗣️', $$Your move now.$$),
('Caught Red Handed',    'Phrases & Sayings 🗣️', $$Busted mid-crime.$$),
('Let the Cat Out of the Bag','Phrases & Sayings 🗣️', $$Reveal the surprise.$$),
('Best of Both Worlds',  'Phrases & Sayings 🗣️', $$Win without trade-offs.$$),
('Speak of the Devil',   'Phrases & Sayings 🗣️', $$They just appeared.$$),
('Cut to the Chase',     'Phrases & Sayings 🗣️', $$Skip to the point.$$),

-- ===== Science & Nature 🔬 =====
('The Solar System',     'Science & Nature 🔬', $$One star, eight planets.$$),
('Black Hole',           'Science & Nature 🔬', $$Light point of no return.$$),
('Photosynthesis',       'Science & Nature 🔬', $$Plants eating sunlight.$$),
('Big Bang',             'Science & Nature 🔬', $$Everything loud beginning.$$),
('Gravity',              'Science & Nature 🔬', $$Why apples fall down.$$),
('Double Helix',         'Science & Nature 🔬', $$Twisted ladder of life.$$),
('Evolution',            'Science & Nature 🔬', $$Survival rewrites the species.$$),
('The Northern Lights',  'Science & Nature 🔬', $$Sky green curtain.$$),
('Tectonic Plates',      'Science & Nature 🔬', $$Earth shifting puzzle pieces.$$),
('Volcano',              'Science & Nature 🔬', $$Mountain that spits fire.$$),
('Periodic Table',       'Science & Nature 🔬', $$Elements in tidy boxes.$$),
('Lightning',            'Science & Nature 🔬', $$Sky electric crack.$$),
('The Water Cycle',      'Science & Nature 🔬', $$Rain endless commute.$$),
('Quantum Physics',      'Science & Nature 🔬', $$Tiny things, big headaches.$$),
('Coral Reef',           'Science & Nature 🔬', $$Underwater rainbow city.$$),
('Hurricane',            'Science & Nature 🔬', $$Spinning ocean fury.$$),
('Speed of Light',       'Science & Nature 🔬', $$Universe hard limit.$$),
('Natural Selection',    'Science & Nature 🔬', $$Nature picks the fittest.$$),
('The Food Chain',       'Science & Nature 🔬', $$Who eats whom.$$),
('Solar Eclipse',        'Science & Nature 🔬', $$Moon photobombs the sun.$$),

-- ===== Books & Characters 📚 =====
('Sherlock Holmes',      'Books & Characters 📚', $$Pipe, violin, smug deductions.$$),
('Harry Potter',         'Books & Characters 📚', $$Lightning scar, boy wizard.$$),
('Romeo and Juliet',     'Books & Characters 📚', $$Teen lovers, terrible plan.$$),
('Moby Dick',            'Books & Characters 📚', $$Captain, white whale obsession.$$),
('Pride and Prejudice',  'Books & Characters 📚', $$Mr Darcy slow thaw.$$),
('The Great Gatsby',     'Books & Characters 📚', $$Green light, doomed parties.$$),
('Frankenstein',         'Books & Characters 📚', $$Doctor regrettable creation.$$),
('Alice in Wonderland',  'Books & Characters 📚', $$Rabbit hole, mad tea.$$),
('The Hobbit',           'Books & Characters 📚', $$Reluctant burglar, dragon gold.$$),
('Dracula',              'Books & Characters 📚', $$Transylvanian neck enthusiast.$$),
('Peter Pan',            'Books & Characters 📚', $$Boy refusing to grow.$$),
('The Cat in the Hat',   'Books & Characters 📚', $$Chaos in striped headwear.$$),
('Winnie the Pooh',      'Books & Characters 📚', $$Honey-obsessed stuffed bear.$$),
('Lord of the Flies',    'Books & Characters 📚', $$Schoolboys, island, savagery.$$),
('The Hunger Games',     'Books & Characters 📚', $$Televised teen deathmatch.$$),
('Don Quixote',          'Books & Characters 📚', $$Old knight fights windmills.$$),
('Little Women',         'Books & Characters 📚', $$Four sisters, wartime growing.$$),
('Huckleberry Finn',     'Books & Characters 📚', $$Raft kid, big river.$$),
('Tom Sawyer',           'Books & Characters 📚', $$Fence-painting con artist.$$),
('The Odyssey',          'Books & Characters 📚', $$Ten-year voyage home.$$),

-- ===== Video Games 🎮 =====
('Donkey Kong',          'Video Games 🎮', $$Barrel-throwing ape, trapped girl.$$),
('Super Mario',          'Video Games 🎮', $$Plumber, mushrooms, princess rescue.$$),
('The Legend of Zelda',  'Video Games 🎮', $$Green elf, master sword.$$),
('Minecraft',            'Video Games 🎮', $$Blocky world, creepers explode.$$),
('Pac Man',              'Video Games 🎮', $$Pellet muncher, ghost dodger.$$),
('Tetris',               'Video Games 🎮', $$Falling blocks, no breaks.$$),
('Fortnite',             'Video Games 🎮', $$Last standing, dance emotes.$$),
('Sonic the Hedgehog',   'Video Games 🎮', $$Blue blur, gold rings.$$),
('Pokemon',              'Video Games 🎮', $$Gotta catch them all.$$),
('Grand Theft Auto',     'Video Games 🎮', $$Crime sandbox mayhem.$$),
('Space Invaders',       'Video Games 🎮', $$Descending pixel aliens.$$),
('Call of Duty',         'Video Games 🎮', $$Military shooter, loud lobbies.$$),
('Street Fighter',       'Video Games 🎮', $$Fireball, arcade brawls.$$),
('Angry Birds',          'Video Games 🎮', $$Slingshot vengeance on pigs.$$),
('Final Fantasy',        'Video Games 🎮', $$Spiky hair, endless sequels.$$),
('Candy Crush',          'Video Games 🎮', $$Matching sweets, sneaky charges.$$),
('World of Warcraft',    'Video Games 🎮', $$Orcs, raids, lost weekends.$$),
('Mortal Kombat',        'Video Games 🎮', $$Spine-ripping finishers.$$),
('Among Us',             'Video Games 🎮', $$Spaceship trust issues.$$),
('Halo',                 'Video Games 🎮', $$Green armor, alien war.$$),

-- ===== Brands & Logos 🏷️ =====
('Coca Cola',            'Brands & Logos 🏷️', $$Secret formula, red can.$$),
('Nike',                 'Brands & Logos 🏷️', $$Swoosh, just do it.$$),
('Apple',                'Brands & Logos 🏷️', $$Bitten fruit, pricey gadgets.$$),
('McDonalds',            'Brands & Logos 🏷️', $$Golden arches, clown mascot.$$),
('Google',               'Brands & Logos 🏷️', $$Verb for searching.$$),
('Starbucks',            'Brands & Logos 🏷️', $$Green siren, misspelled cups.$$),
('Amazon',               'Brands & Logos 🏷️', $$Smiling arrow, doorstep boxes.$$),
('Netflix',              'Brands & Logos 🏷️', $$Red N, chill euphemism.$$),
('Disney',               'Brands & Logos 🏷️', $$Mouse ears, castle logo.$$),
('Tesla',                'Brands & Logos 🏷️', $$Electric cars, eccentric boss.$$),
('Lego',                 'Brands & Logos 🏷️', $$Plastic bricks, barefoot menace.$$),
('Ferrari',              'Brands & Logos 🏷️', $$Prancing horse, red speed.$$),
('Rolex',                'Brands & Logos 🏷️', $$Crown logo, wrist flex.$$),
('Adidas',               'Brands & Logos 🏷️', $$Three stripes rival.$$),
('Spotify',              'Brands & Logos 🏷️', $$Green circle, shuffled playlists.$$),
('Lays',                 'Brands & Logos 🏷️', $$Cannot eat just one.$$),
('Gucci',                'Brands & Logos 🏷️', $$Double G, loud luxury.$$),
('Red Bull',             'Brands & Logos 🏷️', $$Wings in a can.$$),
('Ikea',                 'Brands & Logos 🏷️', $$Flat-pack, allen-wrench tears.$$),
('Pringles',             'Brands & Logos 🏷️', $$Mustached man, stackable chips.$$),

-- ===== Tech & Internet 💻 =====
('Artificial Intelligence','Tech & Internet 💻', $$Machines that improvise facts.$$),
('World Wide Web',       'Tech & Internet 💻', $$The www prefix.$$),
('Social Media',         'Tech & Internet 💻', $$Scrolling for validation.$$),
('Bitcoin',              'Tech & Internet 💻', $$Imaginary coins, real volatility.$$),
('Cloud Storage',        'Tech & Internet 💻', $$Files on someone computer.$$),
('Emoji',                'Tech & Internet 💻', $$Tiny faces, big feelings.$$),
('Smartphone',           'Tech & Internet 💻', $$Pocket-sized everything.$$),
('Cryptocurrency',       'Tech & Internet 💻', $$Digital gold rush.$$),
('Virtual Reality',      'Tech & Internet 💻', $$Headset, fake worlds.$$),
('Search Engine',        'Tech & Internet 💻', $$Question answering machine.$$),
('Cybersecurity',        'Tech & Internet 💻', $$Hackers worst day.$$),
('Streaming',            'Tech & Internet 💻', $$Binge without downloads.$$),
('The Metaverse',        'Tech & Internet 💻', $$Promised digital nowhere.$$),
('Hashtag',              'Tech & Internet 💻', $$Pound sign goes viral.$$),
('Going Viral',          'Tech & Internet 💻', $$Internet wildfire fame.$$),
('Operating System',     'Tech & Internet 💻', $$The boss software.$$),
('Touchscreen',          'Tech & Internet 💻', $$Fingerprints as input.$$),
('Data Breach',          'Tech & Internet 💻', $$Passwords on the loose.$$),
('Wireless Charging',    'Tech & Internet 💻', $$Powered by a pad.$$),
('Two Factor Authentication','Tech & Internet 💻', $$Code after your password.$$);

-- ============================================================
-- Round 2: +20 per category (total 40 each). Additive — distinct from round 1.
-- ============================================================
INSERT INTO public.daily_puzzles (phrase, category, clue) VALUES
('The Avengers',         'Movies & TV 🎬', $$Earth's mightiest squabbling heroes.$$),
('Frozen',               'Movies & TV 🎬', $$Snow queen, let it go.$$),
('Finding Nemo',         'Movies & TV 🎬', $$Lost clownfish, forgetful sidekick.$$),
('Shrek',                'Movies & TV 🎬', $$Ogre, donkey, swamp romance.$$),
('The Wizard of Oz',     'Movies & TV 🎬', $$Yellow brick road trip.$$),
('Rocky',                'Movies & TV 🎬', $$Philadelphia boxer, frozen meat.$$),
('Home Alone',           'Movies & TV 🎬', $$Forgotten kid booby-traps house.$$),
('Mean Girls',           'Movies & TV 🎬', $$Pink on Wednesdays.$$),
('The Hangover',         'Movies & TV 🎬', $$Vegas blackout, missing groom.$$),
('Spider Man',           'Movies & TV 🎬', $$Radioactive bite, web slinger.$$),
('Black Panther',        'Movies & TV 🎬', $$Wakanda forever.$$),
('Squid Game',           'Movies & TV 🎬', $$Deadly children's games.$$),
('Ted Lasso',            'Movies & TV 🎬', $$Optimistic coach abroad.$$),
('Seinfeld',             'Movies & TV 🎬', $$Show about nothing.$$),
('The Sopranos',         'Movies & TV 🎬', $$Mob boss in therapy.$$),
('The Mandalorian',      'Movies & TV 🎬', $$Bounty hunter, tiny ward.$$),
('Wednesday',            'Movies & TV 🎬', $$Deadpan Addams daughter.$$),
('Better Call Saul',     'Movies & TV 🎬', $$Crooked lawyer origin.$$),
('Gladiator',            'Movies & TV 🎬', $$Are you not entertained?$$),
('Grease',               'Movies & TV 🎬', $$Summer lovin, greased lightning.$$),
('Shake It Off',         'Music 🎵', $$Haters gonna hate.$$),
('Single Ladies',        'Music 🎵', $$Put a ring on it.$$),
('Like a Rolling Stone', 'Music 🎵', $$Dylan asks how it feels.$$),
('Sweet Home Alabama',   'Music 🎵', $$Southern rock pride.$$),
('Wonderwall',           'Music 🎵', $$Oasis singalong staple.$$),
('Hey Jude',             'Music 🎵', $$Sad song made better.$$),
('Smooth Criminal',      'Music 🎵', $$Annie, are you okay?$$),
('Blinding Lights',      'Music 🎵', $$Eighties synth, midnight drive.$$),
('Shape of You',         'Music 🎵', $$Sheeran club romance.$$),
('Levitating',           'Music 🎵', $$Dua Lipa disco float.$$),
('Seven Nation Army',    'Music 🎵', $$Stadium chant riff.$$),
('Mr Brightside',        'Music 🎵', $$Killers jealousy spiral.$$),
('Viva la Vida',         'Music 🎵', $$Coldplay's fallen king.$$),
('Bad Guy',              'Music 🎵', $$Whispered, duh.$$),
('Gangnam Style',        'Music 🎵', $$Horse dance gone viral.$$),
('Africa',               'Music 🎵', $$Toto blesses the rains.$$),
('Hey Ya',               'Music 🎵', $$Shake it, Polaroid.$$),
('Take On Me',           'Music 🎵', $$Pencil-sketch chase.$$),
('Born to Run',          'Music 🎵', $$Springsteen escape anthem.$$),
('Crazy in Love',        'Music 🎵', $$Beyonce, uh oh horns.$$),
('Martin Luther King',   'Famous People 🌟', $$Dream speech, march leader.$$),
('Mother Teresa',        'Famous People 🌟', $$Saint of the slums.$$),
('Stephen Hawking',      'Famous People 🌟', $$Black holes, robotic voice.$$),
('Queen Elizabeth',      'Famous People 🌟', $$Longest-reigning British monarch.$$),
('Napoleon Bonaparte',   'Famous People 🌟', $$Short emperor, big ambition.$$),
('Pablo Picasso',        'Famous People 🌟', $$Cubism, scrambled faces.$$),
('Frida Kahlo',          'Famous People 🌟', $$Unibrow, painful self-portraits.$$),
('Mark Zuckerberg',      'Famous People 🌟', $$Hoodie, your data.$$),
('Tom Hanks',            'Famous People 🌟', $$Nicest man, deserted island.$$),
('Serena Williams',      'Famous People 🌟', $$Tennis power, sister rivalry.$$),
('Bill Gates',           'Famous People 🌟', $$Windows mogul turned philanthropist.$$),
('Rosa Parks',           'Famous People 🌟', $$Stayed in her seat.$$),
('Charlie Chaplin',      'Famous People 🌟', $$Silent tramp, tiny mustache.$$),
('Neil Armstrong',       'Famous People 🌟', $$One small step.$$),
('Greta Thunberg',       'Famous People 🌟', $$How dare you.$$),
('Elvis Presley',        'Famous People 🌟', $$Hips, jumpsuit, the King.$$),
('Joan of Arc',          'Famous People 🌟', $$Teen saint, burning stake.$$),
('Winston Churchill',    'Famous People 🌟', $$Cigar, never surrender.$$),
('Audrey Hepburn',       'Famous People 🌟', $$Tiffany breakfast elegance.$$),
('Christopher Columbus', 'Famous People 🌟', $$Sailed, got famously lost.$$),
('Cheeseburger',         'Food & Drink 🍔', $$Patty plus a slice.$$),
('Donut',                'Food & Drink 🍔', $$Sweet ring, cop cliche.$$),
('Burrito',              'Food & Drink 🍔', $$Foil-wrapped, overstuffed.$$),
('Lasagna',              'Food & Drink 🍔', $$Layered pasta, Garfield's love.$$),
('Fried Chicken',        'Food & Drink 🍔', $$Crispy, finger-licking bird.$$),
('Milkshake',            'Food & Drink 🍔', $$Brings boys to the yard.$$),
('Nachos',               'Food & Drink 🍔', $$Chips drowning in cheese.$$),
('Cheesecake',           'Food & Drink 🍔', $$Dense, creamy, New York.$$),
('Steak',                'Food & Drink 🍔', $$Sizzling slab, medium rare.$$),
('Popcorn',              'Food & Drink 🍔', $$Movie night kernels.$$),
('Apple Pie',            'Food & Drink 🍔', $$America in a crust.$$),
('Pho',                  'Food & Drink 🍔', $$Vietnamese broth bowl.$$),
('Dumplings',            'Food & Drink 🍔', $$Steamed pockets, soy dip.$$),
('Lemonade',             'Food & Drink 🍔', $$Sour summer stand.$$),
('Waffles',              'Food & Drink 🍔', $$Syrup grids.$$),
('Curry',                'Food & Drink 🍔', $$Spiced stew, regional pride.$$),
('Smoothie',             'Food & Drink 🍔', $$Blended fruit, fake health.$$),
('Cotton Candy',         'Food & Drink 🍔', $$Spun sugar cloud.$$),
('Espresso',             'Food & Drink 🍔', $$Tiny cup, big jolt.$$),
('Bagel',                'Food & Drink 🍔', $$Boiled, holey, schmear ready.$$),
('Mount Fuji',           'Places & Travel ✈️', $$Japan's snowy cone.$$),
('The Leaning Tower',    'Places & Travel ✈️', $$Pisa's tilting mistake.$$),
('Stonehenge',           'Places & Travel ✈️', $$Mysterious standing stones.$$),
('The Taj Mahal',        'Places & Travel ✈️', $$Marble monument to love.$$),
('New York City',        'Places & Travel ✈️', $$The big apple.$$),
('London',               'Places & Travel ✈️', $$Red buses, foggy crown.$$),
('Paris',                'Places & Travel ✈️', $$City of lights.$$),
('Mount Kilimanjaro',    'Places & Travel ✈️', $$Africa's snowy summit.$$),
('The Amazon',           'Places & Travel ✈️', $$Vast green rainforest.$$),
('Dubai',                'Places & Travel ✈️', $$Desert skyscrapers, instant wealth.$$),
('Antarctica',           'Places & Travel ✈️', $$Frozen penguin continent.$$),
('Rome',                 'Places & Travel ✈️', $$All roads lead here.$$),
('The Golden Gate',      'Places & Travel ✈️', $$Foggy orange bridge.$$),
('Mount Vesuvius',       'Places & Travel ✈️', $$Buried Pompeii in ash.$$),
('The Maldives',         'Places & Travel ✈️', $$Sinking island paradise.$$),
('Yellowstone',          'Places & Travel ✈️', $$Geysers and grumpy bears.$$),
('Easter Island',        'Places & Travel ✈️', $$Giant stone heads.$$),
('The Alps',             'Places & Travel ✈️', $$Snowy European spine.$$),
('Cairo',                'Places & Travel ✈️', $$Pyramids next door.$$),
('Barcelona',            'Places & Travel ✈️', $$Gaudi's melting cathedral.$$),
('Free Throw',           'Sports 🏆', $$Uncontested foul-line shot.$$),
('Offside',              'Sports 🏆', $$Soccer's confusing flag.$$),
('Half Time',            'Sports 🏆', $$Show with snacks.$$),
('Wimbledon',            'Sports 🏆', $$Strawberries and grass tennis.$$),
('The World Series',     'Sports 🏆', $$Baseball's autumn crown.$$),
('Field Goal',           'Sports 🏆', $$Three points, uprights.$$),
('Bicycle Kick',         'Sports 🏆', $$Overhead acrobatic strike.$$),
('Royal Rumble',         'Sports 🏆', $$Thirty wrestlers, one ring.$$),
('Sudden Death',         'Sports 🏆', $$Next score wins.$$),
('Pole Vault',           'Sports 🏆', $$Pole-assisted high jump.$$),
('Marathon',             'Sports 🏆', $$Twenty-six grueling miles.$$),
('Strikeout',            'Sports 🏆', $$Three swings, sit down.$$),
('Hole in One',          'Sports 🏆', $$Tee to cup, once.$$),
('Red Card',             'Sports 🏆', $$Soccer's ejection slip.$$),
('Power Play',           'Sports 🏆', $$Hockey's man advantage.$$),
('Grand Prix',           'Sports 🏆', $$Formula one circuit.$$),
('The Ryder Cup',        'Sports 🏆', $$Golf, continents collide.$$),
('Triple Crown',         'Sports 🏆', $$Three-race horse glory.$$),
('Full Court Press',     'Sports 🏆', $$Defense, end to end.$$),
('Decathlon',            'Sports 🏆', $$Ten events, one champion.$$),
('Back to Square One',   'Phrases & Sayings 🗣️', $$Start all over.$$),
('Beat Around the Bush', 'Phrases & Sayings 🗣️', $$Avoid the point.$$),
('Hit the Nail on the Head','Phrases & Sayings 🗣️', $$Exactly right.$$),
('The Last Straw',       'Phrases & Sayings 🗣️', $$Final breaking point.$$),
('Cost an Arm and a Leg','Phrases & Sayings 🗣️', $$Painfully expensive.$$),
('Add Fuel to the Fire', 'Phrases & Sayings 🗣️', $$Make it worse.$$),
('A Blessing in Disguise','Phrases & Sayings 🗣️', $$Hidden good news.$$),
('Throw in the Towel',   'Phrases & Sayings 🗣️', $$Give up.$$),
('Read Between the Lines','Phrases & Sayings 🗣️', $$Find hidden meaning.$$),
('Jump on the Bandwagon','Phrases & Sayings 🗣️', $$Join the trend.$$),
('The Tip of the Iceberg','Phrases & Sayings 🗣️', $$Small visible part.$$),
('Pull Yourself Together','Phrases & Sayings 🗣️', $$Calm down.$$),
('Burn the Bridges',     'Phrases & Sayings 🗣️', $$End it permanently.$$),
('Out of the Blue',      'Phrases & Sayings 🗣️', $$Completely unexpected.$$),
('A Penny for Your Thoughts','Phrases & Sayings 🗣️', $$What are you thinking?$$),
('The Whole Nine Yards', 'Phrases & Sayings 🗣️', $$Everything, all of it.$$),
('When Pigs Fly',        'Phrases & Sayings 🗣️', $$Never going to happen.$$),
('Steal the Show',       'Phrases & Sayings 🗣️', $$Outshine everyone.$$),
('Face the Music',       'Phrases & Sayings 🗣️', $$Accept the consequences.$$),
('Down to Earth',        'Phrases & Sayings 🗣️', $$Humble and practical.$$),
('Milky Way',            'Science & Nature 🔬', $$Our home galaxy.$$),
('Climate Change',       'Science & Nature 🔬', $$Warming, melting, denial.$$),
('Greenhouse Effect',    'Science & Nature 🔬', $$Trapped heat blanket.$$),
('Cell Division',        'Science & Nature 🔬', $$One becomes two.$$),
('The Big Dipper',       'Science & Nature 🔬', $$Ladle of stars.$$),
('Supernova',            'Science & Nature 🔬', $$A star's violent death.$$),
('Magnetism',            'Science & Nature 🔬', $$Invisible pulling force.$$),
('Ecosystem',            'Science & Nature 🔬', $$Web of living things.$$),
('Genetics',             'Science & Nature 🔬', $$Inherited blueprint.$$),
('The Ozone Layer',      'Science & Nature 🔬', $$Sky's sunscreen.$$),
('Comet',                'Science & Nature 🔬', $$Icy tail across sky.$$),
('Antibodies',           'Science & Nature 🔬', $$Immune system soldiers.$$),
('Friction',             'Science & Nature 🔬', $$Resistance that slows.$$),
('Density',              'Science & Nature 🔬', $$Mass packed in space.$$),
('Stem Cells',           'Science & Nature 🔬', $$Body's blank-slate cells.$$),
('Erosion',              'Science & Nature 🔬', $$Wind and water sculpting.$$),
('Vaccination',          'Science & Nature 🔬', $$Training the immune system.$$),
('The Atmosphere',       'Science & Nature 🔬', $$Air blanket around Earth.$$),
('Carbon Dioxide',       'Science & Nature 🔬', $$Exhaled greenhouse gas.$$),
('Metamorphosis',        'Science & Nature 🔬', $$Caterpillar to butterfly.$$),
('The Lord of the Rings','Books & Characters 📚', $$One ring, long walk.$$),
('Pinocchio',            'Books & Characters 📚', $$Lying puppet, growing nose.$$),
('Cinderella',           'Books & Characters 📚', $$Lost slipper, midnight curfew.$$),
('Snow White',           'Books & Characters 📚', $$Poisoned apple, seven roommates.$$),
('Treasure Island',      'Books & Characters 📚', $$Pirates, map, buried gold.$$),
('The Jungle Book',      'Books & Characters 📚', $$Boy raised by wolves.$$),
('Wuthering Heights',    'Books & Characters 📚', $$Moors, doomed obsession.$$),
('Of Mice and Men',      'Books & Characters 📚', $$Dreaming of rabbits.$$),
('The Three Musketeers', 'Books & Characters 📚', $$All for one.$$),
('Anna Karenina',        'Books & Characters 📚', $$Affair, oncoming train.$$),
('Crime and Punishment', 'Books & Characters 📚', $$Guilty student spirals.$$),
('War and Peace',        'Books & Characters 📚', $$Very long Russian epic.$$),
('The Catcher in the Rye','Books & Characters 📚', $$Whiny teen, red hat.$$),
('Robinson Crusoe',      'Books & Characters 📚', $$Castaway, lonely island.$$),
('A Christmas Carol',    'Books & Characters 📚', $$Three ghosts visit Scrooge.$$),
('Matilda',              'Books & Characters 📚', $$Telekinetic genius girl.$$),
('Hamlet',               'Books & Characters 📚', $$To be or not.$$),
('The Grinch',           'Books & Characters 📚', $$Green grump steals Christmas.$$),
('Macbeth',              'Books & Characters 📚', $$Bloody crown, guilty hands.$$),
('Oliver Twist',         'Books & Characters 📚', $$Please sir, more gruel.$$),
('The Sims',             'Video Games 🎮', $$Virtual people, pause god.$$),
('Animal Crossing',      'Video Games 🎮', $$Island debt to a raccoon.$$),
('Red Dead Redemption',  'Video Games 🎮', $$Wild west outlaw saga.$$),
('Assassins Creed',      'Video Games 🎮', $$Hooded historical stabbing.$$),
('The Last of Us',       'Video Games 🎮', $$Fungus apocalypse escort.$$),
('League of Legends',    'Video Games 🎮', $$Five-lane war.$$),
('Cyberpunk',            'Video Games 🎮', $$Neon future, buggy launch.$$),
('God of War',           'Video Games 🎮', $$Angry dad, Greek gods.$$),
('Resident Evil',        'Video Games 🎮', $$Mansion of zombies.$$),
('Mario Kart',           'Video Games 🎮', $$Banana peels, blue shells.$$),
('Overwatch',            'Video Games 🎮', $$Hero shooter, payload push.$$),
('Roblox',               'Video Games 🎮', $$Kid-built game universe.$$),
('Elden Ring',           'Video Games 🎮', $$Open world, frequent death.$$),
('Dark Souls',           'Video Games 🎮', $$Prepare to die.$$),
('Metroid',              'Video Games 🎮', $$Bounty hunter, alien caves.$$),
('The Witcher',          'Video Games 🎮', $$Monster hunter, silver sword.$$),
('Bioshock',             'Video Games 🎮', $$Underwater dystopia.$$),
('Temple Run',           'Video Games 🎮', $$Endless sprint from monkeys.$$),
('Counter Strike',       'Video Games 🎮', $$Terrorists versus counter.$$),
('Stardew Valley',       'Video Games 🎮', $$Inherited farm, cozy grind.$$),
('Pepsi',                'Brands & Logos 🏷️', $$Coke's blue rival.$$),
('Microsoft',            'Brands & Logos 🏷️', $$Windows and clippy.$$),
('Samsung',              'Brands & Logos 🏷️', $$Korean everything maker.$$),
('Burger King',          'Brands & Logos 🏷️', $$Have it your way.$$),
('Walmart',              'Brands & Logos 🏷️', $$Big box, low prices.$$),
('Lamborghini',          'Brands & Logos 🏷️', $$Scissor doors, bull badge.$$),
('Chanel',               'Brands & Logos 🏷️', $$Double C, French couture.$$),
('Louis Vuitton',        'Brands & Logos 🏷️', $$Monogram luggage flex.$$),
('Toyota',               'Brands & Logos 🏷️', $$Reliable, runs forever.$$),
('KFC',                  'Brands & Logos 🏷️', $$Colonel's secret spices.$$),
('Subway',               'Brands & Logos 🏷️', $$Footlong sandwich chain.$$),
('Twitter',              'Brands & Logos 🏷️', $$Birds, now an X.$$),
('Instagram',            'Brands & Logos 🏷️', $$Filtered photo grid.$$),
('YouTube',              'Brands & Logos 🏷️', $$Endless video rabbit hole.$$),
('Dominos',              'Brands & Logos 🏷️', $$Thirty-minute pizza promise.$$),
('Heineken',             'Brands & Logos 🏷️', $$Green bottle lager.$$),
('Visa',                 'Brands & Logos 🏷️', $$Everywhere you want to be.$$),
('PlayStation',          'Brands & Logos 🏷️', $$Sony's gaming console.$$),
('Xbox',                 'Brands & Logos 🏷️', $$Green gaming console.$$),
('Reebok',               'Brands & Logos 🏷️', $$Retro pump sneakers.$$),
('Machine Learning',     'Tech & Internet 💻', $$Algorithms that self-improve.$$),
('Self Driving Car',     'Tech & Internet 💻', $$Robot at the wheel.$$),
('Quantum Computing',    'Tech & Internet 💻', $$Qubits break encryption.$$),
('Open Source',          'Tech & Internet 💻', $$Free, shared code.$$),
('Augmented Reality',    'Tech & Internet 💻', $$Digital layer on reality.$$),
('Facial Recognition',   'Tech & Internet 💻', $$Your face unlocks it.$$),
('The Dark Web',         'Tech & Internet 💻', $$Internet's shady basement.$$),
('Net Neutrality',       'Tech & Internet 💻', $$All traffic treated equal.$$),
('Phishing',             'Tech & Internet 💻', $$Fake email, real theft.$$),
('Browser Cookies',      'Tech & Internet 💻', $$Tracking your crumbs.$$),
('Encryption',           'Tech & Internet 💻', $$Scrambled secrets.$$),
('Bandwidth',            'Tech & Internet 💻', $$Pipe size for data.$$),
('The Algorithm',        'Tech & Internet 💻', $$Decides what you see.$$),
('Drone Delivery',       'Tech & Internet 💻', $$Package from the sky.$$),
('Smart Home',           'Tech & Internet 💻', $$Voice-controlled house.$$),
('Blockchain',           'Tech & Internet 💻', $$Tamper-proof ledger.$$),
('Video Call',           'Tech & Internet 💻', $$Pajamas below camera.$$),
('App Store',            'Tech & Internet 💻', $$Tap to download.$$),
('Password Manager',     'Tech & Internet 💻', $$One vault, many keys.$$),
('Fiber Optic',          'Tech & Internet 💻', $$Internet at light speed.$$);
